begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('60000000-0000-0000-0000-000000000001','owner@agreements.test',now()),
 ('60000000-0000-0000-0000-000000000002','staff@agreements.test',now()),
 ('60000000-0000-0000-0000-000000000003','reader@agreements.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"60000000-0000-0000-0000-000000000001","role":"authenticated"}';
select set_config('test.a',create_tenant('Agreement A','agreement-a',gen_random_uuid())::text,true);
select set_config('test.b',create_tenant('Agreement B','agreement-b',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.a')::uuid,gen_random_uuid(),'Seller','','123')::text,true);
select set_config('test.v1',gen_random_uuid()::text,true);
select set_config('test.v2',gen_random_uuid()::text,true);
select set_config('test.evidence',gen_random_uuid()::text,true);
select set_config('test.bag',gen_random_uuid()::text,true);
select lives_ok($$select receive_bag(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'Before agreement')$$,'no initial agreement prerequisite');
select lives_ok($$select publish_seller_agreement(current_setting('test.a')::uuid,current_setting('test.v1')::uuid,null,'Test terms','Fictional test text','sv',true)$$,'owner publishes');
select lives_ok($$select publish_seller_agreement(current_setting('test.a')::uuid,current_setting('test.v1')::uuid,null,'Test terms','Fictional test text','sv',true)$$,'publication replay resolves original version');
select is((select count(*) from seller_agreement_versions),1::bigint,'publication replay does not duplicate');
select throws_like($$select publish_seller_agreement(current_setting('test.a')::uuid,gen_random_uuid(),null,'Other','Text','sv',false)$$,'%AGREEMENT_CHANGED%','stale publication rejected');
select throws_like($$select publish_seller_agreement(current_setting('test.a')::uuid,current_setting('test.v1')::uuid,null,'Changed','Fictional test text','sv',true)$$,'%REQUEST_CONFLICT%','request cannot rewrite published text');
select throws_like($$select receive_bag(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'Old client')$$,'%AGREEMENT_CHANGED%','legacy client cannot ignore an unseen agreement');
select throws_like($$select receive_bag_with_agreement(current_setting('test.a')::uuid,current_setting('test.bag')::uuid,current_setting('test.seller')::uuid,'Bag',current_setting('test.v1')::uuid)$$,'%AGREEMENT_REQUIRED%','required evidence enforced in SQL');
select throws_like($$select record_agreement_evidence(current_setting('test.b')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,current_setting('test.v1')::uuid,'Paper 1')$$,'%SELLER_NOT_FOUND%','cross-store seller cannot be referenced');
select throws_like($$select record_agreement_evidence(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,current_setting('test.v1')::uuid,' ')$$,'%INVALID_INPUT%','reference cannot be empty');
select lives_ok($$select record_agreement_evidence(current_setting('test.a')::uuid,current_setting('test.evidence')::uuid,current_setting('test.seller')::uuid,current_setting('test.v1')::uuid,'Paper TEST-1')$$,'staff evidence recorded explicitly');
select lives_ok($$select record_agreement_evidence(current_setting('test.a')::uuid,current_setting('test.evidence')::uuid,current_setting('test.seller')::uuid,current_setting('test.v1')::uuid,'Paper TEST-1')$$,'evidence replay resolves original');
select is((select count(*) from seller_agreement_evidence),1::bigint,'evidence not duplicated');
select lives_ok($$select receive_bag_with_agreement(current_setting('test.a')::uuid,current_setting('test.bag')::uuid,current_setting('test.seller')::uuid,'Bag',current_setting('test.v1')::uuid)$$,'receipt accepts matching evidence');
select is((select agreement_version_id from bag_receipts where id=current_setting('test.bag')::uuid),current_setting('test.v1')::uuid,'receipt preserves agreement version');
select is((select agreement_evidence_id from bag_receipts where id=current_setting('test.bag')::uuid),current_setting('test.evidence')::uuid,'receipt preserves evidence');
select publish_seller_agreement(current_setting('test.a')::uuid,current_setting('test.v2')::uuid,current_setting('test.v1')::uuid,'New terms','New fictional test text','en',true);
select lives_ok($$select receive_bag_with_agreement(current_setting('test.a')::uuid,current_setting('test.bag')::uuid,current_setting('test.seller')::uuid,'Bag',current_setting('test.v1')::uuid)$$,'successful receipt retries after new publication');
select is((select agreement_version_id from bag_receipts where id=current_setting('test.bag')::uuid),current_setting('test.v1')::uuid,'new terms do not rewrite old receipt');
select throws_like($$select receive_bag_with_agreement(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'New bag',current_setting('test.v1')::uuid)$$,'%AGREEMENT_CHANGED%','new receipt must use current version');
select throws_like($$select receive_bag_with_agreement(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'New bag',current_setting('test.v2')::uuid)$$,'%AGREEMENT_REQUIRED%','old evidence does not satisfy new version');
select throws_like($$select record_agreement_evidence(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,current_setting('test.v1')::uuid,'Stale paper')$$,'%AGREEMENT_CHANGED%','stale evidence form rejected');
select lives_ok($$select record_agreement_evidence(current_setting('test.a')::uuid,current_setting('test.evidence')::uuid,current_setting('test.seller')::uuid,current_setting('test.v1')::uuid,'Paper TEST-1')$$,'evidence retry survives supersession');
select throws_ok($$update seller_agreement_versions set body='Overwrite'$$,'42501',null,'published text cannot be updated through API');
select throws_ok($$delete from seller_agreement_evidence$$,'42501',null,'evidence cannot be deleted through API');
reset role;
insert into tenant_members(tenant_id,user_id,role) values
 (current_setting('test.a')::uuid,'60000000-0000-0000-0000-000000000002','staff'),
 (current_setting('test.a')::uuid,'60000000-0000-0000-0000-000000000003','readonly');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"60000000-0000-0000-0000-000000000002","role":"authenticated"}';
select throws_like($$select publish_seller_agreement(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.v2')::uuid,'Staff','Text','sv',false)$$,'%FORBIDDEN%','staff cannot publish');
select lives_ok($$select record_agreement_evidence(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,current_setting('test.v2')::uuid,'Staff reference')$$,'staff can record external evidence');
select throws_like($$select publish_seller_agreement(current_setting('test.b')::uuid,gen_random_uuid(),null,'Cross store','Text','sv',false)$$,'%FORBIDDEN%','staff cannot publish across tenants');
set local "request.jwt.claims"='{"sub":"60000000-0000-0000-0000-000000000003","role":"authenticated"}';
select is((select count(*) from seller_agreement_versions),2::bigint,'readonly sees versions in own store');
select throws_like($$select record_agreement_evidence(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,current_setting('test.v2')::uuid,'Reader')$$,'%FORBIDDEN%','readonly cannot attest evidence');
reset role;
delete from tenant_members where user_id='60000000-0000-0000-0000-000000000002';
set local role authenticated;
set local "request.jwt.claims"='{"sub":"60000000-0000-0000-0000-000000000002","role":"authenticated"}';
select is((select count(*) from seller_agreement_versions),0::bigint,'removed member cannot read terms');
select is((select count(*) from seller_agreement_evidence),0::bigint,'removed member cannot read evidence');
set local role anon;
select throws_ok($$select * from seller_agreement_evidence$$,'42501',null,'anonymous evidence access denied');
select throws_ok($$select publish_seller_agreement(null,null,null,'','', 'sv',false)$$,'42501',null,'anonymous publication denied');
reset role;
select throws_like($$update seller_agreement_versions set title='Changed outside API'$$,'%IMMUTABLE_AGREEMENT_RECORD%','published rows are immutable even outside API grants');
select throws_like($$delete from seller_agreement_evidence$$,'%IMMUTABLE_AGREEMENT_RECORD%','evidence rows are immutable even outside API grants');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"60000000-0000-0000-0000-000000000001","role":"authenticated"}';
select set_config('test.v3',publish_seller_agreement(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.v2')::uuid,'Optional','Optional fictional terms','sv',false)::text,true);
select lives_ok($$select receive_bag_with_agreement(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'Optional evidence bag',current_setting('test.v3')::uuid)$$,'tenant can publish an optional-evidence policy');
reset role;
insert into auth.mfa_factors(id,user_id,factor_type,status,created_at,updated_at)
 values(gen_random_uuid(),'60000000-0000-0000-0000-000000000001','totp','verified',now(),now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"60000000-0000-0000-0000-000000000001","role":"authenticated","aal":"aal1"}';
select is((select count(*) from seller_agreement_evidence),0::bigint,'MFA challenge denies evidence reads');
select throws_like($$select publish_seller_agreement(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.v3')::uuid,'Bypass','Text','sv',false)$$,'%AUTH_REQUIRED%','MFA challenge denies publication');
reset role;
select * from finish();
rollback;
