begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('90000000-0000-4000-8000-000000000001','owner@review.test',now()),
 ('90000000-0000-4000-8000-000000000002','reader@review.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"90000000-0000-4000-8000-000000000001","role":"authenticated"}';
select set_config('test.a',create_tenant('Review A','review-a',gen_random_uuid())::text,true);
select set_config('test.b',create_tenant('Review B','review-b',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.a')::uuid,gen_random_uuid(),'Seller','seller@example.test','')::text,true);
select set_config('test.session',create_reception_session(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid)::text,true);
select set_config('test.agreement',publish_seller_agreement(current_setting('test.a')::uuid,gen_random_uuid(),null,'TEST terms','Fictional terms','en',false)::text,true);
select set_config('test.sources','[{"id":"90000000-0000-4000-8000-000000000010","kind":"observation","reference":"TEST","observation":"Blue jacket"},{"id":"90000000-0000-4000-8000-000000000011","kind":"price-evidence","reference":"TEST appraisal","observation":"Fictional 250 SEK appraisal"}]',true);
select save_reception_sources(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,0,current_setting('test.sources')::jsonb);
select set_config('test.suggestions','{"attributes":[{"slug":"description","definitionVersion":1,"value":"Blue jacket","sourceIds":["90000000-0000-4000-8000-000000000010"],"certainty":"observed"}],"price":{"currency":"SEK","amount":"250.00","rationale":"TEST appraisal","sourceIds":["90000000-0000-4000-8000-000000000011"]},"questions":[]}',true);
select set_config('test.review',gen_random_uuid()::text,true);
select set_config('test.expiry',(now()+interval '1 day')::text,true);
select lives_ok($$select publish_reception_review(current_setting('test.a')::uuid,current_setting('test.review')::uuid,current_setting('test.session')::uuid,1,null,current_setting('test.agreement')::uuid,current_setting('test.suggestions')::jsonb,current_setting('test.expiry')::timestamptz)$$,'publish complete review');
select is((select price_amount from reception_reviews),250.00::numeric,'price stored as numeric');
select is((select agreement_id from reception_reviews),current_setting('test.agreement')::uuid,'review pins terms version');
select lives_ok($$select publish_reception_review(current_setting('test.a')::uuid,current_setting('test.review')::uuid,current_setting('test.session')::uuid,1,null,current_setting('test.agreement')::uuid,current_setting('test.suggestions')::jsonb,current_setting('test.expiry')::timestamptz)$$,'identical retry succeeds');
select is((select count(*) from reception_reviews),1::bigint,'retry persists once');
select throws_like($$select publish_reception_review(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,1,null,current_setting('test.agreement')::uuid,current_setting('test.suggestions')::jsonb,current_setting('test.expiry')::timestamptz)$$,'%RECEPTION_REVIEW_CHANGED%','stale previous review rejected');
select throws_like($$select publish_reception_review(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,2,current_setting('test.review')::uuid,current_setting('test.agreement')::uuid,current_setting('test.suggestions')::jsonb,current_setting('test.expiry')::timestamptz)$$,'%RECEPTION_CHANGED%','source revision must be current');
select throws_like($$select publish_reception_review(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,1,current_setting('test.review')::uuid,current_setting('test.agreement')::uuid,jsonb_set(current_setting('test.suggestions')::jsonb,'{price,sourceIds}','["90000000-0000-4000-8000-000000000010"]'),current_setting('test.expiry')::timestamptz)$$,'%RECEPTION_PRICE_EVIDENCE_REQUIRED%','price cannot cite an observation as price evidence');
select throws_like($$select publish_reception_review(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,1,current_setting('test.review')::uuid,current_setting('test.agreement')::uuid,jsonb_set(current_setting('test.suggestions')::jsonb,'{attributes,0,sourceIds}','["90000000-0000-4000-8000-000000000099"]'),current_setting('test.expiry')::timestamptz)$$,'%RECEPTION_UNKNOWN_SOURCE%','unknown attribute evidence rejected');
select throws_like($$select publish_reception_review(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,1,current_setting('test.review')::uuid,current_setting('test.agreement')::uuid,jsonb_set(current_setting('test.suggestions')::jsonb,'{questions}','["Need label"]'),current_setting('test.expiry')::timestamptz)$$,'%INVALID_INPUT%','unresolved questions cannot be published');
select throws_like($$select publish_reception_review(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,1,current_setting('test.review')::uuid,current_setting('test.agreement')::uuid,jsonb_set(current_setting('test.suggestions')::jsonb,'{attributes,0,certainty}','"tentative"'),current_setting('test.expiry')::timestamptz)$$,'%INVALID_INPUT%','a tentative attribute cannot be published');
select throws_like($$select publish_reception_review(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,1,current_setting('test.review')::uuid,current_setting('test.agreement')::uuid,jsonb_set(current_setting('test.suggestions')::jsonb,'{approved}','true'),current_setting('test.expiry')::timestamptz)$$,'%INVALID_INPUT%','unknown authority field rejected');
select throws_like($$select publish_reception_review(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,1,current_setting('test.review')::uuid,current_setting('test.agreement')::uuid,current_setting('test.suggestions')::jsonb,now())$$,'%RECEPTION_REVIEW_EXPIRED%','expiry boundary rejected');
select throws_like($$select publish_reception_review(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,1,current_setting('test.review')::uuid,current_setting('test.agreement')::uuid,current_setting('test.suggestions')::jsonb,now()+interval '8 days')$$,'%RECEPTION_REVIEW_EXPIRED%','expiry bounded');
select throws_like($$select publish_reception_review(current_setting('test.b')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,1,null,current_setting('test.agreement')::uuid,current_setting('test.suggestions')::jsonb,current_setting('test.expiry')::timestamptz)$$,'%RECEPTION_NOT_FOUND%','session cannot cross stores');
select throws_like($$select publish_reception_review(current_setting('test.a')::uuid,current_setting('test.review')::uuid,current_setting('test.session')::uuid,1,null,current_setting('test.agreement')::uuid,jsonb_set(current_setting('test.suggestions')::jsonb,'{price,amount}','"251.00"'),current_setting('test.expiry')::timestamptz)$$,'%REQUEST_CONFLICT%','retry binds exact proposed price');
select set_config('test.agreement2',publish_seller_agreement(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.agreement')::uuid,'TEST next terms','Fictional changed terms','en',false)::text,true);
select throws_like($$select publish_reception_review(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,1,current_setting('test.review')::uuid,current_setting('test.agreement')::uuid,current_setting('test.suggestions')::jsonb,current_setting('test.expiry')::timestamptz)$$,'%AGREEMENT_CHANGED%','new reviews require current terms');
select is((select agreement_id from reception_reviews),current_setting('test.agreement')::uuid,'new agreement does not rewrite old review');
select lives_ok($$select publish_reception_review(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,1,current_setting('test.review')::uuid,current_setting('test.agreement2')::uuid,current_setting('test.suggestions')::jsonb,current_setting('test.expiry')::timestamptz)$$,'new reviewed terms append version');
select is((select version from reception_reviews_current),2,'latest review is second version');
select lives_ok($$select publish_reception_review(current_setting('test.a')::uuid,current_setting('test.review')::uuid,current_setting('test.session')::uuid,1,null,current_setting('test.agreement')::uuid,current_setting('test.suggestions')::jsonb,current_setting('test.expiry')::timestamptz)$$,'old replay resolves old review');
select is((select version from reception_reviews_current),2,'old replay cannot become current');
reset role;
insert into tenant_members(tenant_id,user_id,role) values(current_setting('test.a')::uuid,'90000000-0000-4000-8000-000000000002','readonly');
select throws_like($$update reception_reviews set expires_at=now()$$,'%IMMUTABLE_RECEPTION%','review snapshots immutable');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"90000000-0000-4000-8000-000000000002","role":"authenticated"}';
select is((select count(*) from reception_reviews),2::bigint,'readonly reads review history');
select throws_like($$select publish_reception_review(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,1,null,current_setting('test.agreement')::uuid,current_setting('test.suggestions')::jsonb,current_setting('test.expiry')::timestamptz)$$,'%FORBIDDEN%','readonly cannot publish');
set local role anon;
select throws_ok($$select * from reception_reviews$$,'42501',null,'anonymous cannot read');
select throws_ok($$select publish_reception_review(null,null,null,1,null,null,null,null)$$,'42501',null,'anonymous cannot publish');
select * from finish();
rollback;
