begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('90000000-0000-4000-8000-000000000001','owner@review.test',now()),
 ('90000000-0000-4000-8000-000000000002','reader@review.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"90000000-0000-4000-8000-000000000001","role":"authenticated"}';
select set_config('test.a',create_tenant('Review A','review-a',gen_random_uuid())::text,true);
select set_config('test.b',create_tenant('Review B','review-b',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.a')::uuid,gen_random_uuid(),'Seller','seller@example.test','')::text,true);
select set_config('test.session',create_reception_session(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid)::text,true);
select set_config('test.agreement',publish_seller_agreement(current_setting('test.a')::uuid,gen_random_uuid(),null,'TEST terms','Fictional terms','en',false)::text,true);
select set_config('test.sources','[{"id":"90000000-0000-4000-8000-000000000010","kind":"observation","reference":"TEST","observation":"Blue jacket"},{"id":"90000000-0000-4000-8000-000000000011","kind":"price-evidence","reference":"TEST appraisal","observation":"Fictional 250 SEK appraisal"}]',true);
select save_reception_sources(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,0,current_setting('test.sources')::jsonb);
select set_config('test.suggestions','{"attributes":[{"slug":"description","definitionVersion":1,"value":"Blue jacket","sourceIds":["90000000-0000-4000-8000-000000000010"],"certainty":"observed"}],"price":{"currency":"SEK","amount":"250.00","rationale":"TEST appraisal","sourceIds":["90000000-0000-4000-8000-000000000011"]},"questions":[]}',true);
select set_config('test.review',gen_random_uuid()::text,true);
select set_config('test.expiry',(now()+interval '1 day')::text,true);
select publish_reception_review(current_setting('test.a')::uuid,current_setting('test.review')::uuid,current_setting('test.session')::uuid,1,null,current_setting('test.agreement')::uuid,current_setting('test.suggestions')::jsonb,current_setting('test.expiry')::timestamptz);
select set_config('test.link',gen_random_uuid()::text,true);
select lives_ok($$select set_reception_access(current_setting('test.a')::uuid,current_setting('test.link')::uuid,current_setting('test.review')::uuid,null,encode(sha256(convert_to(repeat('a',64),'UTF8')),'hex'))$$,'staff issues hashed access');
select lives_ok($$select set_reception_access(current_setting('test.a')::uuid,current_setting('test.link')::uuid,current_setting('test.review')::uuid,null,encode(sha256(convert_to(repeat('a',64),'UTF8')),'hex'))$$,'issuance retry');
select throws_like($$select set_reception_access(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.review')::uuid,null,repeat('b',64))$$,'%RECEPTION_ACCESS_CHANGED%','stale issuance rejected');
select throws_like($$select read_seller_review(repeat('a',64))$$,'%REVIEW_UNAVAILABLE%','owner cannot impersonate seller');
reset role;
insert into auth.users(id,email,email_confirmed_at) values('90000000-0000-4000-8000-000000000003','seller@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"90000000-0000-4000-8000-000000000003","role":"authenticated"}';
select is((select count(*) from tenant_members),0::bigint,'seller has no staff membership');
select is((select count(*) from reception_reviews),0::bigint,'seller cannot enumerate reviews');
select is((read_seller_review(repeat('a',64))->>'reviewId'),current_setting('test.review'),'capability reads exact review');
select is((read_seller_review(repeat('a',64))->'terms'->>'body'),'Fictional terms','seller sees pinned terms');
select ok(not(read_seller_review(repeat('a',64)) ? 'sources'),'internal source notes withheld');
select throws_like($$select read_seller_review(repeat('b',64))$$,'%REVIEW_UNAVAILABLE%','wrong token rejected');
select throws_like($$select read_seller_review(encode(sha256(convert_to(repeat('a',64),'UTF8')),'hex'))$$,'%REVIEW_UNAVAILABLE%','stored hash is not bearer token');
select throws_like($$select set_reception_access(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.review')::uuid,current_setting('test.link')::uuid,null)$$,'%FORBIDDEN%','seller cannot manage links');
select set_config('test.response',gen_random_uuid()::text,true);
select lives_ok($$select respond_to_reception_review(repeat('a',64),current_setting('test.response')::uuid,current_setting('test.review')::uuid,'approve')$$,'seller approves exact review');
select lives_ok($$select respond_to_reception_review(repeat('a',64),current_setting('test.response')::uuid,current_setting('test.review')::uuid,'approve')$$,'response replay safe');
select throws_like($$select respond_to_reception_review(repeat('a',64),current_setting('test.response')::uuid,current_setting('test.review')::uuid,'decline')$$,'%REQUEST_CONFLICT%','retry binds decision');
select throws_like($$select respond_to_reception_review(repeat('a',64),gen_random_uuid(),current_setting('test.review')::uuid,'decline')$$,'%REVIEW_ALREADY_ANSWERED%','cannot overwrite response');
select throws_like($$select respond_to_reception_review(repeat('a',64),gen_random_uuid(),gen_random_uuid(),'approve')$$,'%REVIEW_UNAVAILABLE%','exact displayed review required');
select is(read_seller_review(repeat('a',64))->'response'->>'decision','approve','read saved response');
reset role;
select is((select count(*) from reception_responses where tenant_id=current_setting('test.a')::uuid),1::bigint,'one response persisted');
select throws_like($$update reception_responses set decision='decline'$$,'%IMMUTABLE_RECEPTION%','response immutable');
update auth.users set email_confirmed_at=null where id='90000000-0000-4000-8000-000000000003';
set local role authenticated;
select throws_like($$select read_seller_review(repeat('a',64))$$,'%AUTH_REQUIRED%','unverified account denied');
reset role;
update auth.users set email_confirmed_at=now() where id='90000000-0000-4000-8000-000000000003';
set local role authenticated;
set local "request.jwt.claims"='{"sub":"90000000-0000-4000-8000-000000000001","role":"authenticated"}';
select set_reception_access(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.review')::uuid,current_setting('test.link')::uuid,null);
set local "request.jwt.claims"='{"sub":"90000000-0000-4000-8000-000000000003","role":"authenticated"}';
select throws_like($$select read_seller_review(repeat('a',64))$$,'%REVIEW_UNAVAILABLE%','revoked link unavailable');
set local role anon;
select throws_ok($$select read_seller_review(repeat('a',64))$$,'42501',null,'anonymous cannot read review');
select throws_ok($$select respond_to_reception_review(repeat('a',64),gen_random_uuid(),gen_random_uuid(),'approve')$$,'42501',null,'anonymous cannot respond');
reset role;
insert into auth.mfa_factors(id,user_id,factor_type,status,created_at,updated_at) values(gen_random_uuid(),'90000000-0000-4000-8000-000000000003','totp','verified',now(),now());
set local role authenticated;
select throws_like($$select read_seller_review(repeat('a',64))$$,'%AUTH_REQUIRED%','MFA required independently of app');
set local "request.jwt.claims"='{"sub":"90000000-0000-4000-8000-000000000001","role":"authenticated"}';
select set_config('test.current_access',(select id::text from reception_access_events where review_id=current_setting('test.review')::uuid order by version desc limit 1),true);
select set_reception_access(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.review')::uuid,current_setting('test.current_access')::uuid,encode(sha256(convert_to(repeat('b',64),'UTF8')),'hex'));
set local "request.jwt.claims"='{"sub":"90000000-0000-4000-8000-000000000003","role":"authenticated","aal":"aal2"}';
select lives_ok($$select read_seller_review(repeat('b',64))$$,'new link and MFA permit access');
select throws_like($$select read_seller_review(repeat('a',64))$$,'%REVIEW_UNAVAILABLE%','old link remains revoked');
set local "request.jwt.claims"='{"sub":"90000000-0000-4000-8000-000000000001","role":"authenticated"}';
select save_reception_sources(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,1,current_setting('test.sources')::jsonb);
set local "request.jwt.claims"='{"sub":"90000000-0000-4000-8000-000000000003","role":"authenticated","aal":"aal2"}';
select throws_like($$select read_seller_review(repeat('b',64))$$,'%REVIEW_UNAVAILABLE%','changed sources invalidate review');
select throws_like($$select respond_to_reception_review(repeat('b',64),gen_random_uuid(),current_setting('test.review')::uuid,'approve')$$,'%REVIEW_UNAVAILABLE%','cannot respond to stale review');
set local "request.jwt.claims"='{"sub":"90000000-0000-4000-8000-000000000001","role":"authenticated"}';
select set_config('test.review2',gen_random_uuid()::text,true);
select publish_reception_review(current_setting('test.a')::uuid,current_setting('test.review2')::uuid,current_setting('test.session')::uuid,2,current_setting('test.review')::uuid,current_setting('test.agreement')::uuid,current_setting('test.suggestions')::jsonb,current_setting('test.expiry')::timestamptz);
select set_config('test.access2',gen_random_uuid()::text,true);
select set_reception_access(current_setting('test.a')::uuid,current_setting('test.access2')::uuid,current_setting('test.review2')::uuid,null,encode(sha256(convert_to(repeat('c',64),'UTF8')),'hex'));
select throws_like($$select set_reception_access(current_setting('test.b')::uuid,gen_random_uuid(),current_setting('test.review2')::uuid,null,repeat('d',64))$$,'%REVIEW_UNAVAILABLE%','staff cannot bind link to different tenant review');
select publish_reception_review(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,2,current_setting('test.review2')::uuid,current_setting('test.agreement')::uuid,current_setting('test.suggestions')::jsonb,current_setting('test.expiry')::timestamptz);
set local "request.jwt.claims"='{"sub":"90000000-0000-4000-8000-000000000003","role":"authenticated","aal":"aal2"}';
select throws_like($$select respond_to_reception_review(repeat('c',64),gen_random_uuid(),current_setting('test.review2')::uuid,'approve')$$,'%REVIEW_UNAVAILABLE%','new review invalidates old mobile decision');
select throws_ok($$insert into reception_responses(id,tenant_id,review_id,access_id,decision,created_by) values(gen_random_uuid(),current_setting('test.a')::uuid,current_setting('test.review2')::uuid,current_setting('test.access2')::uuid,'approve',auth.uid())$$,'42501',null,'seller cannot bypass engine by inserting response');
reset role;
-- Historical fixture: an expired, latest review cannot be used even with a valid token.
select set_config('test.expired',gen_random_uuid()::text,true);
insert into reception_reviews(id,tenant_id,session_id,version,source_revision,previous_review_id,agreement_id,seller_email,suggestions,expires_at,created_by)
select current_setting('test.expired')::uuid,tenant_id,session_id,version+1,source_revision,id,agreement_id,seller_email,suggestions,now()-interval '1 second',created_by from reception_reviews_current where session_id=current_setting('test.session')::uuid;
insert into reception_access_events(id,tenant_id,review_id,version,token_hash,created_by) values(gen_random_uuid(),current_setting('test.a')::uuid,current_setting('test.expired')::uuid,1,encode(sha256(convert_to(repeat('d',64),'UTF8')),'hex'),'90000000-0000-4000-8000-000000000001');
set local role authenticated;
select throws_like($$select read_seller_review(repeat('d',64))$$,'%REVIEW_UNAVAILABLE%','expired review cannot be read');
select throws_like($$select respond_to_reception_review(repeat('d',64),gen_random_uuid(),current_setting('test.expired')::uuid,'approve')$$,'%REVIEW_UNAVAILABLE%','expired review cannot be approved');
select * from finish();
rollback;
