begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('80000000-0000-4000-8000-000000000001','owner@reception.test',now()),
 ('80000000-0000-4000-8000-000000000002','staff@reception.test',now()),
 ('80000000-0000-4000-8000-000000000003','reader@reception.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"80000000-0000-4000-8000-000000000001","role":"authenticated"}';
select set_config('test.a',create_tenant('Reception A','reception-a',gen_random_uuid())::text,true);
select set_config('test.b',create_tenant('Reception B','reception-b',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.a')::uuid,gen_random_uuid(),'Seller','','123')::text,true);
select set_config('test.session',gen_random_uuid()::text,true);
select set_config('test.request',gen_random_uuid()::text,true);
select create_reception_session(current_setting('test.a')::uuid,current_setting('test.session')::uuid,current_setting('test.seller')::uuid);
select set_config('test.photo',gen_random_uuid()::text,true);
select set_config('test.path',current_setting('test.a')||'/'||current_setting('test.session')||'/'||current_setting('test.photo')||'.png',true);
reset role;
select is((select public from storage.buckets where id='reception-photos'),false,'photo bucket private');
set local role authenticated;
select ok(reception_photo_access(current_setting('test.path'),true),'staff uploads own session');
select ok(not reception_photo_access(current_setting('test.b')||'/'||current_setting('test.session')||'/'||current_setting('test.photo')||'.png',true),'tenant/session mismatch denied');
select ok(not reception_photo_access('../../secret',false),'untrusted path denied');
select throws_ok($$insert into storage.objects(bucket_id,name) values('reception-photos',current_setting('test.b')||'/'||current_setting('test.session')||'/'||gen_random_uuid()::text||'.png')$$,'42501',null,'actual storage insert rejects mismatched tenant');
select set_config('test.sources',jsonb_build_array(jsonb_build_object('id',current_setting('test.photo'),'kind','photo','reference',current_setting('test.path'),'observation',''))::text,true);
select throws_like($$select save_reception_sources(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,0,current_setting('test.sources')::jsonb)$$,'%INVALID_INPUT%','missing object cannot become evidence');
insert into storage.objects(bucket_id,name,owner_id,metadata) values('reception-photos',current_setting('test.path'),auth.uid()::text,'{"mimetype":"image/png","size":68}');
select lives_ok($$select save_reception_sources(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,0,current_setting('test.sources')::jsonb)$$,'existing private image attaches to exact session');
select throws_like($$select save_reception_sources(current_setting('test.b')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,0,current_setting('test.sources')::jsonb)$$,'%RECEPTION_NOT_FOUND%','cannot attach to another store');
with changed as(update storage.objects set name=name||'x' where bucket_id='reception-photos' returning id) select is((select count(*) from changed),0::bigint,'photo cannot be overwritten or moved');
reset role;
insert into tenant_members(tenant_id,user_id,role) values(current_setting('test.a')::uuid,'80000000-0000-4000-8000-000000000003','readonly');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"80000000-0000-4000-8000-000000000003","role":"authenticated"}';
select ok(reception_photo_access(current_setting('test.path'),false),'readonly may read');
select ok(not reception_photo_access(current_setting('test.path'),true),'readonly cannot upload');
select throws_ok($$insert into storage.objects(bucket_id,name) values('reception-photos',current_setting('test.a')||'/'||current_setting('test.session')||'/'||gen_random_uuid()::text||'.png')$$,'42501',null,'readonly storage insert denied');
select is((select count(*) from storage.objects where name=current_setting('test.path')),1::bigint,'authorized image visible');
set local "request.jwt.claims"='{"sub":"80000000-0000-4000-8000-000000000002","role":"authenticated"}';
select is((select count(*) from storage.objects where name=current_setting('test.path')),0::bigint,'unrelated account cannot read');
set local role anon;
select ok(not reception_photo_access(current_setting('test.path'),false),'anonymous cannot read');
reset role;
insert into auth.mfa_factors(id,user_id,factor_type,status,created_at,updated_at) values(gen_random_uuid(),'80000000-0000-4000-8000-000000000001','totp','verified',now(),now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"80000000-0000-4000-8000-000000000001","role":"authenticated","aal":"aal1"}';
select is((select count(*) from storage.objects where name=current_setting('test.path')),0::bigint,'MFA blocks direct storage read');
select ok(not reception_photo_access(current_setting('test.path'),true),'MFA blocks upload');
select * from finish();
rollback;
