begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('b0000000-0000-4000-8000-000000000001','owner@queue.test',now()),
 ('b0000000-0000-4000-8000-000000000002','seller@queue.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"b0000000-0000-4000-8000-000000000001","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Queue','queue-test',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Seller','seller@queue.test','')::text,true);
select set_config('test.session',create_reception_session(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid)::text,true);
select is((select stage from reception_queue(current_setting('test.tenant')::uuid)),'preparing','empty session prepares');
select throws_ok($$select * from reception_queue(gen_random_uuid())$$,'42501',null,'another tenant denied');
select throws_like($$select * from reception_queue(current_setting('test.tenant')::uuid,'unknown')$$,'%INVALID_INPUT%','unknown filter rejected');
select throws_like($$select * from reception_queue(current_setting('test.tenant')::uuid,null,now(),null)$$,'%INVALID_INPUT%','partial cursor rejected');
select set_config('test.terms',publish_seller_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),null,'TEST','Fictional terms','en',false)::text,true);
select set_config('test.sources','[{"id":"b0000000-0000-4000-8000-000000000010","kind":"price-evidence","reference":"TEST","observation":"Fictional shirt 80SEK"}]',true);
select save_reception_sources(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,0,current_setting('test.sources')::jsonb);
select set_config('test.suggestions','{"metadata":{"description":{"value":"TEST shirt","sourceIds":["b0000000-0000-4000-8000-000000000010"],"certainty":"observed"}},"price":{"currency":"SEK","amount":"80.00","rationale":"TEST","sourceIds":["b0000000-0000-4000-8000-000000000010"]},"questions":[]}',true);
select set_config('test.review',gen_random_uuid()::text,true);
select publish_reception_review(current_setting('test.tenant')::uuid,current_setting('test.review')::uuid,current_setting('test.session')::uuid,1,null,current_setting('test.terms')::uuid,current_setting('test.suggestions')::jsonb,now()+interval '1 day');
select is((select stage from reception_queue(current_setting('test.tenant')::uuid)),'ready_to_share','published but not issued');
select set_config('test.access',gen_random_uuid()::text,true);
select set_reception_access(current_setting('test.tenant')::uuid,current_setting('test.access')::uuid,current_setting('test.review')::uuid,null,encode(sha256(convert_to(repeat('a',64),'UTF8')),'hex'));
select is((select stage from reception_queue(current_setting('test.tenant')::uuid)),'awaiting_seller','issued unanswered review');
select set_config('test.revoked',gen_random_uuid()::text,true);
select set_reception_access(current_setting('test.tenant')::uuid,current_setting('test.revoked')::uuid,current_setting('test.review')::uuid,current_setting('test.access')::uuid,null);
select is((select stage from reception_queue(current_setting('test.tenant')::uuid)),'link_revoked','unanswered revoked link needs staff action');
select set_config('test.access',gen_random_uuid()::text,true);
select set_reception_access(current_setting('test.tenant')::uuid,current_setting('test.access')::uuid,current_setting('test.review')::uuid,current_setting('test.revoked')::uuid,encode(sha256(convert_to(repeat('b',64),'UTF8')),'hex'));
set local "request.jwt.claims"='{"sub":"b0000000-0000-4000-8000-000000000002","role":"authenticated"}';
select throws_ok($$select * from reception_queue(current_setting('test.tenant')::uuid)$$,'42501',null,'seller is not staff');
select respond_to_reception_review(repeat('b',64),gen_random_uuid(),current_setting('test.review')::uuid,'approve');
set local "request.jwt.claims"='{"sub":"b0000000-0000-4000-8000-000000000001","role":"authenticated"}';
select is((select stage from reception_queue(current_setting('test.tenant')::uuid)),'approved','exact saved response');
select set_reception_access(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.review')::uuid,current_setting('test.access')::uuid,null);
select is((select stage from reception_queue(current_setting('test.tenant')::uuid)),'approved','revocation preserves historical response');
select is((select link_state from reception_queue(current_setting('test.tenant')::uuid)),'revoked','link availability is separate');
select save_reception_sources(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,1,current_setting('test.sources')::jsonb);
select is((select stage from reception_queue(current_setting('test.tenant')::uuid)),'needs_review','new sources invalidate current approval');
select is((select decision from reception_queue(current_setting('test.tenant')::uuid)),'approve','historical response retained');
-- Enough same-time rows to require a real cursor and filtering before limit.
select set_config('test.review2',gen_random_uuid()::text,true);
select publish_reception_review(current_setting('test.tenant')::uuid,current_setting('test.review2')::uuid,current_setting('test.session')::uuid,2,current_setting('test.review')::uuid,current_setting('test.terms')::uuid,current_setting('test.suggestions')::jsonb,now()+interval '1 day');
select is((select stage from reception_queue(current_setting('test.tenant')::uuid)),'ready_to_share','new review does not inherit approval');
select set_config('test.access2',gen_random_uuid()::text,true);
select set_reception_access(current_setting('test.tenant')::uuid,current_setting('test.access2')::uuid,current_setting('test.review2')::uuid,null,encode(sha256(convert_to(repeat('c',64),'UTF8')),'hex'));
set local "request.jwt.claims"='{"sub":"b0000000-0000-4000-8000-000000000002","role":"authenticated"}';
select respond_to_reception_review(repeat('c',64),gen_random_uuid(),current_setting('test.review2')::uuid,'decline');
set local "request.jwt.claims"='{"sub":"b0000000-0000-4000-8000-000000000001","role":"authenticated"}';
select is((select stage from reception_queue(current_setting('test.tenant')::uuid)),'declined','latest declined response wins');
-- Append an expired historical fixture; never modify an existing review.
reset role;
insert into public.reception_reviews(id,tenant_id,session_id,version,source_revision,previous_review_id,agreement_id,seller_email,suggestions,expires_at,created_by)
select gen_random_uuid(),tenant_id,session_id,3,source_revision,id,agreement_id,seller_email,suggestions,now()-interval '1 hour',created_by from public.reception_reviews where id=current_setting('test.review2')::uuid;
insert into public.tenant_members(tenant_id,user_id,role) values(current_setting('test.tenant')::uuid,'b0000000-0000-4000-8000-000000000002','readonly');
set local role authenticated;
select is((select stage from reception_queue(current_setting('test.tenant')::uuid)),'expired','unanswered expired review');
set local "request.jwt.claims"='{"sub":"b0000000-0000-4000-8000-000000000002","role":"authenticated"}';
select is((select count(*) from reception_queue(current_setting('test.tenant')::uuid)),1::bigint,'readonly staff may read');
reset role;
delete from public.tenant_members where tenant_id=current_setting('test.tenant')::uuid and user_id='b0000000-0000-4000-8000-000000000002';
set local role authenticated;
select throws_ok($$select * from reception_queue(current_setting('test.tenant')::uuid)$$,'42501',null,'removed membership loses queue access');
set local "request.jwt.claims"='{"sub":"b0000000-0000-4000-8000-000000000001","role":"authenticated"}';
select create_reception_session(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid) from generate_series(1,25);
select is((select count(*) from reception_queue(current_setting('test.tenant')::uuid)),21::bigint,'bounded page plus lookahead');
select is((select count(*) from reception_queue(current_setting('test.tenant')::uuid,'expired')),1::bigint,'filter is applied before limit');
select set_config('test.cursor_id',(select session_id::text from reception_queue(current_setting('test.tenant')::uuid) offset 19 limit 1),true);
select set_config('test.cursor_time',(select created_at::text from reception_queue(current_setting('test.tenant')::uuid) offset 19 limit 1),true);
select is((select count(*) from reception_queue(current_setting('test.tenant')::uuid,null,current_setting('test.cursor_time')::timestamptz,current_setting('test.cursor_id')::uuid)),6::bigint,'same-time cursor reaches remaining rows');
reset role;
insert into auth.mfa_factors(id,user_id,factor_type,status,created_at,updated_at) values(gen_random_uuid(),'b0000000-0000-4000-8000-000000000001','totp','verified',now(),now());
set local role authenticated;
select throws_ok($$select * from reception_queue(current_setting('test.tenant')::uuid)$$,'42501',null,'MFA enforced');
set local role anon;
select throws_ok($$select * from reception_queue(current_setting('test.tenant')::uuid)$$,'42501',null,'anonymous denied');
select * from finish();
rollback;
