begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values ('f0000000-0000-4000-8000-000000000021','vat-owner@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000021","role":"authenticated"}';
select set_config('test.tenant',create_tenant('VAT policy test','vat-policy-test',gen_random_uuid())::text,true);
select set_config('test.body',(current_store_policy(current_setting('test.tenant')::uuid)->'policy')::text,true);
select ok(not(current_setting('test.body')::jsonb ? 'vatModeConsignmentPrivate'),'defaults choose no VAT mode for the tenant');
select set_config('test.id',gen_random_uuid()::text,true);
select lives_ok($$select publish_store_policy(current_setting('test.tenant')::uuid,current_setting('test.id')::uuid,null,current_setting('test.body')::jsonb)$$,'policy without VAT keys still publishes');
select set_config('test.id2',gen_random_uuid()::text,true);
select lives_ok($$select publish_store_policy(current_setting('test.tenant')::uuid,current_setting('test.id2')::uuid,current_setting('test.id')::uuid,current_setting('test.body')::jsonb || '{"vatModeConsignmentPrivate":"consignment_margin","vatModeStoreOwned":"store_margin","vatRatePercent":25}')$$,'tenant selects its VAT modes');
select is(current_store_policy(current_setting('test.tenant')::uuid)->'policy'->>'vatModeConsignmentPrivate','consignment_margin','selected mode is read back');
select is((current_store_policy(current_setting('test.tenant')::uuid)->'policy'->>'vatRatePercent')::numeric,25::numeric,'rate is read back');
select throws_like($$select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.id2')::uuid,current_setting('test.body')::jsonb || '{"vatModeConsignmentPrivate":"store_margin"}')$$,'%INVALID_INPUT%','mode from the wrong group rejected');
select throws_like($$select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.id2')::uuid,current_setting('test.body')::jsonb || '{"vatModeStoreOwned":"agency"}')$$,'%INVALID_INPUT%','unknown mode rejected');
select throws_like($$select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.id2')::uuid,current_setting('test.body')::jsonb || '{"vatRatePercent":25.001}')$$,'%INVALID_INPUT%','rate beyond two decimals rejected');
select throws_like($$select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.id2')::uuid,current_setting('test.body')::jsonb || '{"vatRatePercent":100.01}')$$,'%INVALID_INPUT%','rate above 100 rejected');
select throws_like($$select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.id2')::uuid,current_setting('test.body')::jsonb || '{"vatRatePercent":"25"}')$$,'%INVALID_INPUT%','rate as text rejected');
select throws_like($$select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.id2')::uuid,current_setting('test.body')::jsonb || '{"vatModeConsignmentBusiness":"consignment_business"}')$$,'%INVALID_INPUT%','fixed business mode is not a key');
select * from finish();
rollback;
