begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000191','close-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000192','close-reader@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000191","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Close test','close-test',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Synthetic seller','seller@close.test','')::text,true);
select set_config('test.agreement',publish_seller_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),null,'Synthetic terms','Only a test','en',false)::text,true);
select record_agreement_evidence(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,current_setting('test.agreement')::uuid,'Signed paper');
select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),null,(current_store_policy(current_setting('test.tenant')::uuid)->'policy') || '{"vatModeConsignmentPrivate":"consignment_margin","vatModeStoreOwned":"store_margin"}');
select set_config('test.bag',receive_bag_with_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'',current_setting('test.agreement')::uuid)::text,true);
select set_config('test.d1',gen_random_uuid()::text,true);
select save_inspection_draft(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.bag')::uuid,current_setting('test.d1')::uuid,0,'Synthetic jacket','Jackets','Good');
select set_config('test.i1',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.i1')::uuid,'inspection_draft',current_setting('test.d1')::uuid,1,25000);
select set_config('test.purchase',register_purchase(current_setting('test.tenant')::uuid,gen_random_uuid(),'',15000,'Receipt 1',true)::text,true);
select set_config('test.i2',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.i2')::uuid,'purchase',current_setting('test.purchase')::uuid,null,25000);
-- Two sales on 2026-09-05 local time (one right after midnight), one the day before.
select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','D-0','2026-09-04T20:00:00+02:00','SEK',jsonb_build_array(jsonb_build_object('itemId',current_setting('test.i2'),'priceOre',25000)));
select set_config('test.ret',gen_random_uuid()::text,true);
select record_return(current_setting('test.tenant')::uuid,current_setting('test.ret')::uuid,(select id from sale_lines where item_id=current_setting('test.i2')::uuid),25000,'Defect','2026-09-05T09:00:00+02:00');
select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','D-1','2026-09-05T00:30:00+02:00','SEK',jsonb_build_array(jsonb_build_object('itemId',current_setting('test.i1'),'priceOre',25000)));
select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','D-2','2026-09-05T15:00:00+02:00','SEK',jsonb_build_array(jsonb_build_object('itemId',current_setting('test.i2'),'priceOre',30000)));
select set_config('test.c1',gen_random_uuid()::text,true);
select throws_like($$select generate_day_close(current_setting('test.tenant')::uuid,current_setting('test.c1')::uuid,'2099-01-01')$$,'%INVALID_INPUT%','future day rejected');
select is(generate_day_close(current_setting('test.tenant')::uuid,current_setting('test.c1')::uuid,'2026-09-05'),current_setting('test.c1')::uuid,'day closed');
select set_config('test.h',(select row_to_json(d)::text from day_closes d where id=current_setting('test.c1')::uuid),true);
select is((current_setting('test.h')::jsonb->>'version')::int,1,'first version');
select is((current_setting('test.h')::jsonb->>'sales_count')::int,2,'two sales on the local day, the evening sale belongs to the day before');
select is((current_setting('test.h')::jsonb->>'gross_ore')::bigint,55000::bigint,'gross 550 SEK');
select is((current_setting('test.h')::jsonb->>'commission_ore')::bigint,15000::bigint,'commission on the consignment line');
select is((current_setting('test.h')::jsonb->>'seller_credit_ore')::bigint,10000::bigint,'seller credit');
select is((current_setting('test.h')::jsonb->>'vat_ore')::bigint,6000::bigint,'VAT: 3000 on the margin line plus 3000 on the store margin line (30000-15000)');
select is((current_setting('test.h')::jsonb->>'returns_count')::int,1,'one return that day');
select is((current_setting('test.h')::jsonb->>'refunds_ore')::bigint,25000::bigint,'refund total');
select is((current_setting('test.h')::jsonb->'per_mode'->'consignment_margin'->>'vatOre')::bigint,3000::bigint,'per-mode VAT for consignment margin');
select is((current_setting('test.h')::jsonb->'per_mode'->'store_margin'->>'netOre')::bigint,27000::bigint,'per-mode net for store margin');
select is(generate_day_close(current_setting('test.tenant')::uuid,gen_random_uuid(),'2026-09-05'),current_setting('test.c1')::uuid,'an unchanged day returns the existing version');
select is((select count(*) from day_closes),1::bigint,'no duplicate version');
-- A late sale on that day makes a new version; the old one stays.
select set_config('test.d2',gen_random_uuid()::text,true);
select save_inspection_draft(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.bag')::uuid,current_setting('test.d2')::uuid,0,'Synthetic scarf','Accessories','Good');
select set_config('test.i3',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.i3')::uuid,'inspection_draft',current_setting('test.d2')::uuid,1,10000);
select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','D-3','2026-09-05T23:59:00+02:00','SEK',jsonb_build_array(jsonb_build_object('itemId',current_setting('test.i3'),'priceOre',10000)));
select set_config('test.c2',gen_random_uuid()::text,true);
select is(generate_day_close(current_setting('test.tenant')::uuid,current_setting('test.c2')::uuid,'2026-09-05'),current_setting('test.c2')::uuid,'changed day gets a new close');
select is((select version||'|'||sales_count||'|'||gross_ore from day_closes where id=current_setting('test.c2')::uuid),'2|3|65000','version two with three sales');
select is((select gross_ore from day_closes where id=current_setting('test.c1')::uuid),55000::bigint,'version one untouched');
select set_config('test.c3',generate_day_close(current_setting('test.tenant')::uuid,gen_random_uuid(),'2026-09-04')::text,true);
select is((select sales_count from day_closes where id=current_setting('test.c3')::uuid),1,'the evening sale closes with its own day');
select set_config('test.c4',generate_day_close(current_setting('test.tenant')::uuid,gen_random_uuid(),'2026-09-06')::text,true);
select is((select sales_count||'|'||gross_ore from day_closes where id=current_setting('test.c4')::uuid),'0|0','an empty day closes at zero');
select throws_ok($$update day_closes set gross_ore=0$$,'42501',null,'direct update denied');
reset role;
select throws_like($$update day_closes set gross_ore=0 where id=current_setting('test.c1')::uuid$$,'%IMMUTABLE_DAY_CLOSE%','privileged update immutable');
insert into tenant_members(tenant_id,user_id,role) values (current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000000192','readonly');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000192","role":"authenticated"}';
select is((select count(*) from day_closes),4::bigint,'readonly reads day closes');
select throws_ok($$select generate_day_close(current_setting('test.tenant')::uuid,gen_random_uuid(),'2026-09-05')$$,'42501',null,'readonly cannot generate');
select * from finish();
rollback;
