begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000221','print-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000222','print-agent@example.test',now()),
 ('f0000000-0000-4000-8000-000000000223','print-reader@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000221","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Print test','print-test',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Synthetic seller','seller@print.test','')::text,true);
select set_config('test.bag',receive_bag_with_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'',null)::text,true);
select set_config('test.printer',gen_random_uuid()::text,true);
select throws_like($$select register_printer(current_setting('test.tenant')::uuid,current_setting('test.printer')::uuid,'Counter','tcp','not a host!','ZD421',203)$$,'%INVALID_INPUT%','tcp address validated');
select throws_like($$select register_printer(current_setting('test.tenant')::uuid,current_setting('test.printer')::uuid,'Counter','tcp','192.168.1.50:9100','ZD421',150)$$,'%INVALID_INPUT%','dpi limited to known values');
select is(register_printer(current_setting('test.tenant')::uuid,current_setting('test.printer')::uuid,'Counter','tcp','192.168.1.50:9100','ZD421',203),current_setting('test.printer')::uuid,'printer registered');
select is(register_printer(current_setting('test.tenant')::uuid,current_setting('test.printer')::uuid,'Counter 2','tcp','192.168.1.51:9100','ZD421',203),current_setting('test.printer')::uuid,'re-registering updates the description');
select is((select name||'|'||address from printers where id=current_setting('test.printer')::uuid),'Counter 2|192.168.1.51:9100','description updated');
select set_config('test.job',gen_random_uuid()::text,true);
select throws_like($$select queue_print_job(current_setting('test.tenant')::uuid,current_setting('test.job')::uuid,gen_random_uuid(),'bag','zpl-v1','bag_receipt',current_setting('test.bag')::uuid,'^XA^XZ')$$,'%PRINTER_NOT_FOUND%','unknown printer');
select throws_like($$select queue_print_job(current_setting('test.tenant')::uuid,current_setting('test.job')::uuid,current_setting('test.printer')::uuid,'bag','zpl-v1','bag_receipt',gen_random_uuid(),'^XA^XZ')$$,'%REFERENCE_NOT_FOUND%','unknown reference');
select throws_like($$select queue_print_job(current_setting('test.tenant')::uuid,current_setting('test.job')::uuid,current_setting('test.printer')::uuid,'poster','zpl-v1','bag_receipt',current_setting('test.bag')::uuid,'^XA^XZ')$$,'%INVALID_INPUT%','unknown label kind');
select throws_like($$select queue_print_job(current_setting('test.tenant')::uuid,current_setting('test.job')::uuid,current_setting('test.printer')::uuid,'bag','zpl-v1','bag_receipt',current_setting('test.bag')::uuid,'^XA^XZ',50)$$,'%INVALID_INPUT%','copies bounded');
select is(queue_print_job(current_setting('test.tenant')::uuid,current_setting('test.job')::uuid,current_setting('test.printer')::uuid,'bag','zpl-v1','bag_receipt',current_setting('test.bag')::uuid,'^XA^FDK-1^FS^XZ',2),current_setting('test.job')::uuid,'job queued');
select is(queue_print_job(current_setting('test.tenant')::uuid,current_setting('test.job')::uuid,current_setting('test.printer')::uuid,'bag','zpl-v1','bag_receipt',current_setting('test.bag')::uuid,'^XA^FDK-1^FS^XZ',2),current_setting('test.job')::uuid,'replay');
select throws_like($$select queue_print_job(current_setting('test.tenant')::uuid,current_setting('test.job')::uuid,current_setting('test.printer')::uuid,'bag','zpl-v1','bag_receipt',current_setting('test.bag')::uuid,'^XA^FDK-2^FS^XZ',2)$$,'%REQUEST_CONFLICT%','changed replay rejected');
select throws_like($$select complete_print_job(current_setting('test.tenant')::uuid,current_setting('test.job')::uuid,true)$$,'%PRINT_JOB_NOT_CLAIMED%','cannot complete before a claim');
-- The agent is a staff member of the store.
reset role;
insert into tenant_members(tenant_id,user_id,role) values (current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000000222','staff'),(current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000000223','readonly');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000222","role":"authenticated"}';
select set_config('test.claim',claim_print_job(current_setting('test.tenant')::uuid,current_setting('test.printer')::uuid)::text,true);
select is(current_setting('test.claim')::jsonb->>'jobId',current_setting('test.job'),'agent claims the queued job');
select is((current_setting('test.claim')::jsonb->>'copies')::int,2,'claim carries the copies');
select is(current_setting('test.claim')::jsonb->>'payload','^XA^FDK-1^FS^XZ','claim carries the payload');
select is(claim_print_job(current_setting('test.tenant')::uuid,current_setting('test.printer')::uuid),null,'nothing else to claim');
select is((select status||'|'||claimed_by from print_jobs where id=current_setting('test.job')::uuid),'claimed|f0000000-0000-4000-8000-000000000222','claimed by the agent');
select is(complete_print_job(current_setting('test.tenant')::uuid,current_setting('test.job')::uuid,true),current_setting('test.job')::uuid,'printed');
select is(complete_print_job(current_setting('test.tenant')::uuid,current_setting('test.job')::uuid,true),current_setting('test.job')::uuid,'same outcome replays');
select throws_like($$select complete_print_job(current_setting('test.tenant')::uuid,current_setting('test.job')::uuid,false,'jam')$$,'%PRINT_JOB_DECIDED%','a second outcome is refused');
select is((select status from print_jobs where id=current_setting('test.job')::uuid),'printed','status printed');
-- A stale claim can be claimed again; a failure records the error; a queued job can be cancelled.
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000221","role":"authenticated"}';
select set_config('test.job2',gen_random_uuid()::text,true);
select queue_print_job(current_setting('test.tenant')::uuid,current_setting('test.job2')::uuid,current_setting('test.printer')::uuid,'garment','zpl-v1','bag_receipt',current_setting('test.bag')::uuid,'^XA^FDG-1^FS^XZ');
select set_config('test.job3',gen_random_uuid()::text,true);
select queue_print_job(current_setting('test.tenant')::uuid,current_setting('test.job3')::uuid,current_setting('test.printer')::uuid,'item','zpl-v1','bag_receipt',current_setting('test.bag')::uuid,'^XA^FDI^FS^XZ');
select is(cancel_print_job(current_setting('test.tenant')::uuid,current_setting('test.job3')::uuid),current_setting('test.job3')::uuid,'queued job cancelled');
select throws_like($$select cancel_print_job(current_setting('test.tenant')::uuid,current_setting('test.job')::uuid)$$,'%PRINT_JOB_DECIDED%','a printed job cannot be cancelled');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000222","role":"authenticated"}';
select is(claim_print_job(current_setting('test.tenant')::uuid,current_setting('test.printer')::uuid)->>'jobId',current_setting('test.job2'),'next queued job claimed, cancelled one skipped');
reset role;
alter table public.print_jobs disable trigger print_jobs_guard;
update public.print_jobs set claimed_at=now()-interval '11 minutes' where id=current_setting('test.job2')::uuid;
alter table public.print_jobs enable trigger print_jobs_guard;
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000222","role":"authenticated"}';
select is(claim_print_job(current_setting('test.tenant')::uuid,current_setting('test.printer')::uuid)->>'jobId',current_setting('test.job2'),'a stale claim is handed out again');
select is(complete_print_job(current_setting('test.tenant')::uuid,current_setting('test.job2')::uuid,false,'Paper out'),current_setting('test.job2')::uuid,'failure recorded');
select is((select status||'|'||error from print_jobs where id=current_setting('test.job2')::uuid),'failed|Paper out','error stored');
select throws_ok($$update print_jobs set status='printed'$$,'42501',null,'direct update denied');
reset role;
select throws_like($$update print_jobs set status='printed' where id=current_setting('test.job2')::uuid$$,'%IMMUTABLE_PRINT_JOB%','privileged status change outside the engine refused');
select throws_like($$delete from printers where id=current_setting('test.printer')::uuid$$,'%IMMUTABLE_PRINTER%','printers are not deleted');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000223","role":"authenticated"}';
select is((select count(*) from print_jobs),3::bigint,'readonly reads jobs');
select throws_ok($$select claim_print_job(current_setting('test.tenant')::uuid,current_setting('test.printer')::uuid)$$,'42501',null,'readonly cannot claim');
select throws_ok($$select register_printer(current_setting('test.tenant')::uuid,gen_random_uuid(),'X','usb','','',203)$$,'42501',null,'readonly cannot register');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000222","role":"authenticated"}';
select throws_ok($$select register_printer(current_setting('test.tenant')::uuid,gen_random_uuid(),'X','usb','','',203)$$,'42501',null,'staff cannot register printers');
select * from finish();
rollback;
