begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
select is(komisio_private.operation_risk('sendMessage'),'low','a template-bound message is low risk');
insert into auth.users(id,email,email_confirmed_at) values ('f0000000-0000-4000-8000-000000000281','message-owner@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000281","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Message test','message-test',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Synthetic seller','seller@message.test','')::text,true);
select set_config('test.phone',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Phone seller','','0700000000')::text,true);
select throws_like($$select propose_operation(current_setting('test.tenant')::uuid,gen_random_uuid(),'sendMessage',jsonb_build_object('sellerId',current_setting('test.seller'),'locale','de','freeText','Hallo'),'agent',now()+interval '1 day')$$,'%INVALID_INPUT%','locale limited to sv and en');
select throws_like($$select propose_operation(current_setting('test.tenant')::uuid,gen_random_uuid(),'sendMessage',jsonb_build_object('sellerId',current_setting('test.seller'),'locale','sv','freeText','','subject','Hej'),'agent',now()+interval '1 day')$$,'%INVALID_INPUT%','no subject or body in the payload: the template is code');
select throws_like($$select propose_operation(current_setting('test.tenant')::uuid,gen_random_uuid(),'sendMessage',jsonb_build_object('sellerId',current_setting('test.phone'),'locale','sv','freeText','Hej'),'agent',now()+interval '1 day')$$,'%SELLER_EMAIL_MISSING%','a seller without e-mail cannot be messaged');
select throws_like($$select propose_operation(current_setting('test.tenant')::uuid,gen_random_uuid(),'sendMessage',jsonb_build_object('sellerId',gen_random_uuid(),'locale','sv','freeText','Hej'),'agent',now()+interval '1 day')$$,'%SELLER_NOT_FOUND%','unknown seller refused');
select set_config('test.op',gen_random_uuid()::text,true);
select is(propose_operation(current_setting('test.tenant')::uuid,current_setting('test.op')::uuid,'sendMessage',jsonb_build_object('sellerId',current_setting('test.seller'),'locale','sv','freeText','Vi har öppet extra på lördag.'),'message-agent',now()+interval '1 day'),current_setting('test.op')::uuid,'message proposed');
select set_config('test.dec',gen_random_uuid()::text,true);
select lives_ok($$select decide_operation(current_setting('test.tenant')::uuid,current_setting('test.dec')::uuid,current_setting('test.op')::uuid,'approved','Fine')$$,'low risk: the proposer may approve');
select is((select outcome||'|'||result_id from operation_decisions where id=current_setting('test.dec')::uuid),'executed|'||current_setting('test.op'),'approval recorded with the operation id as the message id');
select is((select count(*) from seller_communications where tenant_id=current_setting('test.tenant')::uuid),0::bigint,'nothing queued by SQL: the application sends after approval');
select is((select count(*) from operation_queue_filtered_page(current_setting('test.tenant')::uuid,'executed',null,null,'sendMessage')),1::bigint,'queue filters the message kind');
select * from finish();
rollback;
