begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000481','portal-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000482','portal-seller@example.test',now()),
 ('f0000000-0000-4000-8000-000000000483','portal-other@example.test',now()),
 ('f0000000-0000-4000-8000-000000000484','portal-unverified@example.test',null);
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000481","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Portal test','portal-test',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Synthetic seller','portal-seller@example.test','')::text,true);
select set_config('test.other',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Other seller','portal-other@example.test','')::text,true);
select adjust_seller_ledger(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,20000,'PRIVATE staff note');
select set_config('test.balance',seller_balance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)::text,true);
select set_config('test.statement',issue_statement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'2000-01-01',clock_timestamp())::text,true);
select set_config('test.otherstatement',issue_statement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.other')::uuid,'2000-01-01',clock_timestamp())::text,true);
select queue_seller_communication(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'message','message','1','en','Hello','Synthetic message','none',null);
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000482","role":"authenticated"}';
select is(jsonb_array_length(my_seller_accounts()),1,'only own account discovered');
select is((my_seller_economy(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)->'balance'),current_setting('test.balance')::jsonb,'seller and staff share balance calculation');
select is((my_seller_economy(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)->'ledger'->0->>'reason'),null,'staff reason omitted');
select is(jsonb_array_length(my_seller_economy(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)->'messages'),1,'own message log');
select is(jsonb_array_length(my_seller_statement(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.statement')::uuid)->'lines'),1,'own frozen statement lines');
select throws_like($$select my_seller_statement(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.otherstatement')::uuid)$$,'%STATEMENT_NOT_FOUND%','other statement denied');
select throws_ok($$select my_seller_economy(current_setting('test.tenant')::uuid,current_setting('test.other')::uuid)$$,'42501',null,'other seller denied');
select throws_ok($$select my_seller_economy(gen_random_uuid(),current_setting('test.seller')::uuid)$$,'42501',null,'other tenant denied');
select is((select count(*) from seller_ledger_entries),0::bigint,'raw ledger remains staff only');
select is((select count(*) from settlement_statements),0::bigint,'raw statements remain staff only');
select set_config('test.payout',gen_random_uuid()::text,true);
select throws_like($$select request_my_payout(current_setting('test.tenant')::uuid,current_setting('test.payout')::uuid,current_setting('test.seller')::uuid,9999)$$,'%PAYOUT_BELOW_THRESHOLD%','threshold enforced');
select throws_like($$select request_my_payout(current_setting('test.tenant')::uuid,current_setting('test.payout')::uuid,current_setting('test.seller')::uuid,20001)$$,'%PAYOUT_EXCEEDS_BALANCE%','available enforced');
select is(request_my_payout(current_setting('test.tenant')::uuid,current_setting('test.payout')::uuid,current_setting('test.seller')::uuid,10000),current_setting('test.payout')::uuid,'own request');
select is(request_my_payout(current_setting('test.tenant')::uuid,current_setting('test.payout')::uuid,current_setting('test.seller')::uuid,10000),current_setting('test.payout')::uuid,'request replay');
select throws_like($$select request_my_payout(current_setting('test.tenant')::uuid,current_setting('test.payout')::uuid,current_setting('test.seller')::uuid,11000)$$,'%REQUEST_CONFLICT%','changed request denied');
select throws_ok($$select request_my_payout(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.other')::uuid,10000)$$,'42501',null,'other seller request denied');
select throws_ok($$select approve_payout(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.payout')::uuid)$$,'42501',null,'seller cannot approve');
select throws_ok($$select mark_payout_paid(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.payout')::uuid,'test')$$,'42501',null,'seller cannot pay');
select set_config('test.pref',gen_random_uuid()::text,true);
select set_my_seller_notifications(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.pref')::uuid,false);
select is((my_seller_economy(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)->>'automaticEmails')::boolean,false,'seller opts out');
select is(set_my_seller_notifications(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.pref')::uuid,false),current_setting('test.pref')::uuid,'preference replay');
select throws_ok($$select set_my_seller_notifications(current_setting('test.tenant')::uuid,current_setting('test.other')::uuid,gen_random_uuid(),false)$$,'42501',null,'other preference denied');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000481","role":"authenticated"}';
select is((select request_source from payouts where id=current_setting('test.payout')::uuid),'seller','staff sees request source');
select approve_payout(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.payout')::uuid);
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000482","role":"authenticated"}';
select is((my_seller_economy(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)->'balance'->>'reservedOre')::bigint,10000::bigint,'reservation visible');
select throws_like($$select request_my_payout(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,10001)$$,'%PAYOUT_EXCEEDS_BALANCE%','reservation reduces available');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000484","role":"authenticated"}';
select throws_ok($$select my_seller_accounts()$$,'42501',null,'unverified denied');
set local role anon;
select throws_ok($$select my_seller_accounts()$$,'42501',null,'anonymous denied');
reset role;
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000481","role":"authenticated"}';
select is(allow_automatic_seller_email(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,gen_random_uuid()),false,'opt out prevents automatic transport');
select is((select detail->>'why' from access_events where tenant_id=current_setting('test.tenant')::uuid and action='seller_email.skipped' limit 1),'seller_opt_out','skip reason is persisted');
select is(allow_automatic_seller_email(current_setting('test.tenant')::uuid,current_setting('test.other')::uuid,gen_random_uuid()),true,'default permits notification subject to store policy');
reset role;
insert into auth.mfa_factors(id,user_id,factor_type,status,created_at,updated_at) values(gen_random_uuid(),'f0000000-0000-4000-8000-000000000482','totp','verified',now(),now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000482","role":"authenticated","aal":"aal1"}';
select throws_ok($$select my_seller_accounts()$$,'42501',null,'seller MFA required at SQL boundary');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000482","role":"authenticated","aal":"aal2"}';
select is(jsonb_array_length(my_seller_accounts()),1,'MFA verified seller can read');
select throws_ok($$select allow_automatic_seller_email(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,gen_random_uuid())$$,'42501',null,'seller cannot invoke staff dispatch gate');
reset role;
insert into sellers(id,tenant_id,name,email,created_by) values(gen_random_uuid(),current_setting('test.tenant')::uuid,'Duplicate','portal-seller@example.test','f0000000-0000-4000-8000-000000000481');
set local role authenticated;
select is(jsonb_array_length(my_seller_accounts()),0,'ambiguous email is not auto-linked');
select throws_ok($$select my_seller_economy(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)$$,'42501',null,'ambiguous direct lookup also denied');
reset role;
select * from finish();
rollback;
