begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000351','export-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000352','export-staff@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000351","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Export test','seller-export-test',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Exported Seller','exported@example.test','070')::text,true);
select set_config('test.other',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Other Seller','other@example.test','')::text,true);
select publish_seller_terms(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,null,'inclusive',55,'Private note');
select set_config('test.agreement',publish_seller_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),null,'Synthetic terms','Only a test','en',false)::text,true);
select record_agreement_evidence(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,current_setting('test.agreement')::uuid,'Signed paper');
select record_agreement_evidence(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.other')::uuid,current_setting('test.agreement')::uuid,'Signed paper');
select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),null,(current_store_policy(current_setting('test.tenant')::uuid)->'policy') || '{"vatModeConsignmentPrivate":"consignment_margin","vatModeStoreOwned":"store_full"}');
select set_config('test.bag',receive_bag_with_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'',current_setting('test.agreement')::uuid)::text,true);
select set_config('test.draft',gen_random_uuid()::text,true);
select save_inspection_draft(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.bag')::uuid,current_setting('test.draft')::uuid,0,'Jacket','Jackets','Good');
select set_config('test.item',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.item')::uuid,'inspection_draft',current_setting('test.draft')::uuid,1,50000);
select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','K-1','2026-09-10T10:00:00Z','SEK',jsonb_build_array(jsonb_build_object('itemId',current_setting('test.item'),'priceOre',50000)));
select set_config('test.payout',gen_random_uuid()::text,true);
select request_payout(current_setting('test.tenant')::uuid,current_setting('test.payout')::uuid,current_setting('test.seller')::uuid,10000);
select issue_statement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'2026-09-01T00:00:00Z','2026-09-12T00:00:00Z',null);
select queue_seller_communication(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'message','message','v1','sv','Hej','Text','none',null);
-- The other seller has a bag too; it must not appear.
select receive_bag_with_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.other')::uuid,'other bag',current_setting('test.agreement')::uuid);
select set_config('test.export',seller_data_export(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)::text,true);
select is(current_setting('test.export')::jsonb->'seller'->>'name','Exported Seller','the seller record is included');
select is(current_setting('test.export')::jsonb->'seller'->>'tenant_id',null,'tenant id stripped from rows');
select is(jsonb_array_length(current_setting('test.export')::jsonb->'terms'),1,'terms versions');
select is(current_setting('test.export')::jsonb->'terms'->0->>'notes','Private note','terms notes are the seller''s data and included');
select is(jsonb_array_length(current_setting('test.export')::jsonb->'agreementEvidence'),1,'only this seller''s evidence');
select is(jsonb_array_length(current_setting('test.export')::jsonb->'bags'),1,'only this seller''s bag');
select is(jsonb_array_length(current_setting('test.export')::jsonb->'inspectionDrafts'),1,'draft revisions through the bag');
select is(jsonb_array_length(current_setting('test.export')::jsonb->'items'),1,'items');
select cmp_ok(jsonb_array_length(current_setting('test.export')::jsonb->'itemEvents'),'>=',2,'item events through the items');
select cmp_ok(jsonb_array_length(current_setting('test.export')::jsonb->'itemPrices'),'>=',1,'item prices through the items');
select is(jsonb_array_length(current_setting('test.export')::jsonb->'saleLines'),1,'sale lines through the items');
select is(current_setting('test.export')::jsonb->'saleLines'->0->'sale'->>'external_id','K-1','each line carries its sale header');
select cmp_ok(jsonb_array_length(current_setting('test.export')::jsonb->'ledger'),'>=',1,'ledger entries');
select is(jsonb_array_length(current_setting('test.export')::jsonb->'payouts'),1,'payouts');
select is(jsonb_array_length(current_setting('test.export')::jsonb->'payoutEvents'),1,'payout events');
select is(jsonb_array_length(current_setting('test.export')::jsonb->'statements'),1,'statements');
select cmp_ok(jsonb_array_length(current_setting('test.export')::jsonb->'statementLines'),'>=',1,'statement lines');
select is(jsonb_array_length(current_setting('test.export')::jsonb->'communications'),1,'communications');
select is(jsonb_array_length(current_setting('test.export')::jsonb->'returns'),0,'no returns');
select is(position('Other Seller' in current_setting('test.export')),0,'nothing about the other seller leaks in');
select is(position('other bag' in current_setting('test.export')),0,'nor the other seller''s bag');
select is((select count(*) from access_events where tenant_id=current_setting('test.tenant')::uuid and action='seller.exported' and target_id=current_setting('test.seller')::uuid),1::bigint,'the export is logged as an access event');
select throws_like($$select seller_data_export(current_setting('test.tenant')::uuid,gen_random_uuid())$$,'%SELLER_NOT_FOUND%','unknown seller refused');
select throws_ok($$select seller_data_export(gen_random_uuid(),current_setting('test.seller')::uuid)$$,'42501',null,'another tenant denied');
reset role;
insert into tenant_members(tenant_id,user_id,role) values (current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000000352','staff');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000352","role":"authenticated"}';
select throws_ok($$select seller_data_export(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)$$,'42501',null,'staff cannot export');
set local role anon;
select throws_ok($$select seller_data_export(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)$$,'42501',null,'anon cannot execute the export');
select * from finish();
rollback;
