begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values ('f0000000-0000-4000-8000-000000000391','evidence-owner@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000391","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Evidence test','evidence-test',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Seller','s@evidence.test','')::text,true);
select set_config('test.agreement',publish_seller_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),null,'Synthetic terms','Only a test','en',false)::text,true);
select record_agreement_evidence(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,current_setting('test.agreement')::uuid,'Signed paper');
select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),null,(current_store_policy(current_setting('test.tenant')::uuid)->'policy') || '{"vatModeConsignmentPrivate":"consignment_margin","vatModeStoreOwned":"store_full"}');
select set_config('test.bag',receive_bag_with_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'',current_setting('test.agreement')::uuid)::text,true);
-- Three jackets and one coat accepted; two jackets sold, one returned, the coat sold.
create temp table fx(id uuid, draft uuid, title text, category text, price bigint);
insert into fx values (gen_random_uuid(),gen_random_uuid(),'Blue wool jacket','Jackets',50000),(gen_random_uuid(),gen_random_uuid(),'Red jacket','Jackets',30000),(gen_random_uuid(),gen_random_uuid(),'Green jacket','Jackets',40000),(gen_random_uuid(),gen_random_uuid(),'Long coat','Coats',80000);
select save_inspection_draft(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.bag')::uuid,draft,0,title,category,'Good') from fx;
select accept_item(current_setting('test.tenant')::uuid,id,'inspection_draft',draft,1,price) from fx;
select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','E-1','2026-09-10T10:00:00Z','SEK',jsonb_build_array(jsonb_build_object('itemId',(select id from fx where title='Blue wool jacket'),'priceOre',45000)));
select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','E-2','2026-09-11T10:00:00Z','SEK',jsonb_build_array(jsonb_build_object('itemId',(select id from fx where title='Red jacket'),'priceOre',30000)));
select set_config('test.s3',record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','E-3','2026-09-12T10:00:00Z','SEK',jsonb_build_array(jsonb_build_object('itemId',(select id from fx where title='Green jacket'),'priceOre',40000)))::text,true);
select record_return(current_setting('test.tenant')::uuid,gen_random_uuid(),(select id from sale_lines where sale_id=current_setting('test.s3')::uuid),40000,'Did not fit','2026-09-13T10:00:00Z');
select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','E-4','2026-09-12T12:00:00Z','SEK',jsonb_build_array(jsonb_build_object('itemId',(select id from fx where title='Long coat'),'priceOre',80000)));
select set_config('test.ev',price_evidence(current_setting('test.tenant')::uuid,'jackets',null,365)::text,true);
select is((current_setting('test.ev')::jsonb->'summary'->>'count')::int,2,'two sold jackets, the returned one excluded');
select is(current_setting('test.ev')::jsonb->>'currency','SEK','the store currency is named');
select is((current_setting('test.ev')::jsonb->'summary'->>'medianSoldOre')::bigint,37500::bigint,'median of the sold prices');
select is((current_setting('test.ev')::jsonb->'summary'->>'minSoldOre')::bigint,30000::bigint,'lowest sold');
select is((current_setting('test.ev')::jsonb->'summary'->>'maxSoldOre')::bigint,45000::bigint,'highest sold');
select is(current_setting('test.ev')::jsonb->'matches'->0->>'title','Red jacket','newest sale first');
select is((current_setting('test.ev')::jsonb->'matches'->1->>'acceptedPriceOre')::bigint,50000::bigint,'the accepted price next to the sold price');
select is((current_setting('test.ev')::jsonb->'matches'->1->>'soldPriceOre')::bigint,45000::bigint,'sold below the accepted price');
select is((price_evidence(current_setting('test.tenant')::uuid,'Jackets','wool',365)->'summary'->>'count')::int,1,'free text narrows within the category');
select is((price_evidence(current_setting('test.tenant')::uuid,null,'jacket',365)->'summary'->>'count')::int,2,'free text alone');
select is((price_evidence(current_setting('test.tenant')::uuid,null,null,365)->'summary'->>'count')::int,3,'no filter: every sold item');
select is((price_evidence(current_setting('test.tenant')::uuid,'Coats',null,1)->'summary'->>'count')::int,0,'the window applies');
select is(price_evidence(current_setting('test.tenant')::uuid,'Hats',null,365)->'summary'->>'medianSoldOre',null,'no matches, no median');
select throws_like($$select price_evidence(current_setting('test.tenant')::uuid,'Jackets',null,0)$$,'%INVALID_INPUT%','window at least one day');
select throws_like($$select price_evidence(current_setting('test.tenant')::uuid,repeat('x',121),null,365)$$,'%INVALID_INPUT%','category bounded');
select throws_ok($$select price_evidence(gen_random_uuid(),'Jackets',null,365)$$,'42501',null,'another tenant denied');
select * from finish();
rollback;
