begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000631','image-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000632','image-outsider@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000631","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Image test','image-test',gen_random_uuid())::text,true);
select set_config('test.merchant',gen_random_uuid()::text,true);
select enable_zettle_pull(current_setting('test.tenant')::uuid,current_setting('test.merchant')::uuid);
select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),null,(current_store_policy(current_setting('test.tenant')::uuid)->'policy')||'{"vatModeConsignmentPrivate":"consignment_margin"}');
select publish_zettle_catalog_config(current_setting('test.tenant')::uuid,gen_random_uuid(),null,'{"consignment_margin":0}');
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Synthetic seller','image-seller@example.test','')::text,true);
select set_config('test.agreement',publish_seller_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),null,'Synthetic terms','Test only','en',false)::text,true);
select record_agreement_evidence(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,current_setting('test.agreement')::uuid,'Test evidence');
select set_config('test.session',create_reception_session(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid)::text,true);
select set_config('test.photo',gen_random_uuid()::text,true);
select set_config('test.path',current_setting('test.tenant')||'/'||current_setting('test.session')||'/'||current_setting('test.photo')||'.jpg',true);
reset role;
insert into storage.objects(bucket_id,name) values('reception-photos',current_setting('test.path'));
set local role authenticated;
select save_reception_sources(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,0,jsonb_build_array(jsonb_build_object('id',current_setting('test.photo'),'kind','photo','reference',current_setting('test.path'),'observation',''),jsonb_build_object('id','f0000000-0000-4000-8000-000000000638','kind','price-evidence','reference','Staff','observation','Test appraisal')));
select publish_reception_review(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,1,null,current_setting('test.agreement')::uuid,jsonb_build_object('attributes',jsonb_build_array(jsonb_build_object('slug','description','definitionVersion',1,'value','Test jacket','sourceIds',jsonb_build_array(current_setting('test.photo')),'certainty','observed')),'price',jsonb_build_object('currency','SEK','amount','100.00','rationale','Test','sourceIds',jsonb_build_array('f0000000-0000-4000-8000-000000000638'::text)),'questions','[]'::jsonb),now()+interval '1 day');
select receive_garment(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,'');
select set_config('test.item',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.item')::uuid,'reception_review',current_setting('test.session')::uuid,1,10000);
select set_config('test.request',gen_random_uuid()::text,true);
select throws_like($$select prepare_zettle_image(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.item')::uuid,current_setting('test.merchant')::uuid)$$,'%ZETTLE_IMAGE_PRODUCT_REQUIRED%','product export must precede image export');
select finish_zettle_product(current_setting('test.tenant')::uuid,prepare_zettle_product(current_setting('test.tenant')::uuid,current_setting('test.item')::uuid),'synced',null);
select throws_like($$select prepare_zettle_image(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.item')::uuid,gen_random_uuid())$$,'%ZETTLE_WRONG_MERCHANT%','merchant binding enforced');
select set_config('test.claim',prepare_zettle_image(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.item')::uuid,current_setting('test.merchant')::uuid)::text,true);
select is(current_setting('test.claim')::jsonb->>'reference',current_setting('test.path'),'accepted exact photo selected');
select is(current_setting('test.claim')::jsonb->>'fresh','true','one upload grant');
select is(prepare_zettle_image(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.item')::uuid,current_setting('test.merchant')::uuid)->>'fresh','false','same request never regrants upload');
select is(prepare_zettle_image(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.item')::uuid,current_setting('test.merchant')::uuid)->>'id',current_setting('test.request'),'different request converges');
select save_reception_sources(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,1,'[{"id":"f0000000-0000-4000-8000-000000000639","kind":"observation","reference":"Later","observation":"No photo"}]');
select is(prepare_zettle_image(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.item')::uuid,current_setting('test.merchant')::uuid)->>'reference',current_setting('test.path'),'later sources never replace the accepted image');
select throws_like($$select record_zettle_image_upload(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,'https://evil.example/photo.jpg')$$,'%INVALID_INPUT%','foreign URL rejected');
select lives_ok($$select record_zettle_image_upload(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,'https://image.izettle.com/product/synthetic.jpg')$$,'provider URL retained');
select lives_ok($$select record_zettle_image_upload(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,'https://image.izettle.com/product/synthetic.jpg')$$,'upload acknowledgement replay');
select throws_like($$select record_zettle_image_upload(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,'https://image.izettle.com/product/changed.jpg')$$,'%REQUEST_CONFLICT%','URL cannot be replaced');
select is(zettle_item_image_url(current_setting('test.tenant')::uuid,current_setting('test.item')::uuid),'https://image.izettle.com/product/synthetic.jpg','normal exports can preserve the registered image');
select lives_ok($$select finish_zettle_image(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid)$$,'association acknowledgement');
select lives_ok($$select finish_zettle_image(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid)$$,'association acknowledgement replay');
select is((select count(*) from zettle_image_outcomes where tenant_id=current_setting('test.tenant')::uuid),1::bigint,'one immutable success');
select is((select count(*) from zettle_stock_intents where tenant_id=current_setting('test.tenant')::uuid),0::bigint,'image export grants no stock');
select is((select count(*) from sales where tenant_id=current_setting('test.tenant')::uuid),0::bigint,'image export creates no sale');
select throws_ok($$delete from zettle_image_intents$$,'42501',null,'direct writes forbidden');
select set_config('test.purchase',register_purchase(current_setting('test.tenant')::uuid,gen_random_uuid(),'Synthetic',1000,'Test',true)::text,true);
select set_config('test.purchased_item',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.purchased_item')::uuid,'purchase',current_setting('test.purchase')::uuid,null,10000);
select is(prepare_zettle_image(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.purchased_item')::uuid,current_setting('test.merchant')::uuid),null::jsonb,'purchase origin never guesses an image');
select throws_like($$select prepare_zettle_image(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.purchased_item')::uuid,current_setting('test.merchant')::uuid)$$,'%REQUEST_CONFLICT%','request ID cannot be reused for another item');
select is((select status from zettle_image_status(current_setting('test.tenant')::uuid)),'synced','durable association status is visible');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000632","role":"authenticated"}';
select is((select count(*) from zettle_image_intents),0::bigint,'other tenant images hidden');
select throws_ok($$select prepare_zettle_image(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.item')::uuid,current_setting('test.merchant')::uuid)$$,'42501',null,'outsider denied');
select throws_ok($$select record_zettle_image_upload(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,'https://image.izettle.com/product/synthetic.jpg')$$,'42501',null,'outsider cannot acknowledge');
select throws_ok($$select zettle_item_image_url(current_setting('test.tenant')::uuid,current_setting('test.item')::uuid)$$,'42501',null,'outsider cannot read URL');
reset role;
select throws_like($$update zettle_image_uploads set image_url='https://image.izettle.com/product/changed.jpg'$$,'%IMMUTABLE%','privileged edits remain immutable');
insert into tenant_members(tenant_id,user_id,role) values(current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000000632','staff');
set local role authenticated;
select throws_ok($$select prepare_zettle_image(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.item')::uuid,current_setting('test.merchant')::uuid)$$,'42501',null,'staff cannot export imagery');
select throws_ok($$select finish_zettle_image(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid)$$,'42501',null,'staff cannot acknowledge association');
select is(zettle_item_image_url(current_setting('test.tenant')::uuid,current_setting('test.item')::uuid),'https://image.izettle.com/product/synthetic.jpg','staff may read the registered URL');
select is((select status from zettle_image_status_v2(current_setting('test.tenant')::uuid) where item_id=current_setting('test.item')::uuid),'synced','staff may read the associated status');
select is((select count(*) from zettle_image_intents),0::bigint,'staff cannot read private source references');
reset role;
insert into auth.mfa_factors(id,user_id,factor_type,status,created_at,updated_at) values(gen_random_uuid(),'f0000000-0000-4000-8000-000000000631','totp','verified',now(),now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000631","role":"authenticated","aal":"aal1"}';
select throws_ok($$select prepare_zettle_image(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.item')::uuid,current_setting('test.merchant')::uuid)$$,'42501',null,'MFA required for image export');
select throws_ok($$select zettle_item_image_url(current_setting('test.tenant')::uuid,current_setting('test.item')::uuid)$$,'42501',null,'MFA required for URL read');
select * from finish();
rollback;
