begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000070','close-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000071','close-staff@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000070","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Close test','close-test',gen_random_uuid())::text,true);
select set_config('test.merchant',gen_random_uuid()::text,true);
select enable_zettle_pull(current_setting('test.tenant')::uuid,current_setting('test.merchant')::uuid);
reset role;
alter table zettle_pull_connections disable trigger zettle_pull_immutable;
update zettle_pull_connections set cutover=clock_timestamp()-interval '3 days' where tenant_id=current_setting('test.tenant')::uuid;
alter table zettle_pull_connections enable trigger zettle_pull_immutable;
set local role authenticated;
select set_config('test.window',open_zettle_pull_window(current_setting('test.tenant')::uuid,current_setting('test.merchant')::uuid)::text,true);
select set_config('test.request',gen_random_uuid()::text,true);
select throws_like($$select abandon_zettle_pull_window(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.window')::uuid,' ')$$,'%INVALID_INPUT%','reason required');
select throws_like($$select abandon_zettle_pull_window(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.window')::uuid,repeat('x',501))$$,'%INVALID_INPUT%','reason bounded');
select lives_ok($$select abandon_zettle_pull_window(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.window')::uuid,'Provider page stuck')$$,'owner closes');
select lives_ok($$select abandon_zettle_pull_window(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.window')::uuid,'Provider page stuck')$$,'exact replay');
select throws_like($$select abandon_zettle_pull_window(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.window')::uuid,'Different reason')$$,'%REQUEST_CONFLICT%','reason cannot change');
select is((select count(*) from zettle_pull_window_closures),1::bigint,'one immutable closure');
select is(zettle_window_closure(current_setting('test.tenant')::uuid,current_setting('test.window')::uuid)->>'reason','Provider page stuck','reason visible');
select throws_like($$select record_zettle_pull_page(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.window')::uuid,null,null,'[]')$$,'%ZETTLE_WINDOW_ABANDONED%','closed window rejects pages');
select is((select count(*) from zettle_pull_pages where window_id=current_setting('test.window')::uuid),0::bigint,'no fake completion');
select is((select count(*) from zettle_sync_runs where tenant_id=current_setting('test.tenant')::uuid),0::bigint,'rejected page has no partial sync');
select set_config('test.next',open_zettle_pull_window(current_setting('test.tenant')::uuid,current_setting('test.merchant')::uuid)::text,true);
select is((select start_at from zettle_pull_windows where id=current_setting('test.next')::uuid),(select end_at from zettle_pull_windows where id=current_setting('test.window')::uuid),'next starts exactly at abandoned end');
select lives_ok($$select record_zettle_pull_page(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.next')::uuid,null,null,'[]')$$,'next accepts pages');
select throws_like($$select abandon_zettle_pull_window(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.next')::uuid,'Already complete')$$,'%ZETTLE_WINDOW_COMPLETE%','cannot abandon completed window');
select throws_like($$update zettle_pull_window_closures set reason='changed'$$,'%permission denied%','no direct write');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000071","role":"authenticated"}';
select is((select count(*) from zettle_pull_window_closures),0::bigint,'outsider cannot read closure');
select throws_like($$select abandon_zettle_pull_window(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.next')::uuid,'outsider')$$,'%FORBIDDEN%','outsider cannot close');
reset role;
insert into tenant_members(tenant_id,user_id,role) values(current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000000071','admin');
set local role authenticated;
select throws_like($$select abandon_zettle_pull_window(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.next')::uuid,'admin')$$,'%FORBIDDEN%','admin cannot close');
select * from finish();
rollback;
