begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000751','cron-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000752','cron-worker@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000751","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Cron test','cron-test',gen_random_uuid())::text,true);
select set_config('test.merchant',gen_random_uuid()::text,true);
select enable_zettle_pull(current_setting('test.tenant')::uuid,current_setting('test.merchant')::uuid);
select enable_automation(current_setting('test.tenant')::uuid,gen_random_uuid(),'zettle_pull','cron-worker@example.test');
select enable_automation(current_setting('test.tenant')::uuid,gen_random_uuid(),'fortnox_send','cron-worker@example.test');
select set_config('test.purchase',register_purchase(current_setting('test.tenant')::uuid,gen_random_uuid(),'Synthetic',1000,'Test',true)::text,true);
select set_config('test.item',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.item')::uuid,'purchase',current_setting('test.purchase')::uuid,null,2500);
select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),null,(current_store_policy(current_setting('test.tenant')::uuid)->'policy') || '{"vatModeStoreOwned":"store_full"}');
reset role;
alter table zettle_pull_connections disable trigger zettle_pull_immutable;
update zettle_pull_connections set cutover=clock_timestamp()-interval '3 hours' where tenant_id=current_setting('test.tenant')::uuid;
alter table zettle_pull_connections enable trigger zettle_pull_immutable;
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000752","role":"authenticated"}';
select accept_automation_grants();
select set_config('test.job',prepare_zettle_automatic_pull(current_setting('test.tenant')::uuid,current_setting('test.merchant')::uuid)::text,true);
select ok((current_setting('test.job')::jsonb->>'id') is not null,'active scope prepares a page');
select is(prepare_zettle_automatic_pull(current_setting('test.tenant')::uuid,current_setting('test.merchant')::uuid),null::jsonb,'duplicate delivery does not repeat HTTP');
select is(accept_automation_grants(),'[]'::jsonb,'later invocations accept nothing new');
select is(jsonb_array_length(zettle_automation_tenants()),1,'existing accepted grant remains runnable');
select throws_ok($$select prepare_zettle_automatic_pull(gen_random_uuid(),current_setting('test.merchant')::uuid)$$,'42501',null,'another tenant is denied');
select throws_like($$select prepare_zettle_automatic_pull(current_setting('test.tenant')::uuid,gen_random_uuid())$$,'%ZETTLE_NOT_CONNECTED%','merchant mismatch is denied before HTTP');
select throws_ok($$select current_store_policy(current_setting('test.tenant')::uuid)$$,'42501',null,'public policy reader is not broadened');
select throws_ok($$select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'zettle','x',now(),'SEK','[]','{}')$$,'42501',null,'automation cannot call arbitrary sale command');
select throws_ok($$select record_zettle_page(current_setting('test.tenant')::uuid,gen_random_uuid(),null,null,'[]')$$,'42501',null,'automation cannot bypass window validation');
select throws_ok($$select prepare_zettle_product(current_setting('test.tenant')::uuid,gen_random_uuid())$$,'42501',null,'automation cannot export products');
select throws_ok($$select abandon_zettle_pull_window(current_setting('test.tenant')::uuid,gen_random_uuid(),(current_setting('test.job')::jsonb->>'windowId')::uuid,'cron')$$,'42501',null,'automation cannot abandon a window');
create temp view cron_receipt as select jsonb_build_array(jsonb_build_object('externalId','12345678-1234-4234-8234-123456780075','occurredAt',current_setting('test.job')::jsonb->>'startDate','currency','SEK','amountOre',2500,'blockedReason',null,'lines',jsonb_build_array(jsonb_build_object('lineNo',1,'reference','I-'||upper(left(current_setting('test.item'),8)),'labelConflict',false,'description','Synthetic','priceOre',2500)))) purchases;
select lives_ok($$select record_zettle_pull_page(current_setting('test.tenant')::uuid,(current_setting('test.job')::jsonb->>'id')::uuid,(current_setting('test.job')::jsonb->>'windowId')::uuid,null,'cursor-1',(select purchases from cron_receipt))$$,'matched receipt reaches the sale engine');
select lives_ok($$select record_zettle_pull_page(current_setting('test.tenant')::uuid,(current_setting('test.job')::jsonb->>'id')::uuid,(current_setting('test.job')::jsonb->>'windowId')::uuid,null,'cursor-1',(select purchases from cron_receipt))$$,'page replay remains safe');
select lives_ok($$select finish_zettle_automatic_pull(current_setting('test.tenant')::uuid,(current_setting('test.job')::jsonb->>'id')::uuid,'received')$$,'bounded outcome recorded');
select throws_like($$select finish_zettle_automatic_pull(current_setting('test.tenant')::uuid,(current_setting('test.job')::jsonb->>'id')::uuid,'secret provider body')$$,'%INVALID_INPUT%','raw provider errors cannot enter audit');
reset role;
select is((select count(*) from sales where tenant_id=current_setting('test.tenant')::uuid),1::bigint,'matched sale recorded exactly once, not held by nested authorization');
select is((select recorded_by from sales where tenant_id=current_setting('test.tenant')::uuid),'f0000000-0000-4000-8000-000000000752'::uuid,'sale identifies automation');
select is((select vat_ore from sale_lines where tenant_id=current_setting('test.tenant')::uuid),500::bigint,'engine VAT arithmetic preserved');
select is((select created_by from zettle_pull_pages where id=(current_setting('test.job')::jsonb->>'id')::uuid),'f0000000-0000-4000-8000-000000000752'::uuid,'page actor is automation identity');
select ok(not has_function_privilege('authenticated','komisio_private.record_sale_core(uuid,uuid,text,text,timestamptz,text,jsonb,jsonb)','EXECUTE'),'private sale core inaccessible');
insert into auth.mfa_factors(id,user_id,factor_type,status,created_at,updated_at)
 values(gen_random_uuid(),'f0000000-0000-4000-8000-000000000752','totp','verified',now(),now());
set local role authenticated;
select throws_like($$select prepare_zettle_automatic_pull(current_setting('test.tenant')::uuid,current_setting('test.merchant')::uuid)$$,'%AUTH_REQUIRED%','enrolled MFA cannot be bypassed by the worker');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000752","role":"authenticated","aal":"aal2"}';
select lives_ok($$select record_zettle_pull_page(current_setting('test.tenant')::uuid,gen_random_uuid(),(current_setting('test.job')::jsonb->>'windowId')::uuid,'cursor-1','cursor-1','[]')$$,'MFA-verified identity can complete the window');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000751","role":"authenticated"}';
select is(zettle_automatic_pull_status(current_setting('test.tenant')::uuid)->>'outcome','received','owner sees last outcome');
select disable_automation(current_setting('test.tenant')::uuid,'zettle_pull');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000752","role":"authenticated","aal":"aal2"}';
select is(tenant_role(current_setting('test.tenant')::uuid),'automation','another scope retains membership without Zettle authority');
select is(zettle_automation_tenants(),'[]'::jsonb,'disabled grant is not scheduled');
select throws_ok($$select open_zettle_pull_window(current_setting('test.tenant')::uuid,current_setting('test.merchant')::uuid)$$,'42501',null,'revocation denies opening');
select throws_ok($$select record_zettle_pull_page(current_setting('test.tenant')::uuid,gen_random_uuid(),(current_setting('test.job')::jsonb->>'windowId')::uuid,null,null,'[]')$$,'42501',null,'revocation denies recording');
select * from finish();
rollback;
