begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000411','fx-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000412','fx-staff@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000411","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Fortnox voucher test','fortnox-voucher-test',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Synthetic seller','seller@fx.test','')::text,true);
select set_config('test.agreement',publish_seller_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),null,'Synthetic terms','Only a test','en',false)::text,true);
select record_agreement_evidence(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,current_setting('test.agreement')::uuid,'Signed paper');
select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),null,(current_store_policy(current_setting('test.tenant')::uuid)->'policy') || '{"vatModeConsignmentPrivate":"consignment_margin","vatModeStoreOwned":"store_full"}');
select set_config('test.bag',receive_bag_with_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'',current_setting('test.agreement')::uuid)::text,true);
select set_config('test.draft',gen_random_uuid()::text,true);
select save_inspection_draft(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.bag')::uuid,current_setting('test.draft')::uuid,0,'Synthetic jacket','Jackets','Good');
select set_config('test.item',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.item')::uuid,'inspection_draft',current_setting('test.draft')::uuid,1,20000);
select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','K-1','2026-09-10T10:00:00Z','SEK',jsonb_build_array(jsonb_build_object('itemId',current_setting('test.item'),'priceOre',20000)));
select set_config('test.close',gen_random_uuid()::text,true);
select generate_day_close(current_setting('test.tenant')::uuid,current_setting('test.close')::uuid,'2026-09-10');
select publish_accounting_map(current_setting('test.tenant')::uuid,gen_random_uuid(),null,
 '{"grossOre":{"account":"1930","side":"debit"},"sellerCreditOre":{"account":"2890","side":"credit"},"commissionOre":{"account":"3010","side":"credit"},"commissionVatOre":{"account":"2610","side":"credit"}}');
select set_config('test.export',export_day_close(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.close')::uuid)::text,true);
select set_config('test.cipher','{"iv":"aWl2","tag":"dGFn","data":"ZGF0YQ=="}',true);
-- No connection: nothing to send with.
select throws_like($$select begin_fortnox_send(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.export')::uuid)$$,'%FORTNOX_NOT_CONNECTED%','a send needs a connection');
select store_fortnox_connection(current_setting('test.tenant')::uuid,'1751085','Komisio Test','5561234567',current_setting('test.cipher')::jsonb,'bookkeeping',now()+interval '1 hour');
select throws_like($$select begin_fortnox_send(current_setting('test.tenant')::uuid,gen_random_uuid(),gen_random_uuid())$$,'%EXPORT_NOT_FOUND%','the export must exist in the tenant');

select set_config('test.send',gen_random_uuid()::text,true);
select begin_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send')::uuid,current_setting('test.export')::uuid);
select throws_like($$select reconcile_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send')::uuid,'confirmed_absent','A',42,2026,'Checked')$$,'%INVALID_INPUT%','absence remains unavailable');
select throws_like($$select reconcile_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send')::uuid,'confirmed_sent','A',42,2026,' ')$$,'%INVALID_INPUT%','evidence required');
select throws_like($$select reconcile_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send')::uuid,'confirmed_sent','A',42,2026,repeat('x',501))$$,'%INVALID_INPUT%','evidence bounded');
reset role;
insert into tenant_members(tenant_id,user_id,role) values(current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000000412','admin');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000412","role":"authenticated"}';
select throws_ok($$select reconcile_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send')::uuid,'confirmed_sent','A',42,2026,'Checked')$$,'42501',null,'admin cannot reconcile');
reset role;
update tenant_members set role='staff' where tenant_id=current_setting('test.tenant')::uuid and user_id='f0000000-0000-4000-8000-000000000412';
set local role authenticated;
select throws_ok($$select reconcile_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send')::uuid,'confirmed_sent','A',42,2026,'Checked')$$,'42501',null,'staff cannot reconcile');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000411","role":"authenticated"}';
select complete_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send')::uuid,'failed','',null,null,'FORTNOX_OUTCOME_UNKNOWN','');
select is(reconcile_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send')::uuid,'confirmed_sent','A',42,2026,'Owner compared date and lines')->>'status','sent','unknown becomes confirmed sent');
select is(reconcile_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send')::uuid,'confirmed_sent','A',42,2026,'Owner compared date and lines')->>'status','sent','exact replay succeeds');
select throws_like($$select reconcile_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send')::uuid,'confirmed_sent','A',43,2026,'Owner compared date and lines')$$,'%REQUEST_CONFLICT%','different voucher cannot replace evidence');
select throws_like($$select reconcile_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send')::uuid,'confirmed_sent','A',42,2026,'Changed evidence')$$,'%REQUEST_CONFLICT%','evidence immutable on replay');
select throws_like($$select begin_fortnox_send(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.export')::uuid)$$,'%FORTNOX_ALREADY_SENT%','confirmed voucher prevents another send');
select is((select count(*) from access_events where tenant_id=current_setting('test.tenant')::uuid and action='fortnox.reconciled'),1::bigint,'one reconciliation event');
select is((select error_code from fortnox_voucher_sends where id=current_setting('test.send')::uuid),'FORTNOX_OUTCOME_UNKNOWN','original transport error preserved');
reset role;
select throws_ok($$update fortnox_voucher_sends set reconciliation_evidence='changed' where id=current_setting('test.send')::uuid$$,'55000',null,'direct edits remain forbidden');
set local role authenticated;
select publish_accounting_map(current_setting('test.tenant')::uuid,gen_random_uuid(),(current_accounting_map(current_setting('test.tenant')::uuid)->>'id')::uuid,current_accounting_map(current_setting('test.tenant')::uuid)->'map');
select set_config('test.export2',export_day_close(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.close')::uuid)::text,true);
select set_config('test.send2',gen_random_uuid()::text,true);
select begin_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send2')::uuid,current_setting('test.export2')::uuid);
select is(reconcile_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send2')::uuid,'confirmed_sent','A',43,2026,'Checked pending receipt')->>'status','sent','pending can be confirmed without another POST');
select is((select actor=reconciled_by and database_number='1751085' from fortnox_voucher_sends where id=current_setting('test.send2')::uuid),true,'actor and company binding preserved');
select throws_ok($$select reconcile_fortnox_send(gen_random_uuid(),current_setting('test.send2')::uuid,'confirmed_sent','A',43,2026,'Checked pending receipt')$$,'42501',null,'other tenant refused');
select publish_accounting_map(current_setting('test.tenant')::uuid,gen_random_uuid(),(current_accounting_map(current_setting('test.tenant')::uuid)->>'id')::uuid,current_accounting_map(current_setting('test.tenant')::uuid)->'map');
select set_config('test.export3',export_day_close(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.close')::uuid)::text,true);
select set_config('test.send3',gen_random_uuid()::text,true);
select begin_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send3')::uuid,current_setting('test.export3')::uuid);
select complete_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send3')::uuid,'sent','A',44,2026,'','');
select throws_like($$select reconcile_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send3')::uuid,'confirmed_sent','A',44,2026,'Already sent')$$,'%SEND_NOT_PENDING%','ordinary sent row cannot be reconciled');
select * from finish();
rollback;
