begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000821','revision-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000822','revision-worker@example.test',now()),
 ('f0000000-0000-4000-8000-000000000823','revision-staff@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000821","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Revision test','revision-test',gen_random_uuid())::text,true);
select set_config('test.cipher','{"iv":"a","tag":"b","data":"synthetic"}',true);
select throws_like($$select refresh_fortnox_tokens(current_setting('test.tenant')::uuid,1,current_setting('test.cipher')::jsonb,'bookkeeping',now()+interval '1 hour')$$,'%FORTNOX_NOT_CONNECTED%','refresh cannot create a connection');
select store_fortnox_connection(current_setting('test.tenant')::uuid,'123','Synthetic company','456',current_setting('test.cipher')::jsonb,'bookkeeping',now()+interval '1 hour');
select set_config('test.revision',read_fortnox_connection(current_setting('test.tenant')::uuid)->>'revision',true);
select set_config('test.before',read_fortnox_connection(current_setting('test.tenant')::uuid)::text,true);
select is(refresh_fortnox_tokens(current_setting('test.tenant')::uuid,current_setting('test.revision')::bigint,'{"iv":"c","tag":"d","data":"new"}','bookkeeping',now()+interval '2 hours')->>'status','refreshed','current revision refreshes');
select ok((read_fortnox_connection(current_setting('test.tenant')::uuid)->>'revision')::bigint>current_setting('test.revision')::bigint,'revision increases');
select is(read_fortnox_connection(current_setting('test.tenant')::uuid)-array['cipher','scope','expiresAt','refreshedAt','revision'],current_setting('test.before')::jsonb-array['cipher','scope','expiresAt','refreshedAt','revision'],'company and connection provenance unchanged');
select set_config('test.current',read_fortnox_connection(current_setting('test.tenant')::uuid)::text,true);
select is(refresh_fortnox_tokens(current_setting('test.tenant')::uuid,current_setting('test.revision')::bigint,current_setting('test.cipher')::jsonb,'bookkeeping',now()+interval '3 hours')->>'error','FORTNOX_CONNECTION_CHANGED','stale revision returns a refusal');
select is(read_fortnox_connection(current_setting('test.tenant')::uuid),current_setting('test.current')::jsonb,'stale result cannot overwrite the row');
select is((select count(*) from fortnox_connection_events where tenant_id=current_setting('test.tenant')::uuid and kind='refused' and detail->>'expected_revision'=current_setting('test.revision')),1::bigint,'refusal event survives the result');
select disconnect_fortnox(current_setting('test.tenant')::uuid);
select store_fortnox_connection(current_setting('test.tenant')::uuid,'789','New company','456',current_setting('test.cipher')::jsonb,'bookkeeping',now()+interval '1 hour');
select ok((read_fortnox_connection(current_setting('test.tenant')::uuid)->>'revision')::bigint>(current_setting('test.current')::jsonb->>'revision')::bigint,'reconnect never reuses revision');
select is(refresh_fortnox_tokens(current_setting('test.tenant')::uuid,current_setting('test.revision')::bigint,current_setting('test.cipher')::jsonb,'bookkeeping',now()+interval '3 hours')->>'error','FORTNOX_CONNECTION_CHANGED','old connection reader cannot refresh the replacement');
select set_config('test.revision',read_fortnox_connection(current_setting('test.tenant')::uuid)->>'revision',true);
select store_fortnox_connection(current_setting('test.tenant')::uuid,'789','New company','456',current_setting('test.cipher')::jsonb,'bookkeeping',now()+interval '1 hour');
select ok((read_fortnox_connection(current_setting('test.tenant')::uuid)->>'revision')::bigint>current_setting('test.revision')::bigint,'OAuth replacement also advances revision');
select enable_automation(current_setting('test.tenant')::uuid,gen_random_uuid(),'zettle_pull','revision-worker@example.test');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000822","role":"authenticated"}';
select accept_automation_grants();
select throws_ok($$select read_fortnox_connection(current_setting('test.tenant')::uuid)$$,'42501',null,'other scope cannot read tokens');
select throws_ok($$select refresh_fortnox_tokens(current_setting('test.tenant')::uuid,1,current_setting('test.cipher')::jsonb,'bookkeeping',now())$$,'42501',null,'other scope cannot refresh');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000821","role":"authenticated"}';
select enable_automation(current_setting('test.tenant')::uuid,gen_random_uuid(),'fortnox_send','revision-worker@example.test');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000822","role":"authenticated"}';
select accept_automation_grants();
select set_config('test.revision',read_fortnox_connection(current_setting('test.tenant')::uuid)->>'revision',true);
select is(refresh_fortnox_tokens(current_setting('test.tenant')::uuid,current_setting('test.revision')::bigint,current_setting('test.cipher')::jsonb,'bookkeeping',now()+interval '1 hour')->>'status','refreshed','scoped automation refreshes');
select is(read_fortnox_connection(current_setting('test.tenant')::uuid)->>'databaseNumber','789','automation cannot change company');
select throws_ok($$select disconnect_fortnox(current_setting('test.tenant')::uuid)$$,'42501',null,'automation cannot disconnect');
select throws_ok($$select fortnox_connection_status(current_setting('test.tenant')::uuid)$$,'42501',null,'automation cannot read status');
select throws_ok($$select store_fortnox_connection(current_setting('test.tenant')::uuid,'789','New company','456',current_setting('test.cipher')::jsonb,'bookkeeping',now())$$,'42501',null,'automation cannot connect or replace');
select throws_ok($$select refresh_fortnox_tokens(gen_random_uuid(),1,current_setting('test.cipher')::jsonb,'bookkeeping',now())$$,'42501',null,'other tenant denied');
select throws_ok($$select * from fortnox_connections$$,'42501',null,'no direct ciphertext read');
reset role;
insert into tenant_members(tenant_id,user_id,role) values(current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000000823','staff');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000823","role":"authenticated"}';
select throws_ok($$select refresh_fortnox_tokens(current_setting('test.tenant')::uuid,1,current_setting('test.cipher')::jsonb,'bookkeeping',now())$$,'42501',null,'staff cannot refresh');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000821","role":"authenticated"}';
select throws_like($$select refresh_fortnox_tokens(current_setting('test.tenant')::uuid,null,current_setting('test.cipher')::jsonb,'bookkeeping',now())$$,'%INVALID_INPUT%','revision required');
select throws_like($$select refresh_fortnox_tokens(current_setting('test.tenant')::uuid,1,'{}','bookkeeping',now())$$,'%INVALID_INPUT%','cipher envelope required');
select disable_automation(current_setting('test.tenant')::uuid,'fortnox_send');
select change_member(current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000000823','admin');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000823","role":"authenticated"}';
select set_config('test.revision',read_fortnox_connection(current_setting('test.tenant')::uuid)->>'revision',true);
select is(refresh_fortnox_tokens(current_setting('test.tenant')::uuid,current_setting('test.revision')::bigint,current_setting('test.cipher')::jsonb,'bookkeeping',now()+interval '1 hour')->>'status','refreshed','admin retains refresh access');
select throws_ok($$select nextval('komisio_private.fortnox_connection_revision')$$,'42501',null,'authenticated cannot allocate private revisions');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000822","role":"authenticated"}';
select throws_ok($$select read_fortnox_connection(current_setting('test.tenant')::uuid)$$,'42501',null,'scope revocation immediately closes reads');
select throws_ok($$select refresh_fortnox_tokens(current_setting('test.tenant')::uuid,1,current_setting('test.cipher')::jsonb,'bookkeeping',now())$$,'42501',null,'scope revocation immediately closes refresh');
select * from finish();
rollback;
