begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000411','fx-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000412','fx-staff@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000411","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Fortnox voucher test','fortnox-voucher-test',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Synthetic seller','seller@fx.test','')::text,true);
select set_config('test.agreement',publish_seller_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),null,'Synthetic terms','Only a test','en',false)::text,true);
select record_agreement_evidence(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,current_setting('test.agreement')::uuid,'Signed paper');
select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),null,(current_store_policy(current_setting('test.tenant')::uuid)->'policy') || '{"vatModeConsignmentPrivate":"consignment_margin","vatModeStoreOwned":"store_full"}');
select set_config('test.bag',receive_bag_with_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'',current_setting('test.agreement')::uuid)::text,true);
select set_config('test.draft',gen_random_uuid()::text,true);
select save_inspection_draft(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.bag')::uuid,current_setting('test.draft')::uuid,0,'Synthetic jacket','Jackets','Good');
select set_config('test.item',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.item')::uuid,'inspection_draft',current_setting('test.draft')::uuid,1,20000);
select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','K-1','2026-09-10T10:00:00Z','SEK',jsonb_build_array(jsonb_build_object('itemId',current_setting('test.item'),'priceOre',20000)));
select set_config('test.close',gen_random_uuid()::text,true);
select generate_day_close(current_setting('test.tenant')::uuid,current_setting('test.close')::uuid,'2026-09-10');
select publish_accounting_map(current_setting('test.tenant')::uuid,gen_random_uuid(),null,
 '{"grossOre":{"account":"1930","side":"debit"},"sellerCreditOre":{"account":"2890","side":"credit"},"commissionOre":{"account":"3010","side":"credit"},"commissionVatOre":{"account":"2610","side":"credit"}}');
select set_config('test.export',export_day_close(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.close')::uuid)::text,true);
select set_config('test.cipher','{"iv":"aWl2","tag":"dGFn","data":"ZGF0YQ=="}',true);

select store_fortnox_connection(current_setting('test.tenant')::uuid,'1751085','Komisio Test','',current_setting('test.cipher')::jsonb,'bookkeeping',now()+interval '1 hour');
reset role;
insert into auth.users(id,email,email_confirmed_at) values('f0000000-0000-4000-8000-000000000831','fortnox-worker@example.test',now());
set local role authenticated;
select enable_automation(current_setting('test.tenant')::uuid,gen_random_uuid(),'zettle_pull','fortnox-worker@example.test');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000831","role":"authenticated"}';
select accept_automation_grants();
select is(fortnox_automation_tenants(),'[]'::jsonb,'wrong scope has no stores');
select throws_ok($$select fortnox_automatic_exports(current_setting('test.tenant')::uuid)$$,'42501',null,'wrong scope cannot list exports');
select throws_ok($$select begin_fortnox_send(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.export')::uuid)$$,'42501',null,'wrong scope cannot begin');
select throws_ok($$select complete_fortnox_send(current_setting('test.tenant')::uuid,gen_random_uuid(),'failed','',null,null,'FORTNOX_PREFLIGHT_FAILED','')$$,'42501',null,'wrong scope cannot complete');
select throws_ok($$select record_fortnox_check(current_setting('test.tenant')::uuid,'checked','{}')$$,'42501',null,'wrong scope cannot record check');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000411","role":"authenticated"}';
select enable_automation(current_setting('test.tenant')::uuid,gen_random_uuid(),'fortnox_send','fortnox-worker@example.test');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000831","role":"authenticated"}';
select accept_automation_grants();
select is(jsonb_array_length(fortnox_automation_tenants()),1,'accepted scope lists its store');
select is(jsonb_array_length(fortnox_automatic_exports(current_setting('test.tenant')::uuid)),1,'fresh export eligible');
select record_fortnox_check(current_setting('test.tenant')::uuid,'refused','{"reason":"save_failed"}');
select set_config('test.send',gen_random_uuid()::text,true);
select is((begin_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send')::uuid,current_setting('test.export')::uuid)->>'dispatchAllowed')::boolean,true,'worker obtains fresh dispatch');
select is(jsonb_array_length(fortnox_automatic_exports(current_setting('test.tenant')::uuid)),0,'pending excluded');
select is((begin_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send')::uuid,current_setting('test.export')::uuid)->>'dispatchAllowed')::boolean,false,'worker replay cannot POST');
select complete_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send')::uuid,'failed','',null,null,'FORTNOX_PREFLIGHT_FAILED','');
select is(jsonb_array_length(fortnox_automatic_exports(current_setting('test.tenant')::uuid)),1,'proven preflight failure eligible');
select set_config('test.send',gen_random_uuid()::text,true);
select begin_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send')::uuid,current_setting('test.export')::uuid);
select complete_fortnox_send(current_setting('test.tenant')::uuid,current_setting('test.send')::uuid,'failed','',null,null,'FORTNOX_OUTCOME_UNKNOWN','');
select is(jsonb_array_length(fortnox_automatic_exports(current_setting('test.tenant')::uuid)),0,'ambiguous result excluded despite older safe failure');
select throws_like($$select begin_fortnox_send(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.export')::uuid)$$,'%FORTNOX_OUTCOME_UNKNOWN%','worker cannot unlock unknown sends');
select throws_ok($$select store_fortnox_connection(current_setting('test.tenant')::uuid,'1751085','Komisio Test','',current_setting('test.cipher')::jsonb,'bookkeeping',now())$$,'42501',null,'worker cannot connect');
select throws_ok($$select disconnect_fortnox(current_setting('test.tenant')::uuid)$$,'42501',null,'worker cannot disconnect');
select throws_ok($$select fortnox_connection_status(current_setting('test.tenant')::uuid)$$,'42501',null,'worker cannot read connection status');
select throws_ok($$select fortnox_automatic_exports(gen_random_uuid())$$,'42501',null,'other tenant refused');
select set_config('test.run',gen_random_uuid()::text,true);
select finish_fortnox_automatic_run(current_setting('test.tenant')::uuid,current_setting('test.run')::uuid,'failed',0);
select finish_fortnox_automatic_run(current_setting('test.tenant')::uuid,current_setting('test.run')::uuid,'failed',0);
select throws_like($$select finish_fortnox_automatic_run(current_setting('test.tenant')::uuid,current_setting('test.run')::uuid,'complete',1)$$,'%REQUEST_CONFLICT%','run replay cannot alter outcome');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000411","role":"authenticated"}';
select is(fortnox_automatic_status(current_setting('test.tenant')::uuid)->>'outcome','failed','owner sees run failure');
select is((select count(*) from access_events where tenant_id=current_setting('test.tenant')::uuid and action='fortnox.automatic_run'),1::bigint,'one durable run event');
select is((select actor_id::text from access_events where tenant_id=current_setting('test.tenant')::uuid and action='fortnox.automatic_run'),'f0000000-0000-4000-8000-000000000831','run attributed to automation, not enabling owner');
select disable_automation(current_setting('test.tenant')::uuid,'fortnox_send');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000831","role":"authenticated"}';
select is(fortnox_automation_tenants(),'[]'::jsonb,'revoked grant no longer scheduled');
select throws_ok($$select begin_fortnox_send(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.export')::uuid)$$,'42501',null,'revocation closes begin');
select throws_ok($$select complete_fortnox_send(current_setting('test.tenant')::uuid,gen_random_uuid(),'failed','',null,null,'FORTNOX_PREFLIGHT_FAILED','')$$,'42501',null,'revocation closes complete');
select * from finish();
rollback;
