begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000841','rule-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000842','rule-staff@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000841","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Label rule test','label-rule-test',gen_random_uuid())::text,true);
select set_config('test.printer',register_printer(current_setting('test.tenant')::uuid,gen_random_uuid(),'Synthetic','tcp','127.0.0.1:9100','',203,true)::text,true);
select is(label_print_rules(current_setting('test.tenant')::uuid),'[]'::jsonb,'no automatic rules by default');
select is(set_label_print_rule(current_setting('test.tenant')::uuid,'item',current_setting('test.printer')::uuid,2,true)->>'kind','item','owner configures a rule');
select set_label_print_rule(current_setting('test.tenant')::uuid,'item',current_setting('test.printer')::uuid,2,true);
select is((select count(*) from access_events where tenant_id=current_setting('test.tenant')::uuid and action='label_print_rule.changed'),1::bigint,'identical replay does not add audit');
select is(jsonb_array_length(label_print_rules(current_setting('test.tenant')::uuid)),1,'one row per kind');
select throws_like($$select set_label_print_rule(current_setting('test.tenant')::uuid,'item',current_setting('test.printer')::uuid,0,true)$$,'%INVALID_INPUT%','positive copies required');
select throws_like($$select set_label_print_rule(current_setting('test.tenant')::uuid,'item',current_setting('test.printer')::uuid,21,true)$$,'%INVALID_INPUT%','copy limit retained');
select throws_like($$select set_label_print_rule(current_setting('test.tenant')::uuid,'other',current_setting('test.printer')::uuid,1,true)$$,'%INVALID_INPUT%','unknown kind refused');
select throws_like($$select set_label_print_rule(current_setting('test.tenant')::uuid,'item',gen_random_uuid(),1,true)$$,'%PRINTER_NOT_FOUND%','unknown printer refused');
select throws_ok($$select set_label_print_rule(gen_random_uuid(),'item',current_setting('test.printer')::uuid,1,true)$$,'42501',null,'other tenant write refused');
select throws_ok($$select label_print_rules(gen_random_uuid())$$,'42501',null,'other tenant read refused');
select throws_ok($$update label_print_rules set copies=10$$,'42501',null,'direct writes denied');
reset role;
insert into tenant_members(tenant_id,user_id,role) values(current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000000842','staff');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000842","role":"authenticated"}';
select is(jsonb_array_length(label_print_rules(current_setting('test.tenant')::uuid)),1,'staff reads rules');
select throws_ok($$select set_label_print_rule(current_setting('test.tenant')::uuid,'item',current_setting('test.printer')::uuid,1,false)$$,'42501',null,'staff cannot configure rules');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000841","role":"authenticated"}';
select change_member(current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000000842','admin');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000842","role":"authenticated"}';
select is((set_label_print_rule(current_setting('test.tenant')::uuid,'item',current_setting('test.printer')::uuid,1,false)->>'enabled')::boolean,false,'admin can disable');
select is((select count(*) from access_events where tenant_id=current_setting('test.tenant')::uuid and action='label_print_rule.changed'),2::bigint,'changed setting is audited');
select is((select count(*) from print_jobs where tenant_id=current_setting('test.tenant')::uuid),0::bigint,'configuration alone queues nothing');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000841","role":"authenticated"}';
select change_member(current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000000842','readonly');
select set_config('test.other',create_tenant('Other rule store','other-label-rule-test',gen_random_uuid())::text,true);
select set_config('test.other_printer',register_printer(current_setting('test.other')::uuid,gen_random_uuid(),'Other','tcp','127.0.0.1:9100','',203,true)::text,true);
select throws_like($$select set_label_print_rule(current_setting('test.tenant')::uuid,'item',current_setting('test.other_printer')::uuid,1,true)$$,'%PRINTER_NOT_FOUND%','printer from another owned store refused');
select set_config('test.inactive',register_printer(current_setting('test.tenant')::uuid,gen_random_uuid(),'Inactive','tcp','127.0.0.1:9100','',203,false)::text,true);
select throws_like($$select set_label_print_rule(current_setting('test.tenant')::uuid,'item',current_setting('test.inactive')::uuid,1,true)$$,'%PRINTER_INACTIVE%','cannot enable an inactive printer');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000842","role":"authenticated"}';
select is(jsonb_array_length(label_print_rules(current_setting('test.tenant')::uuid)),1,'readonly members read rules');
select throws_ok($$select set_label_print_rule(current_setting('test.tenant')::uuid,'item',current_setting('test.printer')::uuid,1,true)$$,'42501',null,'readonly members cannot write rules');
reset role;
select throws_ok($$update label_print_rules set copies=10$$,'55000',null,'privileged direct updates are guarded');
select throws_ok($$delete from label_print_rules$$,'55000',null,'rules cannot be deleted');
insert into auth.users(id,is_anonymous) values ('f0000000-0000-4000-8000-000000000843',true);
insert into auth.users(id,email,email_confirmed_at) values ('f0000000-0000-4000-8000-000000000844','rule-automation@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000841","role":"authenticated"}';
select set_config('test.pair',create_print_pairing_code(current_setting('test.tenant')::uuid,current_setting('test.printer')::uuid)::text,true);
select enable_automation(current_setting('test.tenant')::uuid,gen_random_uuid(),'zettle_pull','rule-automation@example.test');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000843","role":"authenticated","is_anonymous":true}';
select pair_print_device(current_setting('test.pair')::jsonb->>'code','Synthetic',null);
select is((select count(*) from label_print_rules),0::bigint,'device RLS reveals no rules');
select throws_ok($$select label_print_rules(current_setting('test.tenant')::uuid)$$,'42501',null,'device cannot read rule RPC');
select throws_ok($$select set_label_print_rule(current_setting('test.tenant')::uuid,'item',current_setting('test.printer')::uuid,1,true)$$,'42501',null,'device cannot configure rules');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000844","role":"authenticated"}';
select accept_automation_grants();
select is((select count(*) from label_print_rules),0::bigint,'automation RLS reveals no rules');
select throws_ok($$select label_print_rules(current_setting('test.tenant')::uuid)$$,'42501',null,'automation cannot read rule RPC');
select throws_ok($$select set_label_print_rule(current_setting('test.tenant')::uuid,'item',current_setting('test.printer')::uuid,1,true)$$,'42501',null,'automation cannot configure rules');
select * from finish();
rollback;
