begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000501','ha-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000502','ha-host@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000501","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Host activity test','host-activity-test',gen_random_uuid())::text,true);
select set_config('test.quiet',create_tenant('Host activity quiet','host-activity-quiet',gen_random_uuid())::text,true);
select set_config('test.s1',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Anna Andersson','anna@ha.test','')::text,true);
select set_config('test.agreement',publish_seller_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),null,'Synthetic terms','Only a test','en',false)::text,true);
select record_agreement_evidence(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.s1')::uuid,current_setting('test.agreement')::uuid,'Signed paper');
select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),null,(current_store_policy(current_setting('test.tenant')::uuid)->'policy') || '{"vatModeConsignmentPrivate":"consignment_margin","vatModeStoreOwned":"store_full"}');
select set_config('test.bag',receive_bag_with_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.s1')::uuid,'',current_setting('test.agreement')::uuid)::text,true);
select set_config('test.d1',gen_random_uuid()::text,true);
select save_inspection_draft(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.bag')::uuid,current_setting('test.d1')::uuid,0,'Jacket','Jackets','Good');
select set_config('test.i1',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.i1')::uuid,'inspection_draft',current_setting('test.d1')::uuid,1,20000);
select set_config('test.d2',gen_random_uuid()::text,true);
select save_inspection_draft(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.bag')::uuid,current_setting('test.d2')::uuid,0,'Coat','Coats','Good');
select set_config('test.i2',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.i2')::uuid,'inspection_draft',current_setting('test.d2')::uuid,1,30000);
select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','K-1',now()-interval '2 days','SEK',jsonb_build_array(jsonb_build_object('itemId',current_setting('test.i1'),'priceOre',20000)));
select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','K-2',now()-interval '40 days','SEK',jsonb_build_array(jsonb_build_object('itemId',current_setting('test.i2'),'priceOre',30000)));
select throws_ok($$select * from host_activity_overview()$$,'42501',null,'a store owner is not a host');
reset role;
select komisio_private.enable_billing('f0000000-0000-4000-8000-000000000502');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000502","role":"authenticated"}';
select is((select count(*) from host_activity_overview()),2::bigint,'every store listed');
select is((select members from host_activity_overview() where tenant_id=current_setting('test.tenant')::uuid),1,'one member');
select is((select sellers from host_activity_overview() where tenant_id=current_setting('test.tenant')::uuid),1,'one seller');
select is((select items from host_activity_overview() where tenant_id=current_setting('test.tenant')::uuid),2,'two items');
select is((select sales_30d from host_activity_overview() where tenant_id=current_setting('test.tenant')::uuid),1,'only the sale within thirty days');
select ok((select last_activity from host_activity_overview() where tenant_id=current_setting('test.tenant')::uuid) is not null,'last activity from the access log');
select is((select items from host_activity_overview() where tenant_id=current_setting('test.quiet')::uuid),0,'quiet store shows zeros');
set local role anon;
select throws_ok($$select * from host_activity_overview()$$,'42501',null,'anon refused');
select * from finish();
rollback;
