begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000951','io-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000952','io-readonly@example.test',now()),
 ('f0000000-0000-4000-8000-000000000953','io-outsider@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000951","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Items overview test','items-overview-test',gen_random_uuid())::text,true);
select set_config('test.s1',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Anna Andersson','anna@io.test','')::text,true);
select set_config('test.agreement',publish_seller_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),null,'Synthetic terms','Only a test','en',false)::text,true);
select record_agreement_evidence(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.s1')::uuid,current_setting('test.agreement')::uuid,'Signed paper');
select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),null,(current_store_policy(current_setting('test.tenant')::uuid)->'policy') || '{"vatModeConsignmentPrivate":"consignment_margin","vatModeStoreOwned":"store_full"}'::jsonb);
select set_config('test.bag',receive_bag_with_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.s1')::uuid,'',current_setting('test.agreement')::uuid)::text,true);
select set_config('test.d1',gen_random_uuid()::text,true);
select save_inspection_draft(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.bag')::uuid,current_setting('test.d1')::uuid,0,'Blue wool jacket','Jackets','Good');
select set_config('test.i1',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.i1')::uuid,'inspection_draft',current_setting('test.d1')::uuid,1,20000);
select set_config('test.d2',gen_random_uuid()::text,true);
select save_inspection_draft(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.bag')::uuid,current_setting('test.d2')::uuid,0,'Red coat','Coats','Good');
select set_config('test.i2',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.i2')::uuid,'inspection_draft',current_setting('test.d2')::uuid,1,30000);
select set_config('test.p',gen_random_uuid()::text,true);
select register_purchase(current_setting('test.tenant')::uuid,current_setting('test.p')::uuid,'Vintage lamp',15000,'Auction receipt 7',false);
select set_config('test.i3',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.i3')::uuid,'purchase',current_setting('test.p')::uuid,null,25000);
select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','K-1','2026-09-10T10:00:00Z','SEK',jsonb_build_array(jsonb_build_object('itemId',current_setting('test.i1'),'priceOre',20000)));

select set_config('test.o',items_overview(current_setting('test.tenant')::uuid,null,null,50)::text,true);
select is((current_setting('test.o')::jsonb->>'total')::int,3,'every accepted item counted');
select is(jsonb_array_length(current_setting('test.o')::jsonb->'items'),3,'every accepted item listed');
select is(current_setting('test.o')::jsonb->>'currency','SEK','store currency');
create function pg_temp.ov(item text) returns jsonb language sql stable as $$ select e from jsonb_array_elements(current_setting('test.o')::jsonb->'items') e where e->>'id'=current_setting(item) $$;
select is(pg_temp.ov('test.i3')->>'title','Vintage lamp','purchase note as title');
select is(pg_temp.ov('test.i3')->>'originKind','purchase','origin kind');
select is(pg_temp.ov('test.i3')->>'ownership','store','store-owned');
select is(pg_temp.ov('test.i3')->>'stage','on_sale','unsold purchase on sale');
select is((pg_temp.ov('test.i3')->>'currentPriceOre')::bigint,25000::bigint,'current price in öre');
select is(pg_temp.ov('test.i3')->>'sellerId',null,'store-owned item has no seller');
select is(pg_temp.ov('test.i1')->>'title','Blue wool jacket','draft description as title');
select is(pg_temp.ov('test.i1')->>'category','Jackets','draft category');
select is(pg_temp.ov('test.i1')->>'stage','sold','sold item stage');
select is((pg_temp.ov('test.i1')->>'soldAt')::timestamptz,'2026-09-10T10:00:00Z'::timestamptz,'sold at the sale time');
select is(pg_temp.ov('test.i1')->>'sellerId',current_setting('test.s1'),'seller id, no name');
select is(pg_temp.ov('test.i2')->>'soldAt',null,'unsold item has no sale time');
select ok((pg_temp.ov('test.i2')->>'periodEnd')::timestamptz>now(),'period end lies ahead');
select is((items_overview(current_setting('test.tenant')::uuid,'WOOL',null,50)->>'total')::int,1,'text in the title, case-insensitive');
select is((items_overview(current_setting('test.tenant')::uuid,'coats',null,50)->>'total')::int,1,'text in the category');
select is((items_overview(current_setting('test.tenant')::uuid,'%',null,50)->>'total')::int,0,'wildcards are literal');
select is((items_overview(current_setting('test.tenant')::uuid,'_',null,50)->>'total')::int,0,'underscore is literal');
select is((items_overview(current_setting('test.tenant')::uuid,null,'sold',50)->>'total')::int,1,'stage filter: sold');
select is((items_overview(current_setting('test.tenant')::uuid,null,'on_sale',50)->>'total')::int,2,'stage filter: on sale');
select is((items_overview(current_setting('test.tenant')::uuid,null,null,1)->>'limit')::int,1,'limit honoured');
select is(jsonb_array_length(items_overview(current_setting('test.tenant')::uuid,null,null,1)->'items'),1,'one row under the limit');
select is((items_overview(current_setting('test.tenant')::uuid,null,null,1)->>'total')::int,3,'total counts beyond the limit');
select throws_ok($$select items_overview(current_setting('test.tenant')::uuid,null,'listed',50)$$,'INVALID_INPUT','unknown stage refused');
select throws_ok($$select items_overview(current_setting('test.tenant')::uuid,repeat('x',121),null,50)$$,'INVALID_INPUT','overlong query refused');
select ok(items_overview(current_setting('test.tenant')::uuid,null,null,50)::text not like '%Anna%','no seller names');
reset role;
insert into tenant_members(tenant_id,user_id,role) values (current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000000952','readonly');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000952","role":"authenticated"}';
select lives_ok($$select items_overview(current_setting('test.tenant')::uuid,null,null,50)$$,'read-only members read the list');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000953","role":"authenticated"}';
select throws_ok($$select items_overview(current_setting('test.tenant')::uuid,null,null,50)$$,'42501',null,'outsider refused');
select * from finish();
