begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000961','ch-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000962','ch-admin@example.test',now()),
 ('f0000000-0000-4000-8000-000000000963','ch-other@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000961","role":"authenticated"}';
select set_config('test.a',create_tenant('Chain store A','chain-store-a',gen_random_uuid())::text,true);
select set_config('test.b',create_tenant('Chain store B','chain-store-b',gen_random_uuid())::text,true);
select set_config('test.c',create_tenant('Chain store C','chain-store-c',gen_random_uuid())::text,true);
-- A sale in store A so the chain total has something to sum.
select set_config('test.s1',register_seller(current_setting('test.a')::uuid,gen_random_uuid(),'Anna Andersson','anna@ch.test','')::text,true);
select set_config('test.agreement',publish_seller_agreement(current_setting('test.a')::uuid,gen_random_uuid(),null,'Synthetic terms','Only a test','en',false)::text,true);
select record_agreement_evidence(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.s1')::uuid,current_setting('test.agreement')::uuid,'Signed paper');
select publish_store_policy(current_setting('test.a')::uuid,gen_random_uuid(),null,(current_store_policy(current_setting('test.a')::uuid)->'policy') || '{"vatModeConsignmentPrivate":"consignment_margin","vatModeStoreOwned":"store_full"}'::jsonb);
select set_config('test.bag',receive_bag_with_agreement(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.s1')::uuid,'',current_setting('test.agreement')::uuid)::text,true);
select set_config('test.d1',gen_random_uuid()::text,true);
select save_inspection_draft(current_setting('test.a')::uuid,gen_random_uuid(),current_setting('test.bag')::uuid,current_setting('test.d1')::uuid,0,'Jacket','Jackets','Good');
select set_config('test.i1',gen_random_uuid()::text,true);
select accept_item(current_setting('test.a')::uuid,current_setting('test.i1')::uuid,'inspection_draft',current_setting('test.d1')::uuid,1,20000);
select record_sale(current_setting('test.a')::uuid,gen_random_uuid(),'manual','K-1','2026-09-10T10:00:00Z','SEK',jsonb_build_array(jsonb_build_object('itemId',current_setting('test.i1'),'priceOre',20000)));

select is(chain_overview(current_setting('test.a')::uuid),null,'no chain yet');
select set_config('test.chain',gen_random_uuid()::text,true);
select throws_ok($$select create_chain(current_setting('test.chain')::uuid,' ',array[current_setting('test.a')::uuid])$$,'INVALID_INPUT','blank name refused');
select throws_ok($$select create_chain(current_setting('test.chain')::uuid,'Dup',array[current_setting('test.a')::uuid,current_setting('test.a')::uuid])$$,'INVALID_INPUT','duplicate store refused');
select is(create_chain(current_setting('test.chain')::uuid,'Second Life AB',array[current_setting('test.a')::uuid,current_setting('test.b')::uuid]),current_setting('test.chain')::uuid,'chain created from two owned stores');
select is(create_chain(current_setting('test.chain')::uuid,'Second Life AB',array[current_setting('test.a')::uuid]),current_setting('test.chain')::uuid,'replay by id returns the chain');
select is(chain_overview(current_setting('test.a')::uuid)->>'name','Second Life AB','overview names the chain');
select is(jsonb_array_length(chain_overview(current_setting('test.a')::uuid)->'stores'),2,'two stores in the chain');
select is(chain_overview(current_setting('test.b')::uuid)->'stores'->0->>'role','owner','caller role per store');
select throws_ok($$select create_chain(gen_random_uuid(),'Another',array[current_setting('test.a')::uuid])$$,'CHAIN_CONFLICT','a store cannot be in two chains');
select throws_ok($$select join_chain(gen_random_uuid(),current_setting('test.c')::uuid)$$,'CHAIN_NOT_FOUND','unknown chain refused');
select lives_ok($$select join_chain(current_setting('test.chain')::uuid,current_setting('test.c')::uuid)$$,'owner adds a third store');
select is(jsonb_array_length(chain_overview(current_setting('test.c')::uuid)->'stores'),3,'three stores');
select throws_ok($$update tenants set chain_id=null where id=current_setting('test.c')::uuid$$,'42501',null,'direct update of the chain label is refused');
select set_config('test.sum',chain_economy_summary(current_setting('test.chain')::uuid,'2026-09-01','2026-09-30')::text,true);
select is((current_setting('test.sum')::jsonb->>'storeCount')::int,3,'summary covers every store');
select is(current_setting('test.sum')::jsonb->>'currency','SEK','one currency across the chain');
select is((current_setting('test.sum')::jsonb->>'mixedCurrencies')::boolean,false,'no mixed currencies');
select is((current_setting('test.sum')::jsonb->'total'->>'grossOre')::bigint,20000::bigint,'total gross is the sum of the stores');
select is((current_setting('test.sum')::jsonb->'total'->>'salesCount')::int,1,'total sales count');
select ok((current_setting('test.sum')::jsonb->'total'->>'owedOre')::bigint>0,'total liability summed');
select is((select count(*) from jsonb_array_elements(current_setting('test.sum')::jsonb->'stores') e where (e->'totals'->>'grossOre')::bigint=20000),1::bigint,'the selling store carries the gross');
select throws_ok($$select chain_economy_summary(current_setting('test.chain')::uuid,'2026-09-30','2026-09-01')$$,'INVALID_INPUT','period validated by economy_summary');
select lives_ok($$select leave_chain(current_setting('test.c')::uuid)$$,'owner takes a store out');
select is(chain_overview(current_setting('test.c')::uuid),null,'store C has no chain');
select is(jsonb_array_length(chain_overview(current_setting('test.a')::uuid)->'stores'),2,'two stores remain');
reset role;
insert into tenant_members(tenant_id,user_id,role) values (current_setting('test.a')::uuid,'f0000000-0000-4000-8000-000000000962','admin');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000962","role":"authenticated"}';
select is(chain_overview(current_setting('test.a')::uuid)->>'name','Second Life AB','admin in one store sees the chain');
select is((select e->>'role' from jsonb_array_elements(chain_overview(current_setting('test.a')::uuid)->'stores') e where e->>'id'=current_setting('test.b')),null,'no role in the other store');
select throws_ok($$select chain_economy_summary(current_setting('test.chain')::uuid,'2026-09-01','2026-09-30')$$,'42501',null,'admin in only one store cannot read the chain summary');
select throws_ok($$select join_chain(current_setting('test.chain')::uuid,current_setting('test.c')::uuid)$$,'42501',null,'admin cannot add a store');
select throws_ok($$select leave_chain(current_setting('test.a')::uuid)$$,'42501',null,'admin cannot take a store out');
reset role;
insert into tenant_members(tenant_id,user_id,role) values (current_setting('test.b')::uuid,'f0000000-0000-4000-8000-000000000962','admin');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000962","role":"authenticated"}';
select lives_ok($$select chain_economy_summary(current_setting('test.chain')::uuid,'2026-09-01','2026-09-30')$$,'admin in every store reads the chain summary');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000963","role":"authenticated"}';
select is((select count(*) from chains where id=current_setting('test.chain')::uuid),0::bigint,'outsider cannot see the chain');
select throws_ok($$select chain_overview(current_setting('test.a')::uuid)$$,'42501',null,'outsider refused');
select throws_ok($$select chain_economy_summary(current_setting('test.chain')::uuid,'2026-09-01','2026-09-30')$$,'42501',null,'outsider cannot read the summary');
select * from finish();
