begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000981','sr-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000982','sr-outsider@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000981","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Stock report test','stock-report-test',gen_random_uuid())::text,true);
select set_config('test.s1',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Anna Andersson','anna@sr.test','')::text,true);
select set_config('test.agreement',publish_seller_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),null,'Synthetic terms','Only a test','en',false)::text,true);
select record_agreement_evidence(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.s1')::uuid,current_setting('test.agreement')::uuid,'Signed paper');
select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),null,(current_store_policy(current_setting('test.tenant')::uuid)->'policy') || '{"vatModeConsignmentPrivate":"consignment_margin","vatModeStoreOwned":"store_full"}'::jsonb);
select set_config('test.bag',receive_bag_with_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.s1')::uuid,'',current_setting('test.agreement')::uuid)::text,true);
-- Two jackets: one sells in the period, one stays in stock. One coat stays. One store-owned lamp sells.
select set_config('test.d1',gen_random_uuid()::text,true);
select save_inspection_draft(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.bag')::uuid,current_setting('test.d1')::uuid,0,'Blue wool jacket','Jackets','Good');
select set_config('test.i1',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.i1')::uuid,'inspection_draft',current_setting('test.d1')::uuid,1,20000);
select set_config('test.d2',gen_random_uuid()::text,true);
select save_inspection_draft(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.bag')::uuid,current_setting('test.d2')::uuid,0,'Green jacket','Jackets','Good');
select set_config('test.i2',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.i2')::uuid,'inspection_draft',current_setting('test.d2')::uuid,1,30000);
select set_config('test.d3',gen_random_uuid()::text,true);
select save_inspection_draft(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.bag')::uuid,current_setting('test.d3')::uuid,0,'Red coat','Coats','Good');
select set_config('test.i3',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.i3')::uuid,'inspection_draft',current_setting('test.d3')::uuid,1,40000);
select set_config('test.p',gen_random_uuid()::text,true);
select register_purchase(current_setting('test.tenant')::uuid,current_setting('test.p')::uuid,'Vintage lamp',10000,'Auction receipt 7',false);
select set_config('test.i4',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.i4')::uuid,'purchase',current_setting('test.p')::uuid,null,25000);
select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','K-1','2026-09-10T10:00:00Z','SEK',jsonb_build_array(jsonb_build_object('itemId',current_setting('test.i1'),'priceOre',20000),jsonb_build_object('itemId',current_setting('test.i4'),'priceOre',25000)));

select set_config('test.r',stock_report(current_setting('test.tenant')::uuid,'2026-09-01','2026-09-30')::text,true);
select is(current_setting('test.r')::jsonb->>'currency','SEK','store currency');
select is((current_setting('test.r')::jsonb->'total'->>'inStock')::int,2,'two items in stock');
select is((current_setting('test.r')::jsonb->'total'->>'stockValueOre')::bigint,70000::bigint,'stock valued at current prices');
select is((current_setting('test.r')::jsonb->'total'->>'soldCount')::int,2,'two sold in the period');
select is((current_setting('test.r')::jsonb->'total'->>'soldGrossOre')::bigint,45000::bigint,'gross of the sold lines');
select is((current_setting('test.r')::jsonb->'total'->'ageBuckets'->>'d0to14')::int,2,'fresh stock in the first bucket');
select is((current_setting('test.r')::jsonb->'total'->>'sellThroughPercent')::numeric,50.0,'sell-through: 2 sold of 4');
create function pg_temp.cat(name text) returns jsonb language sql stable as $$ select e from jsonb_array_elements(current_setting('test.r')::jsonb->'categories') e where e->>'category'=name $$;
select is((pg_temp.cat('Jackets')->>'inStock')::int,1,'one jacket in stock');
select is((pg_temp.cat('Jackets')->>'soldCount')::int,1,'one jacket sold');
select is((pg_temp.cat('Jackets')->>'soldGrossOre')::bigint,20000::bigint,'jacket gross');
select is((pg_temp.cat('Jackets')->>'marginOre')::bigint,(select commission_ore from sale_lines where item_id=current_setting('test.i1')::uuid),'consignment margin is the commission');
select is((pg_temp.cat('Jackets')->>'sellThroughPercent')::numeric,50.0,'jacket sell-through');
select is((pg_temp.cat('Coats')->>'inStock')::int,1,'coat in stock');
select is(pg_temp.cat('Coats')->>'sellThroughPercent','0.0','coat sell-through zero');
select is(pg_temp.cat('Coats')->>'marginPercent',null,'no margin without sales');
select is((pg_temp.cat('')->>'soldCount')::int,1,'store-owned lamp without category sold');
select is((pg_temp.cat('')->>'marginOre')::bigint,25000-(select vat_ore from sale_lines where item_id=current_setting('test.i4')::uuid)-10000,'store-owned margin is price minus VAT minus purchase price');
select is((select count(*) from jsonb_array_elements(current_setting('test.r')::jsonb->'categories')),3::bigint,'three categories');
select is((stock_report(current_setting('test.tenant')::uuid,'2026-10-01','2026-10-31')->'total'->>'soldCount')::int,0,'nothing sold outside the period');
select is((stock_report(current_setting('test.tenant')::uuid,'2026-10-01','2026-10-31')->'total'->>'inStock')::int,2,'stock is as of now, not the period');
select throws_ok($$select stock_report(current_setting('test.tenant')::uuid,'2026-09-30','2026-09-01')$$,'INVALID_INPUT','reversed period refused');
select throws_ok($$select stock_report(current_setting('test.tenant')::uuid,'2025-01-01','2026-09-30')$$,'INVALID_INPUT','period over a year refused');
select ok(current_setting('test.r')::text not like '%Anna%','no seller names');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000982","role":"authenticated"}';
select throws_ok($$select stock_report(current_setting('test.tenant')::uuid,'2026-09-01','2026-09-30')$$,'42501',null,'outsider refused');
select * from finish();
