begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000991','shopify-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000992','shopify-staff@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000991","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Shopify test','shopify-test',gen_random_uuid())::text,true);
select set_config('test.cipher','{"iv":"aWl2","tag":"dGFn","data":"ZGF0YQ=="}',true);
select is((shopify_connection_status(current_setting('test.tenant')::uuid)->>'connected')::boolean,false,'not connected yet');
select is(read_shopify_connection(current_setting('test.tenant')::uuid),null,'no ciphertext to read');
select throws_like($$select store_shopify_connection(current_setting('test.tenant')::uuid,'evil.com','Komisio Test','SEK',current_setting('test.cipher')::jsonb,'read_orders',null)$$,'%INVALID_INPUT%','only myshopify hosts');
select throws_like($$select store_shopify_connection(current_setting('test.tenant')::uuid,'komisio-test.myshopify.com','Komisio Test','SEK','{"iv":"x"}'::jsonb,'read_orders',null)$$,'%INVALID_INPUT%','ciphertext must be sealed');
select is((store_shopify_connection(current_setting('test.tenant')::uuid,'Komisio-Test.myshopify.com','Komisio Test','sek',current_setting('test.cipher')::jsonb,'read_orders,write_products',now()+interval '1 day')->>'replaced')::boolean,false,'first connection stored');
select is(shopify_connection_status(current_setting('test.tenant')::uuid)->>'shopDomain','komisio-test.myshopify.com','domain normalised to lower case');
select is(shopify_connection_status(current_setting('test.tenant')::uuid)->>'currency','SEK','currency upper-cased');
select is(shopify_connection_status(current_setting('test.tenant')::uuid)->'cipher',null,'status never carries the ciphertext');
select is(read_shopify_connection(current_setting('test.tenant')::uuid)->'cipher'->>'data','ZGF0YQ==','the server read returns the ciphertext');
select is((select kind from shopify_connection_events where tenant_id=current_setting('test.tenant')::uuid order by occurred_at limit 1),'connected','connection event recorded');
select is((store_shopify_connection(current_setting('test.tenant')::uuid,'komisio-test.myshopify.com','Komisio Test','SEK','{"iv":"aWl2","tag":"dGFn","data":"bmV3"}'::jsonb,'read_orders',null)->>'replaced')::boolean,true,'reconnect replaces the token');
select is(read_shopify_connection(current_setting('test.tenant')::uuid)->'cipher'->>'data','bmV3','new ciphertext stored');
select throws_like($$select store_shopify_connection(current_setting('test.tenant')::uuid,'other.myshopify.com','Other','SEK',current_setting('test.cipher')::jsonb,'',null)$$,'%SHOPIFY_WRONG_SHOP%','another shop is refused');
select throws_ok($$update shopify_connections set shop_name='x' where tenant_id=current_setting('test.tenant')::uuid$$,'42501',null,'no direct update');
select record_shopify_check(current_setting('test.tenant')::uuid,'checked','{"shop_domain":"komisio-test.myshopify.com"}'::jsonb);
select throws_like($$select record_shopify_check(current_setting('test.tenant')::uuid,'connected','{}'::jsonb)$$,'%INVALID_INPUT%','only check and refusal events from the application');
select is(jsonb_array_length(shopify_connection_status(current_setting('test.tenant')::uuid)->'events'),3,'events listed');
reset role;
insert into tenant_members(tenant_id,user_id,role) values (current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000000992','staff');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000992","role":"authenticated"}';
select is((shopify_connection_status(current_setting('test.tenant')::uuid)->>'connected')::boolean,true,'staff see that a shop is connected');
select throws_ok($$select read_shopify_connection(current_setting('test.tenant')::uuid)$$,'42501',null,'staff cannot read the ciphertext');
select throws_ok($$select disconnect_shopify(current_setting('test.tenant')::uuid)$$,'42501',null,'staff cannot disconnect');
select throws_ok($$select count(*) from shopify_connections$$,'42501',null,'the connection table is not selectable directly');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000991","role":"authenticated"}';
select is(disconnect_shopify(current_setting('test.tenant')::uuid),true,'owner disconnects');
select is(read_shopify_connection(current_setting('test.tenant')::uuid),null,'ciphertext removed');
select is((select count(*) from shopify_connection_events where tenant_id=current_setting('test.tenant')::uuid and kind='disconnected'),1::bigint,'disconnection recorded');
select * from finish();
