begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000997','shopify-cron-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000998','shopify-cron-worker@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000997","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Shopify cron','shopify-cron-test',gen_random_uuid())::text,true);
select set_config('test.purchase',register_purchase(current_setting('test.tenant')::uuid,gen_random_uuid(),'Synthetic',1000,'Test',true)::text,true);
select set_config('test.item',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.item')::uuid,'purchase',current_setting('test.purchase')::uuid,null,2500);
select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),null,(current_store_policy(current_setting('test.tenant')::uuid)->'policy') || '{"vatModeStoreOwned":"store_full"}');
select throws_like($$select enable_automation(current_setting('test.tenant')::uuid,gen_random_uuid(),'shopify_push','shopify-cron-worker@example.test')$$,'%INVALID_INPUT%','unknown scopes are refused');
select enable_automation(current_setting('test.tenant')::uuid,gen_random_uuid(),'shopify_pull','shopify-cron-worker@example.test');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000998","role":"authenticated"}';
select accept_automation_grants();
select is(shopify_automation_tenants(),'[]'::jsonb,'a store without a shop is not scheduled');
select throws_like($$select prepare_shopify_automatic_pull(current_setting('test.tenant')::uuid)$$,'%SHOPIFY_NOT_CONNECTED%','no run without a connection');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000997","role":"authenticated"}';
select store_shopify_connection(current_setting('test.tenant')::uuid,'komisio-test.myshopify.com','Komisio Test','SEK','{"iv":"aWl2","tag":"dGFn","data":"ZGF0YQ=="}'::jsonb,'read_orders',now()+interval '1 hour');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000998","role":"authenticated"}';
select is(jsonb_array_length(shopify_automation_tenants()),1,'connected store with an accepted grant is scheduled');
select set_config('test.job',prepare_shopify_automatic_pull(current_setting('test.tenant')::uuid)::text,true);
select ok((current_setting('test.job')::jsonb->>'id') is not null,'a run is reserved');
select matches(current_setting('test.job')::jsonb->>'cursor','^[0-9]{4}-','the run carries the watermark');
select is(prepare_shopify_automatic_pull(current_setting('test.tenant')::uuid),null::jsonb,'duplicate delivery reserves nothing');
select throws_ok($$select prepare_shopify_automatic_pull(gen_random_uuid())$$,'42501',null,'another tenant is denied');
select lives_ok($$select read_shopify_connection(current_setting('test.tenant')::uuid)$$,'the scope opens the sealed connection');
select is(shopify_order_cursor(current_setting('test.tenant')::uuid),current_setting('test.job')::jsonb->>'cursor','the scope opens the watermark');
select throws_ok($$select prepare_shopify_product(current_setting('test.tenant')::uuid,current_setting('test.item')::uuid)$$,'42501',null,'automation cannot export products');
select throws_ok($$select record_shopify_check(current_setting('test.tenant')::uuid,'checked','{}'::jsonb)$$,'42501',null,'automation cannot record checks');
select throws_ok($$select disconnect_shopify(current_setting('test.tenant')::uuid)$$,'42501',null,'automation cannot disconnect');
select throws_ok($$select reconcile_shopify_order(current_setting('test.tenant')::uuid,gen_random_uuid())$$,'42501',null,'automation cannot retry orders');
select throws_ok($$select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'shopify','x',now(),'SEK','[]','{}')$$,'42501',null,'automation cannot record arbitrary sales');
select throws_like($$select finish_shopify_automatic_pull(current_setting('test.tenant')::uuid,(current_setting('test.job')::jsonb->>'id')::uuid,'received')$$,'%REQUEST_CONFLICT%','an outcome must match what was recorded');
select lives_ok($$select record_shopify_order_page(current_setting('test.tenant')::uuid,(current_setting('test.job')::jsonb->>'id')::uuid,current_setting('test.job')::jsonb->>'cursor','2026-09-15T12:00:00Z',jsonb_build_array(jsonb_build_object('orderGid','gid://shopify/Order/104','name','#104','occurredAt',now()-interval '1 hour','updatedAt',now()-interval '1 hour','currency','SEK','amountOre',2500,'financialStatus','PAID','test',false,'cancelled',false,'lines',jsonb_build_array(jsonb_build_object('lineNo',1,'sku','K-'||current_setting('test.item'),'description','Jacket','quantity',1,'priceOre',2500)))))$$,'the scope records a page');
select lives_ok($$select finish_shopify_automatic_pull(current_setting('test.tenant')::uuid,(current_setting('test.job')::jsonb->>'id')::uuid,'received')$$,'matching outcome recorded');
select throws_like($$select finish_shopify_automatic_pull(current_setting('test.tenant')::uuid,(current_setting('test.job')::jsonb->>'id')::uuid,'secret provider body')$$,'%INVALID_INPUT%','raw provider errors cannot enter audit');
reset role;
select is((select count(*) from sales where tenant_id=current_setting('test.tenant')::uuid and provider='shopify'),1::bigint,'the matched order became one sale');
select is((select recorded_by from sales where tenant_id=current_setting('test.tenant')::uuid and provider='shopify'),'f0000000-0000-4000-8000-000000000998'::uuid,'the sale names the automation identity');
select is((select created_by from shopify_order_pulls where id=(current_setting('test.job')::jsonb->>'id')::uuid),'f0000000-0000-4000-8000-000000000998'::uuid,'the page names the automation identity');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000997","role":"authenticated"}';
select is(shopify_automatic_pull_status(current_setting('test.tenant')::uuid)->>'outcome','received','owner sees the last outcome');
select is((shopify_automatic_pull_status(current_setting('test.tenant')::uuid)->>'received')::int,1,'owner sees the count');
select disable_automation(current_setting('test.tenant')::uuid,'shopify_pull');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000998","role":"authenticated"}';
select is(shopify_automation_tenants(),'[]'::jsonb,'a disabled grant is not scheduled');
select throws_ok($$select read_shopify_connection(current_setting('test.tenant')::uuid)$$,'42501',null,'revocation closes the connection read');
select throws_ok($$select record_shopify_order_page(current_setting('test.tenant')::uuid,gen_random_uuid(),'2026-09-15T12:00:00Z','2026-09-15T12:00:00Z','[]'::jsonb)$$,'42501',null,'revocation denies recording');
select * from finish();
rollback;
