begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values ('b0000000-0000-4000-8000-000000009951','directory@example.test',now()),('b0000000-0000-4000-8000-000000009952','directory-other@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"b0000000-0000-4000-8000-000000009951","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Directory test','directory-test',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Anna Test','anna@example.test','070-123 45 67')::text,true);
select save_seller_profile(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,0,'{"name":"Anna Test","email":"anna@example.test","phone":"070-123 45 67","addressLine1":"Testgatan 12","addressLine2":"","postalCode":"12345","city":"Teststad","country":"SE","language":"sv","notes":"private note"}');
select is((sellers_overview(current_setting('test.tenant')::uuid,'anna',50)->>'total')::int,1,'finds anna');
select is((sellers_overview(current_setting('test.tenant')::uuid,'ANNA@EXAMPLE',50)->>'total')::int,1,'finds ANNA@EXAMPLE');
select is((sellers_overview(current_setting('test.tenant')::uuid,'0701234567',50)->>'total')::int,1,'finds 0701234567');
select is((sellers_overview(current_setting('test.tenant')::uuid,'123 45 67',50)->>'total')::int,1,'finds 123 45 67');
select is((sellers_overview(current_setting('test.tenant')::uuid,'Testgatan',50)->>'total')::int,1,'finds Testgatan');
select is((sellers_overview(current_setting('test.tenant')::uuid,'12345',50)->>'total')::int,1,'finds 12345');
select is((sellers_overview(current_setting('test.tenant')::uuid,'teststad',50)->>'total')::int,1,'finds teststad');
select is((sellers_overview(current_setting('test.tenant')::uuid,'%',50)->>'total')::int,0,'does not match %');
select is((sellers_overview(current_setting('test.tenant')::uuid,'_',50)->>'total')::int,0,'does not match _');
select is((sellers_overview(current_setting('test.tenant')::uuid,'private note',50)->>'total')::int,0,'does not match private note');
select is((sellers_overview(current_setting('test.tenant')::uuid,'nobody',50)->>'total')::int,0,'does not match nobody');
select is(sellers_overview(current_setting('test.tenant')::uuid,'',50)->'sellers'->0->>'phone','070-123 45 67','returns phone alongside email');
set local "request.jwt.claims"='{"sub":"b0000000-0000-4000-8000-000000009952","role":"authenticated"}';
select throws_like($$select sellers_overview(current_setting('test.tenant')::uuid,'Anna',50)$$,'%FORBIDDEN%','other tenant forbidden');
select * from finish();
rollback;
