begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000926','profile-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000927','profile-reader@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000926","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Profiles','seller-profiles-test',gen_random_uuid())::text,true);
select set_config('test.other',create_tenant('Other','seller-profiles-other',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Original seller','original@example.test','')::text,true);
select set_config('test.profile','{"name":"Changed seller","email":"new@example.test","phone":"0700000000","addressLine1":"Test Street 1","addressLine2":"","postalCode":"12345","city":"Test City","country":"Sweden","language":"en","notes":"Call before pickup"}',true);
select set_config('test.request',gen_random_uuid()::text,true);
select set_config('test.statement',issue_statement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'2020-01-01','2020-02-01',null)::text,true);
select is(save_seller_profile(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.seller')::uuid,0,current_setting('test.profile')::jsonb),current_setting('test.request')::uuid,'profile saved');
select is((select name from sellers where id=current_setting('test.seller')::uuid),'Changed seller','current contact projection updated');
select is((select count(*)::int from seller_profile_versions where seller_id=current_setting('test.seller')::uuid),2,'original and correction retained');
select is((select profile->>'name' from seller_profile_versions where seller_id=current_setting('test.seller')::uuid and revision=0),'Original seller','original name retained');
select is(save_seller_profile(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.seller')::uuid,0,current_setting('test.profile')::jsonb),current_setting('test.request')::uuid,'exact retry is idempotent');
select throws_like($$select save_seller_profile(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.seller')::uuid,0,current_setting('test.profile')::jsonb||'{"name":"Different"}')$$,'%REQUEST_CONFLICT%','request cannot change content');
select throws_like($$select save_seller_profile(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,0,current_setting('test.profile')::jsonb)$$,'%PROFILE_CHANGED%','stale editor cannot overwrite');
select throws_like($$select save_seller_profile(current_setting('test.other')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,1,current_setting('test.profile')::jsonb)$$,'%SELLER_NOT_FOUND%','cross-store seller refused');
select throws_like($$select save_seller_profile(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,1,current_setting('test.profile')::jsonb||'{"email":"","phone":""}')$$,'%INVALID_INPUT%','contact remains required');
select throws_like($$select save_seller_profile(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,1,current_setting('test.profile')::jsonb||'{"notes":null}')$$,'%INVALID_INPUT%','nulls refused');
select throws_like($$select save_seller_profile(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,1,current_setting('test.profile')::jsonb||'{"ssn":"unexpected"}')$$,'%INVALID_INPUT%','unsupported personal fields refused');
select is(register_seller(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,'Original seller','original@example.test',''),current_setting('test.seller')::uuid,'registration replay still binds original input');
select is((select seller_contact->>'name' from settlement_statements where id=current_setting('test.statement')::uuid),'Original seller','issued statement retains original name');
select is(jsonb_array_length(seller_data_export(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)->'profileHistory'),2,'data export includes both profiles');
select throws_ok($$update sellers set name='Direct write' where id=current_setting('test.seller')::uuid$$,'42501',null,'direct profile projection writes denied');
select throws_ok($$delete from seller_profile_versions where seller_id=current_setting('test.seller')::uuid$$,'42501',null,'direct history deletion denied');
select is(legacy_statement_seller_contact(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)->>'name','Original seller','legacy statements resolve the original contact atomically');
select set_config('test.statement2',issue_statement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'2020-02-01','2020-03-01',null)::text,true);
select is((select seller_contact->>'language' from settlement_statements where id=current_setting('test.statement2')::uuid),'en','new statement captures seller language');
select is((select seller_contact->>'addressLine1' from settlement_statements where id=current_setting('test.statement2')::uuid),'Test Street 1','new statement captures current address');
select ok((select not(seller_contact ? 'notes') from settlement_statements where id=current_setting('test.statement2')::uuid),'internal note excluded from statement');
reset role;
select throws_ok($$update seller_profile_versions set profile=current_setting('test.profile')::jsonb where seller_id=current_setting('test.seller')::uuid$$,'55000',null,'history immutable even for owner connection');
insert into tenant_members(tenant_id,user_id,role) values(current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000000927','readonly');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000927","role":"authenticated"}';
select throws_ok($$select save_seller_profile(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,1,current_setting('test.profile')::jsonb)$$,'42501',null,'readonly cannot edit');
select is((select count(*)::int from seller_profile_versions where tenant_id=current_setting('test.other')::uuid),0,'other tenant history invisible');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000928","role":"authenticated"}';
select is((select count(*)::int from seller_profile_versions where tenant_id=current_setting('test.tenant')::uuid),0,'non-member cannot read internal notes or history');
select * from finish();
rollback;
