begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000901','guide-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000902','guide-other@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000901","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Guide test','guide-test',gen_random_uuid())::text,true);
select set_config('test.answers','{"intake":["bags"],"goods":["clothes"],"pricing":["store"],"period":["collect","donate"],"pos":["zettle"],"channels":["shop"]}',true);
select set_config('test.id',gen_random_uuid()::text,true);
select is(current_store_guide(current_setting('test.tenant')::uuid)->>'id',null,'empty guide');
select is(save_store_guide(current_setting('test.tenant')::uuid,current_setting('test.id')::uuid,null,current_setting('test.answers')::jsonb),current_setting('test.id')::uuid,'save');
select is(save_store_guide(current_setting('test.tenant')::uuid,current_setting('test.id')::uuid,null,current_setting('test.answers')::jsonb),current_setting('test.id')::uuid,'retry');
select is(current_store_guide(current_setting('test.tenant')::uuid)->'answers',current_setting('test.answers')::jsonb,'round trip codes');
select throws_like($$select save_store_guide(current_setting('test.tenant')::uuid,gen_random_uuid(),null,current_setting('test.answers')::jsonb)$$,'%GUIDE_CHANGED%','stale version');
select throws_like($$select save_store_guide(current_setting('test.tenant')::uuid,current_setting('test.id')::uuid,null,jsonb_set(current_setting('test.answers')::jsonb,'{pos}','["other"]'))$$,'%REQUEST_CONFLICT%','retry cannot change payload');
select throws_like($$select save_store_guide(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.id')::uuid,jsonb_set(current_setting('test.answers')::jsonb,'{pos}','["invented"]'))$$,'%INVALID_INPUT%','unknown code');
select throws_like($$select save_store_guide(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.id')::uuid,jsonb_set(current_setting('test.answers')::jsonb,'{period}','["later","collect"]'))$$,'%INVALID_INPUT%','undecided is exclusive');
select throws_like($$select save_store_guide(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.id')::uuid,jsonb_set(current_setting('test.answers')::jsonb,'{intake}','["owned"]'))$$,'%INVALID_INPUT%','hidden answers rejected');
select throws_ok($$insert into store_guide_versions(id,tenant_id,version,answers,created_by) values(gen_random_uuid(),current_setting('test.tenant')::uuid,2,current_setting('test.answers')::jsonb,auth.uid())$$,'42501',null,'direct write denied');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000902","role":"authenticated"}';
select is((select count(*) from store_guide_versions),0::bigint,'cross tenant RLS');
select throws_ok($$select current_store_guide(current_setting('test.tenant')::uuid)$$,'42501',null,'foreign read denied');
select throws_ok($$select save_store_guide(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.id')::uuid,current_setting('test.answers')::jsonb)$$,'42501',null,'foreign save denied');
reset role;
insert into tenant_members(tenant_id,user_id,role) values(current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000000902','staff');
set local role authenticated;
select is(current_store_guide(current_setting('test.tenant')::uuid)->>'id',current_setting('test.id'),'staff reads');
select throws_ok($$select save_store_guide(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.id')::uuid,current_setting('test.answers')::jsonb)$$,'42501',null,'staff save denied');
reset role;
update tenant_members set role='admin' where user_id='f0000000-0000-4000-8000-000000000902';
set local role authenticated;
select lives_ok($$select save_store_guide(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.id')::uuid,current_setting('test.answers')::jsonb)$$,'admin saves');
select is((current_store_guide(current_setting('test.tenant')::uuid)->>'version')::int,2,'second version');
set local role anon;
select throws_ok($$select current_store_guide(current_setting('test.tenant')::uuid)$$,'42501',null,'anonymous denied');
reset role;
select throws_ok($$delete from store_guide_versions where id=current_setting('test.id')::uuid$$,'55000',null,'immutable history');
update tenant_members set role='readonly' where user_id='f0000000-0000-4000-8000-000000000902';
set local role authenticated;
select is((current_store_guide(current_setting('test.tenant')::uuid)->>'version')::int,2,'readonly reads');
select throws_ok($$select save_store_guide(current_setting('test.tenant')::uuid,gen_random_uuid(),null,current_setting('test.answers')::jsonb)$$,'42501',null,'readonly cannot save');
reset role;
insert into auth.mfa_factors(id,user_id,factor_type,status,created_at,updated_at)
 values(gen_random_uuid(),'f0000000-0000-4000-8000-000000000901','totp','verified',now(),now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000901","role":"authenticated","aal":"aal1"}';
select is((select count(*) from store_guide_versions),0::bigint,'MFA challenge hides guide history');
select throws_like($$select save_store_guide(current_setting('test.tenant')::uuid,gen_random_uuid(),null,current_setting('test.answers')::jsonb)$$,'%AUTH_REQUIRED%','MFA challenge blocks saves');
reset role;
select * from finish();
rollback;
