begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values ('f1470000-0000-4000-8000-000000000001','shopify-channel-owner@example.test',now()),('f1470000-0000-4000-8000-000000000002','shopify-channel-staff@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f1470000-0000-4000-8000-000000000001","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Shopify channels','shopify-channels',gen_random_uuid())::text,true);
select store_shopify_connection(current_setting('test.tenant')::uuid,'channel-test.myshopify.com','Channel test','SEK','{"iv":"a","tag":"b","data":"c"}','read_orders',null);
select is(shopify_sync_settings(current_setting('test.tenant')::uuid)->'settings','null'::jsonb,'legacy connection has no explicit settings');
select set_config('test.settings','{"mode":"pos","locationId":"gid://shopify/Location/1","locationName":"Shop","webPublicationId":null,"posPublicationId":"gid://shopify/Publication/2"}',true);
select lives_ok($$select save_shopify_sync_settings(current_setting('test.tenant')::uuid,'channel-test.myshopify.com',0,current_setting('test.settings')::jsonb)$$,'owner saves selected POS location');
select throws_like($$select save_shopify_sync_settings(current_setting('test.tenant')::uuid,'channel-test.myshopify.com',0,current_setting('test.settings')::jsonb)$$,'%SHOPIFY_SETTINGS_CHANGED%','stale save refused');
select throws_like($$select save_shopify_sync_settings(current_setting('test.tenant')::uuid,'other.myshopify.com',1,current_setting('test.settings')::jsonb)$$,'%SHOPIFY_WRONG_SHOP%','foreign shop refused');
select throws_ok($$select shopify_sync_settings(gen_random_uuid())$$,'42501',null,'cross tenant refused');
reset role;
insert into tenant_members(tenant_id,user_id,role) values(current_setting('test.tenant')::uuid,'f1470000-0000-4000-8000-000000000002','staff');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f1470000-0000-4000-8000-000000000002","role":"authenticated"}';
select is(shopify_sync_settings(current_setting('test.tenant')::uuid)->'settings'->>'mode','pos','staff can read nonsecret settings');
select throws_ok($$select save_shopify_sync_settings(current_setting('test.tenant')::uuid,'channel-test.myshopify.com',1,current_setting('test.settings')::jsonb)$$,'42501',null,'staff cannot save');
set local "request.jwt.claims"='{"sub":"f1470000-0000-4000-8000-000000000001","role":"authenticated"}';
select throws_like($$select save_shopify_sync_settings(current_setting('test.tenant')::uuid,'channel-test.myshopify.com',1,current_setting('test.settings')::jsonb||'{"posPublicationId":null}')$$,'%INVALID_INPUT%','POS publication required');
select set_config('test.cursor',shopify_order_cursor(current_setting('test.tenant')::uuid),true);
select set_config('test.order',jsonb_build_object('orderGid','gid://shopify/Order/147','name','#147','occurredAt',now(),'updatedAt',now(),'currency','SEK','amountOre',10000,'financialStatus','PAID','test',false,'cancelled',false,'sourceName','web','retailLocationGid',null,'lines',jsonb_build_array(jsonb_build_object('lineNo',1,'sku',null,'description','Synthetic','quantity',1,'priceOre',10000)))::text,true);
select lives_ok($$select record_shopify_order_page(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.cursor'),current_setting('test.cursor'),jsonb_build_array(current_setting('test.order')::jsonb))$$,'web order stored as evidence');
select is((select hold_reason from shopify_orders where tenant_id=current_setting('test.tenant')::uuid),'channel','web sale held in POS mode');
select is((select source_name from shopify_orders where tenant_id=current_setting('test.tenant')::uuid),'web','channel retained');
select lives_ok($$select record_shopify_order_page(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.cursor'),current_setting('test.cursor'),jsonb_build_array(current_setting('test.order')::jsonb||'{"orderGid":"gid://shopify/Order/148","sourceName":"pos","retailLocationGid":"gid://shopify/Location/9"}'))$$,'other location stored');
select is((select hold_reason from shopify_orders where tenant_id=current_setting('test.tenant')::uuid and order_gid='gid://shopify/Order/148'),'location','other POS location held');
select lives_ok($$select record_shopify_order_page(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.cursor'),current_setting('test.cursor'),jsonb_build_array(current_setting('test.order')::jsonb||'{"orderGid":"gid://shopify/Order/149","sourceName":"pos","retailLocationGid":"gid://shopify/Location/1"}'))$$,'selected location stored');
select is((select hold_reason from shopify_orders where tenant_id=current_setting('test.tenant')::uuid and order_gid='gid://shopify/Order/149'),'unknown_sku','selected POS channel reaches normal SKU validation');
select is((select retail_location_gid from shopify_orders where tenant_id=current_setting('test.tenant')::uuid and order_gid='gid://shopify/Order/149'),'gid://shopify/Location/1','location retained');
select throws_like($$select save_shopify_sync_settings(current_setting('test.tenant')::uuid,'channel-test.myshopify.com',1,current_setting('test.settings')::jsonb)$$,'%SHOPIFY_SETTINGS_LOCKED%','cannot move stock or channel after sync starts');
-- A selected POS sale follows the existing sale rules, including its discounted total.
select set_config('test.purchase',register_purchase(current_setting('test.tenant')::uuid,gen_random_uuid(),'Synthetic source',1500,'Receipt',true)::text,true);
select set_config('test.item',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.item')::uuid,'purchase',current_setting('test.purchase')::uuid,null,12000);
select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),null,(current_store_policy(current_setting('test.tenant')::uuid)->'policy') || '{"vatModeStoreOwned":"store_full"}');
select set_config('test.export',prepare_shopify_product(current_setting('test.tenant')::uuid,current_setting('test.item')::uuid)::text,true);
select is((select payload->'syncSettings' from shopify_product_exports where id=current_setting('test.export')::uuid),current_setting('test.settings')::jsonb,'product intent snapshots selected channel and location');
select set_config('test.pos_order',(current_setting('test.order')::jsonb || jsonb_build_object('orderGid','gid://shopify/Order/150','sourceName','pos','retailLocationGid','gid://shopify/Location/1','lines',jsonb_build_array(jsonb_build_object('lineNo',1,'sku','K-'||current_setting('test.item'),'description','Synthetic','quantity',1,'priceOre',10000))))::text,true);
select lives_ok($$select record_shopify_order_page(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.cursor'),current_setting('test.cursor'),jsonb_build_array(current_setting('test.pos_order')::jsonb))$$,'matched POS checkout imported');
select is((select count(*) from sales where tenant_id=current_setting('test.tenant')::uuid and external_id='gid://shopify/Order/150'),1::bigint,'selected POS checkout becomes one sale');
select record_shopify_order_page(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.cursor'),current_setting('test.cursor'),jsonb_build_array(current_setting('test.pos_order')::jsonb));
select is((select count(*) from sales where tenant_id=current_setting('test.tenant')::uuid and external_id='gid://shopify/Order/150'),1::bigint,'POS replay cannot duplicate sale');
select disconnect_shopify(current_setting('test.tenant')::uuid);
select throws_like($$select store_shopify_connection(current_setting('test.tenant')::uuid,'different.myshopify.com','Different','SEK','{"iv":"a","tag":"b","data":"c"}','read_orders',null)$$,'%SHOPIFY_WRONG_SHOP%','disconnect cannot rebind configured stock to another shop');
-- Each mode is exercised in a fresh connection, before the first sync locks it.
select set_config('test.web_tenant',create_tenant('Shopify web','shopify-web-channels',gen_random_uuid())::text,true);
select store_shopify_connection(current_setting('test.web_tenant')::uuid,'web.myshopify.com','Web','SEK','{"iv":"a","tag":"b","data":"c"}','read_orders',null);
select save_shopify_sync_settings(current_setting('test.web_tenant')::uuid,'web.myshopify.com',0,current_setting('test.settings')::jsonb||'{"mode":"web","webPublicationId":"gid://shopify/Publication/1","posPublicationId":null}');
select record_shopify_order_page(current_setting('test.web_tenant')::uuid,gen_random_uuid(),shopify_order_cursor(current_setting('test.web_tenant')::uuid),shopify_order_cursor(current_setting('test.web_tenant')::uuid),jsonb_build_array(current_setting('test.order')::jsonb,current_setting('test.pos_order')::jsonb));
select is((select hold_reason from shopify_orders where tenant_id=current_setting('test.web_tenant')::uuid and source_name='web'),'unknown_sku','web mode allows online checkout through to SKU validation');
select is((select hold_reason from shopify_orders where tenant_id=current_setting('test.web_tenant')::uuid and source_name='pos'),'channel','web mode holds POS checkout');
select set_config('test.both_tenant',create_tenant('Shopify both','shopify-both-channels',gen_random_uuid())::text,true);
select store_shopify_connection(current_setting('test.both_tenant')::uuid,'both.myshopify.com','Both','SEK','{"iv":"a","tag":"b","data":"c"}','read_orders',null);
select save_shopify_sync_settings(current_setting('test.both_tenant')::uuid,'both.myshopify.com',0,current_setting('test.settings')::jsonb||'{"mode":"both","webPublicationId":"gid://shopify/Publication/1"}');
select record_shopify_order_page(current_setting('test.both_tenant')::uuid,gen_random_uuid(),shopify_order_cursor(current_setting('test.both_tenant')::uuid),shopify_order_cursor(current_setting('test.both_tenant')::uuid),jsonb_build_array(current_setting('test.order')::jsonb,current_setting('test.pos_order')::jsonb));
select is((select count(*) from shopify_orders where tenant_id=current_setting('test.both_tenant')::uuid and hold_reason in ('channel','location')),0::bigint,'both mode passes web and selected POS location to existing item checks');
select is((select hold_reason from shopify_orders where tenant_id=current_setting('test.both_tenant')::uuid and source_name='pos'),'missing_item','another tenant cannot sell the matched item');
select * from finish();
rollback;
