begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values ('f2490000-0000-4000-8000-000000000001','global-owner@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f2490000-0000-4000-8000-000000000001","role":"authenticated"}';
create function pg_temp.currency_flow(cur text) returns setof text language plpgsql as $$
declare seller uuid; agreement uuid; bag uuid; draft uuid:=gen_random_uuid(); payout uuid:=gen_random_uuid(); t uuid; req uuid:=gen_random_uuid(); p uuid; i uuid; exp uuid; r jsonb; cursor0 text; receipt uuid:=gen_random_uuid(); page uuid:=gen_random_uuid(); data jsonb;
begin
 t:=public.create_tenant_with_currency('Global synthetic','global-'||lower(cur),req,cur);
 return next is(public.store_currency(t),cur,'explicit initial currency '||cur);
 return next is(public.create_tenant_with_currency('Global synthetic','global-'||lower(cur),req,'SEK'),t,'creation replay preserves identity');
 return next is(public.store_currency(t),cur,'creation replay never overwrites currency');
 perform public.publish_store_policy(t,gen_random_uuid(),(public.current_store_policy(t)->>'id')::uuid,(public.current_store_policy(t)->'policy')||'{"vatModeStoreOwned":"store_full","vatModeConsignmentPrivate":"consignment_margin","minPayoutThreshold":1}');
 perform public.publish_zettle_catalog_config(t,gen_random_uuid(),null,'{"store_full":25,"consignment_margin":0}');
 p:=public.register_purchase(t,gen_random_uuid(),'Synthetic',1000,'Currency test',true);
 return next is((select currency from public.purchase_receipts where id=p),cur,'purchase uses '||cur);
 i:=gen_random_uuid();
 seller:=public.register_seller(t,gen_random_uuid(),'Synthetic seller','global-seller@example.test','');
 agreement:=public.publish_seller_agreement(t,gen_random_uuid(),null,'Synthetic terms','Only a test','en',false);
 perform public.record_agreement_evidence(t,gen_random_uuid(),seller,agreement,'Synthetic paper');
 bag:=public.receive_bag_with_agreement(t,gen_random_uuid(),seller,'',agreement);
 perform public.save_inspection_draft(t,gen_random_uuid(),bag,draft,0,'Synthetic jacket','Jackets','Good');
 perform public.accept_item(t,i,'inspection_draft',draft,1,2500);
 exp:=public.prepare_zettle_product(t,i);
 return next is((select payload->'variants'->0->'price'->>'currencyId' from public.zettle_product_exports where id=exp),cur,'PayPal POS export uses '||cur);
 data:=jsonb_build_array(jsonb_build_object('externalId',receipt,'occurredAt',now(),'currency',cur,'amountOre',2500,'blockedReason',null,'lines',jsonb_build_array(jsonb_build_object('lineNo',1,'reference','I-'||upper(left(i::text,8)),'labelConflict',false,'description','Synthetic','priceOre',2500))));
 perform public.record_zettle_page(t,page,null,'global-cursor',data);
 return next is((select count(*) from public.sales where tenant_id=t and provider='zettle' and currency=cur),1::bigint,'PayPal POS receipt records a '||cur||' sale');
 perform public.record_zettle_page(t,page,null,'global-cursor',data);
 return next is((select count(*) from public.sales where tenant_id=t and provider='zettle'),1::bigint,'PayPal POS replay is idempotent');
 perform public.request_payout(t,payout,seller,100);
 return next is((select currency from public.payouts where id=payout),cur,'payout uses '||cur);
 r:=public.store_shopify_connection(t,'global-test.myshopify.com','Synthetic','SEK','{"iv":"aWl2","tag":"dGFn","data":"ZGF0YQ=="}','read_orders',null);
 return next is(r->>'error','CURRENCY_MISMATCH','mismatched Shopify currency refused');
 return next is(public.shopify_connection_status(t)->>'connected','false','refusal creates no connection');
 return next is(public.shopify_connection_status(t)->'events'->0->>'kind','refused','refusal audit survives');
 perform public.store_shopify_connection(t,'global-test.myshopify.com','Synthetic',cur,'{"iv":"aWl2","tag":"dGFn","data":"ZGF0YQ=="}','read_orders',null);
 r:=public.store_shopify_connection(t,'global-test.myshopify.com','Synthetic','SEK','{"iv":"aWl2","tag":"dGFn","data":"ZGF0YQ=="}','read_orders',null);
 return next is(r->>'error','CURRENCY_MISMATCH','mismatched reconnection refused');
 return next is(public.shopify_connection_status(t)->>'currency',cur,'refused reconnection preserves existing connection');
 p:=public.register_purchase(t,gen_random_uuid(),'Synthetic',1000,'Currency test Shopify',true);
 i:=gen_random_uuid(); perform public.accept_item(t,i,'purchase',p,null,2500);
 cursor0:=public.shopify_order_cursor(t); page:=gen_random_uuid();
 data:=jsonb_build_array(jsonb_build_object('orderGid','gid://shopify/Order/249','name','#249','occurredAt',now(),'updatedAt',now(),'currency',cur,'amountOre',2500,'financialStatus','PAID','test',false,'cancelled',false,'lines',jsonb_build_array(jsonb_build_object('lineNo',1,'sku','K-'||i,'description','Synthetic','quantity',1,'priceOre',2500))));
 perform public.record_shopify_order_page(t,page,cursor0,cursor0,data);
 return next is((select count(*) from public.sales where tenant_id=t and provider='shopify' and currency=cur),1::bigint,'Shopify order records a '||cur||' sale');
 perform public.record_shopify_order_page(t,page,cursor0,cursor0,data);
 return next is((select count(*) from public.sales where tenant_id=t and provider='shopify'),1::bigint,'Shopify replay is idempotent');
 return next throws_like(format('select public.publish_store_policy(%L,gen_random_uuid(),%L,%L)',t,public.current_store_policy(t)->>'id',((public.current_store_policy(t)->'policy')||'{"currency":"SEK"}')::text),'%CURRENCY_FROZEN%','new currency still freezes after a money fact');
end $$;
select * from pg_temp.currency_flow('EUR');
select * from pg_temp.currency_flow('USD');
select throws_like($$select create_tenant_with_currency('Invalid','global-invalid',gen_random_uuid(),'JPY')$$,'%INVALID_INPUT%','unsupported currency refused');
select throws_like($$select create_tenant_with_currency('Invalid','global-null',gen_random_uuid(),null)$$,'%INVALID_INPUT%','null currency refused');
set local role anon;
select throws_ok($$select create_tenant_with_currency('Anonymous','global-anon',gen_random_uuid(),'USD')$$,'42501',null,'anonymous creation denied');
reset role;
select ok(komisio_private.valid_store_profile(jsonb_build_object('address',jsonb_build_object('street','','postalCode','','city','','country',country),'contact',jsonb_build_object('email','','phone','','website',''),'openingHours','[]'::jsonb,'accepts','','concept','','language','en')),'valid ISO profile country '||country) from (values ('US'),('CA'),('AU'),('BR'),('JP'),('ZA')) c(country);
select ok(komisio_private.valid_reception_review(jsonb_build_object('attributes','[{"slug":"description","definitionVersion":1,"value":"Synthetic jacket","sourceIds":["f2490000-0000-4000-8000-000000000099"],"certainty":"observed"}]'::jsonb,'price',jsonb_build_object('currency',cur,'amount','25.00','rationale','Synthetic test','sourceIds','["f2490000-0000-4000-8000-000000000099"]'::jsonb),'questions','[]'::jsonb)),'reception review accepts '||cur) from (values ('EUR'),('USD')) c(cur);
select * from finish();
rollback;
