begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values ('d1640000-0000-4000-8000-000000009901','handover-stage@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"d1640000-0000-4000-8000-000000009901","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Handover stage','handover-stage',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Synthetic seller','','123')::text,true);
select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),null,(current_store_policy(current_setting('test.tenant')::uuid)->'policy') || '{"vatModeConsignmentPrivate":"consignment_margin","vatModeStoreOwned":"store_full"}'::jsonb);
select set_config('test.bag',receive_bag_with_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'Synthetic',null)::text,true);
select set_config('test.draft',gen_random_uuid()::text,true);
select save_inspection_draft(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.bag')::uuid,current_setting('test.draft')::uuid,0,'Synthetic chair','','Good');
select set_config('test.item',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.item')::uuid,'inspection_draft',current_setting('test.draft')::uuid,1,20000);
select set_config('test.row',(bag_registered_items_page(current_setting('test.tenant')::uuid,current_setting('test.bag')::uuid,0)->'items'->0)::text,true);
select is(current_setting('test.row')::jsonb->>'stage','on_sale','fresh draft item is on sale');
select is(current_setting('test.row')::jsonb->>'sold_price_ore',null,'unsold item has no sale proceeds');
select set_config('test.sale',gen_random_uuid()::text,true);
select record_sale(current_setting('test.tenant')::uuid,current_setting('test.sale')::uuid,'manual','Synthetic-stage-sale',now(),'SEK',jsonb_build_array(jsonb_build_object('itemId',current_setting('test.item'),'priceOre',15000)));
select set_config('test.row',(bag_registered_items_page(current_setting('test.tenant')::uuid,current_setting('test.bag')::uuid,0)->'items'->0)::text,true);
select is(current_setting('test.row')::jsonb->>'stage','sold','active completed sale changes the stage');
select is(current_setting('test.row')::jsonb->>'sold_price_ore','15000','actual sale price is distinct from list price');
select is(current_setting('test.row')::jsonb->>'price_ore','20000','list price remains an independent fact');
select is(bag_registered_items_page(current_setting('test.tenant')::uuid,current_setting('test.bag')::uuid,0)->>'total','1','sold item stays in the handover history');
select record_return(current_setting('test.tenant')::uuid,gen_random_uuid(),(select id from sale_lines where tenant_id=current_setting('test.tenant')::uuid and sale_id=current_setting('test.sale')::uuid),15000,'Synthetic full return');
select set_config('test.row',(bag_registered_items_page(current_setting('test.tenant')::uuid,current_setting('test.bag')::uuid,0)->'items'->0)::text,true);
select is(current_setting('test.row')::jsonb->>'stage','on_sale','returned item follows the existing lifecycle');
select is(current_setting('test.row')::jsonb->>'sold_price_ore',null,'returned sale no longer supplies proceeds');
select set_config('test.resale',gen_random_uuid()::text,true);
select record_sale(current_setting('test.tenant')::uuid,current_setting('test.resale')::uuid,'manual','Synthetic-stage-resale',now(),'SEK',jsonb_build_array(jsonb_build_object('itemId',current_setting('test.item'),'priceOre',17000)));
select set_config('test.row',(bag_registered_items_page(current_setting('test.tenant')::uuid,current_setting('test.bag')::uuid,0)->'items'->0)::text,true);
select is(current_setting('test.row')::jsonb->>'stage','sold','resold item uses the active sale');
select is(current_setting('test.row')::jsonb->>'sold_price_ore','17000','resale price excludes the earlier returned line');
select record_return(current_setting('test.tenant')::uuid,gen_random_uuid(),(select id from sale_lines where tenant_id=current_setting('test.tenant')::uuid and sale_id=current_setting('test.resale')::uuid),17000,'Synthetic second return');
select end_sale_period(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.item')::uuid,'charity','Synthetic end');
select is(bag_registered_items_page(current_setting('test.tenant')::uuid,current_setting('test.bag')::uuid,0)->'items'->0->>'stage','ended','ended item remains visible with its engine stage');
select set_config('test.session',gen_random_uuid()::text,true);
select create_bag_reception(current_setting('test.tenant')::uuid,current_setting('test.session')::uuid,current_setting('test.seller')::uuid,current_setting('test.bag')::uuid);
select quick_receive_from_bag(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,current_setting('test.seller')::uuid,0,'{"description":"Synthetic quick item"}',12345,current_setting('test.bag')::uuid);
select is((select x->>'stage' from jsonb_array_elements(bag_registered_items_page(current_setting('test.tenant')::uuid,current_setting('test.bag')::uuid,0)->'items') x where x->>'session_id'=current_setting('test.session')),'on_sale','quick origin uses the same lifecycle');
select is(bag_registered_items_page(current_setting('test.tenant')::uuid,current_setting('test.bag')::uuid,0)->>'total',bag_work_summary(current_setting('test.tenant')::uuid,current_setting('test.bag')::uuid)->>'accepted','stages do not change accepted membership');
reset role;
select * from finish();
rollback;
