begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values ('d1660000-0000-4000-8000-000000009901','vocabulary-locales@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"d1660000-0000-4000-8000-000000009901","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Vocabulary languages','vocabulary-languages',gen_random_uuid())::text,true);
select set_config('test.vocabulary',attribute_vocabulary(current_setting('test.tenant')::uuid)::text,true);
select is(jsonb_array_length(current_setting('test.vocabulary')::jsonb->'definitions'),12,'all existing standard attributes remain available');
select is((select count(*) from jsonb_array_elements(current_setting('test.vocabulary')::jsonb->'definitions') d where not (d->'labels' ?& array['sv','en','no','dk','fi','de','es','it'])),0::bigint,'every standard attribute has all eight labels');
select is((select count(*) from jsonb_array_elements(current_setting('test.vocabulary')::jsonb->'definitions') d where d->'help'<>'{}'::jsonb and not (d->'help' ?& array['sv','en','no','dk','fi','de','es','it'])),0::bigint,'existing help text is translated into all eight languages');
select is((select count(*) from jsonb_array_elements(current_setting('test.vocabulary')::jsonb->'types') t where not (t->'labels' ?& array['sv','en','no','dk','fi','de','es','it'])),0::bigint,'standard item types have all eight labels');
select is((select count(*) from jsonb_array_elements(current_setting('test.vocabulary')::jsonb->'definitions') d cross join lateral jsonb_array_elements(d->'choices') c where not (c->'labels' ?& array['sv','en','no','dk','fi','de','es','it'])),0::bigint,'every current standard choice has all eight labels');
select is((select d->'labels'->>'de' from jsonb_array_elements(current_setting('test.vocabulary')::jsonb->'definitions') d where d->>'slug'='description'),'Beschreibung','German quick reception receives the real translated label');
select is((select count(*) from attribute_definitions where tenant_id is null and slug in ('fit','socket') and version=2),2::bigint,'translated choice labels use new definition versions');
select is((select count(*) from attribute_definitions where tenant_id is null and slug in ('fit','socket') and version=1),2::bigint,'both original choice definitions remain readable');
select is((select count(*) from attribute_definitions d cross join lateral jsonb_array_elements(d.choices) c where d.tenant_id is null and d.slug in ('fit','socket') and d.version=1 and c->'labels' ? 'de'),0::bigint,'historical choice label objects are not rewritten');
select is((select jsonb_object_agg(slug,values_without_labels) from (select d.slug,(select jsonb_agg(c.value-'labels' order by c.ordinality) from jsonb_array_elements(d.choices) with ordinality c) values_without_labels from attribute_definitions d where tenant_id is null and slug in ('fit','socket') and version=2) x),(select jsonb_object_agg(slug,values_without_labels) from (select d.slug,(select jsonb_agg(c.value-'labels' order by c.ordinality) from jsonb_array_elements(d.choices) with ordinality c) values_without_labels from attribute_definitions d where tenant_id is null and slug in ('fit','socket') and version=1) x),'choice ids, order and sort metadata stay identical');
select set_attribute_definition(current_setting('test.tenant')::uuid,'description','{"dataType":"text","labels":{"de":"Eigene Beschreibung","en":"Own description"}}');
select set_item_type(current_setting('test.tenant')::uuid,'lamp','{"labels":{"de":"Eigene Lampe"},"attributes":[{"slug":"description","expected":true,"sort":1}]}');
select is((select d->'labels'->>'de' from jsonb_array_elements(attribute_vocabulary(current_setting('test.tenant')::uuid)->'definitions') d where d->>'slug'='description'),'Eigene Beschreibung','tenant attribute labels still override the platform');
select is((select t->'labels'->>'de' from jsonb_array_elements(attribute_vocabulary(current_setting('test.tenant')::uuid)->'types') t where t->>'slug'='lamp'),'Eigene Lampe','tenant item type labels still override the platform');
reset role;
select throws_like($$update attribute_definitions set choices='[{"id":"other","labels":{"en":"Other"}}]' where tenant_id is null and slug='socket' and version=1$$,'%IMMUTABLE_DEFINITION%','historical choices remain immutable even to a privileged migration caller');
select * from finish();
rollback;
