begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values ('f0000000-0000-4000-8000-000000002501','item-language@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000002501","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Language fixture','item-language-fixture',gen_random_uuid())::text,true);
select set_config('test.body',(current_store_policy(current_setting('test.tenant')::uuid)->'policy')::text,true);
select is(coalesce(current_setting('test.body')::jsonb->>'itemLanguage','sv'),'sv','missing language retains Swedish');
select set_config('test.id',gen_random_uuid()::text,true);
select lives_ok($$select publish_store_policy(current_setting('test.tenant')::uuid,current_setting('test.id')::uuid,null,current_setting('test.body')::jsonb || '{"itemLanguage":"no"}')$$,'owner publishes Norwegian');
select is(current_store_policy(current_setting('test.tenant')::uuid)->'policy'->>'itemLanguage','no','shared store language is read back');
select throws_like($$select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.id')::uuid,current_setting('test.body')::jsonb || '{"itemLanguage":"xx"}')$$,'%INVALID_INPUT%','unsupported language rejected');
select throws_like($$select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.id')::uuid,current_setting('test.body')::jsonb || '{"itemLanguage":null}')$$,'%INVALID_INPUT%','null language rejected');
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Synthetic seller','','123')::text,true);
select set_config('test.session',gen_random_uuid()::text,true);
select set_config('test.request',gen_random_uuid()::text,true);
select create_reception_session(current_setting('test.tenant')::uuid,current_setting('test.session')::uuid,current_setting('test.seller')::uuid);
select save_reception_sources(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,0,
 '[{"id":"f0000000-0000-4000-8000-000000002509","kind":"observation","reference":"fixture","observation":"Shirt"}]');
select is(reserve_reception_assistance(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.session')::uuid,1,'fixture','reception-v5-no'),true,'localized prompt accepted');
select is(reserve_reception_assistance(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.session')::uuid,1,'fixture','reception-v5-no'),false,'localized replay never invokes twice');
select throws_like($$select reserve_reception_assistance(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.session')::uuid,1,'fixture','reception-v5-sv')$$,'%REQUEST_CONFLICT%','language is bound to attempt');
select throws_like($$select reserve_reception_assistance(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,1,'fixture','reception-v5-xx')$$,'%INVALID_INPUT%','invalid prompt language rejected');
select throws_like($$select reserve_reception_assistance(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,1,'fixture','reception-batch-v5-no')$$,'%ASSISTANCE_LIMIT%','batch language passes validation and retains quota');
reset role;
select ok(komisio_private.valid_store_policy(current_setting('test.body')::jsonb || jsonb_build_object('itemLanguage',lang)),lang || ' accepted') from unnest(array['sv','en','no','dk','fi','de','es','it']) lang;
select ok(komisio_private.valid_store_policy(current_setting('test.body')::jsonb || jsonb_build_object('itemLanguage','no','currency',code)),code || ' remains supported with language') from unnest(array['SEK','NOK','DKK','EUR','USD']) code;
select * from finish();
rollback;
