begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values('f0000000-0000-4000-8000-000000001903','agreement-credit@example.test',now());
insert into platform_hosts(user_id) values('f0000000-0000-4000-8000-000000001903');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000001903","role":"authenticated"}';
select set_ai_platform_settings('{"enabled":true,"monthlyCapOre":250,"includedOre":600,"packOre":10000,"reserveOre":50,"reserveBatchOre":200}');
select set_config('test.credit',create_tenant('Agreement credits','agreement-credits',gen_random_uuid())::text,true);
select set_config('test.cap',create_tenant('Agreement cap','agreement-cap',gen_random_uuid())::text,true);
select set_config('test.id',gen_random_uuid()::text,true);
select begin_agreement_assistance(current_setting('test.credit')::uuid,current_setting('test.id')::uuid,null,'sv','fixture');
select begin_agreement_assistance(current_setting('test.credit')::uuid,current_setting('test.id')::uuid,null,'sv','fixture');
select is((select count(*) from ai_credit_events where reference='attempt:'||current_setting('test.id') and kind='reserved'),1::bigint,'replay reserves credits once');
select is((select amount_ore from ai_credit_events where reference='attempt:'||current_setting('test.id') and kind='reserved'),-200::bigint,'configured batch reservation applies');
select throws_ok($$select begin_agreement_assistance(current_setting('test.cap')::uuid,gen_random_uuid(),null,'sv','fixture')$$,'P0001','AI_CAP_REACHED','shared deployment cap blocks new spend');
select is((select count(*) from agreement_ai_attempts where tenant_id=current_setting('test.cap')::uuid),0::bigint,'blocked spend leaves no attempt');
select complete_agreement_assistance(current_setting('test.credit')::uuid,current_setting('test.id')::uuid,null,0,0);
select complete_agreement_assistance(current_setting('test.credit')::uuid,current_setting('test.id')::uuid,null,0,0);
select is(begin_agreement_assistance(current_setting('test.credit')::uuid,current_setting('test.id')::uuid,null,'sv','fixture')->>'status','failed','failed provider result is terminal and replayable');
select is((select count(*) from pending_operations where id=current_setting('test.id')::uuid),0::bigint,'failed generation proposes nothing');
select publish_store_policy(current_setting('test.cap')::uuid,gen_random_uuid(),null,(current_store_policy(current_setting('test.cap')::uuid)->'policy')||'{"assistanceMonthlyQuota":0}');
select throws_ok($$select begin_agreement_assistance(current_setting('test.cap')::uuid,gen_random_uuid(),null,'sv','fixture')$$,'P0001','USAGE_QUOTA_EXCEEDED','ordinary assistance quota also applies');
select * from finish();
rollback;
