begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000000211','life-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000000212','life-reader@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000211","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Lifecycle test','lifecycle-test',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Synthetic seller','seller@life.test','')::text,true);
select set_config('test.agreement',publish_seller_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),null,'Synthetic terms','Only a test','en',false)::text,true);
select record_agreement_evidence(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,current_setting('test.agreement')::uuid,'Signed paper');
select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),null,(current_store_policy(current_setting('test.tenant')::uuid)->'policy') || '{"vatModeConsignmentPrivate":"consignment_margin","vatModeStoreOwned":"store_full"}');
select set_config('test.bag',receive_bag_with_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'',current_setting('test.agreement')::uuid)::text,true);
select set_config('test.d1',gen_random_uuid()::text,true);
select save_inspection_draft(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.bag')::uuid,current_setting('test.d1')::uuid,0,'Synthetic jacket','Jackets','Good');
select set_config('test.item',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.item')::uuid,'inspection_draft',current_setting('test.d1')::uuid,1,20000);
select is((item_photo_state(current_setting('test.tenant')::uuid,array[current_setting('test.item')::uuid])->0->>'revision')::integer,0,'new item has photo revision zero');
select set_config('test.photo',gen_random_uuid()::text,true);
select set_config('test.request',gen_random_uuid()::text,true);
select set_config('test.path',current_setting('test.tenant')||'/'||current_setting('test.item')||'/'||current_setting('test.photo')||'.jpg',true);
insert into storage.objects(bucket_id,name) values('item-photos',current_setting('test.path'));
select is(change_item_photo(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.item')::uuid,0,'add',current_setting('test.photo')::uuid),1,'first photo added');
select is(change_item_photo(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.item')::uuid,0,'add',current_setting('test.photo')::uuid),1,'same request replays');
select is(item_photo_state(current_setting('test.tenant')::uuid,array[current_setting('test.item')::uuid])->0->>'defaultPhotoId',current_setting('test.photo'),'first image is default');
select throws_like($$select change_item_photo(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.item')::uuid,0,'default',current_setting('test.photo')::uuid)$$,'%ITEM_PHOTOS_CHANGED%','stale edits refused');
select throws_like($$select change_item_photo(current_setting('test.tenant')::uuid,current_setting('test.request')::uuid,current_setting('test.item')::uuid,0,'remove',current_setting('test.photo')::uuid)$$,'%REQUEST_CONFLICT%','request identity is bound to payload');
select set_config('test.photo2',gen_random_uuid()::text,true);
insert into storage.objects(bucket_id,name) values('item-photos',current_setting('test.tenant')||'/'||current_setting('test.item')||'/'||current_setting('test.photo2')||'.jpg');
select is(change_item_photo(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.item')::uuid,1,'add',current_setting('test.photo2')::uuid),2,'second image added');
select is(change_item_photo(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.item')::uuid,2,'default',current_setting('test.photo2')::uuid),3,'default changed');
select is(change_item_photo(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.item')::uuid,3,'remove',current_setting('test.photo2')::uuid),4,'image detached');
select is(item_photo_state(current_setting('test.tenant')::uuid,array[current_setting('test.item')::uuid])->0->>'defaultPhotoId',current_setting('test.photo'),'removal selects remaining image');
select is((select count(*) from item_photo_revisions where item_id=current_setting('test.item')::uuid),4::bigint,'history retained');
select throws_like($$select change_item_photo(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.item')::uuid,4,'add',gen_random_uuid())$$,'%PHOTO_NOT_FOUND%','missing object refused');
select throws_like($$update item_photo_revisions set revision=99$$,'%permission denied%','direct writes denied');
-- Reception-origin items inherit frozen photos even if the working draft later detaches them.
select set_config('test.session',create_reception_session(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid)::text,true);
select set_config('test.inherited',gen_random_uuid()::text,true);
select set_config('test.inherited_path',current_setting('test.tenant')||'/'||current_setting('test.session')||'/'||current_setting('test.inherited')||'.jpg',true);
insert into storage.objects(bucket_id,name) values('reception-photos',current_setting('test.inherited_path'));
select save_reception_sources(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,0,jsonb_build_array(jsonb_build_object('id',current_setting('test.inherited'),'kind','photo','reference',current_setting('test.inherited_path'),'observation','')));
select quick_receive(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,current_setting('test.seller')::uuid,1,'{"description":"Inherited photo jacket"}',20000);
select set_config('test.inherited_item',(select id::text from items where origin_id=current_setting('test.session')::uuid),true);
select is(item_photo_state(current_setting('test.tenant')::uuid,array[current_setting('test.inherited_item')::uuid])->0->>'defaultPhotoId',current_setting('test.inherited'),'accepted photo inherited');
select save_reception_sources(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,
 (select max(revision) from reception_source_revisions where session_id=current_setting('test.session')::uuid),
 (select jsonb_agg(x) from jsonb_array_elements((select sources from reception_source_revisions where session_id=current_setting('test.session')::uuid order by revision desc limit 1)) x where x->>'kind'<>'photo'));
select is(item_photo_state(current_setting('test.tenant')::uuid,array[current_setting('test.inherited_item')::uuid])->0->>'defaultPhotoId',current_setting('test.inherited'),'later reception detachment does not rewrite item evidence');
select is(change_item_photo(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.inherited_item')::uuid,0,'default',current_setting('test.inherited')::uuid),1,'inherited photo can be selected as default');
select is(change_item_photo(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.inherited_item')::uuid,1,'remove',current_setting('test.inherited')::uuid),2,'inherited photo can be detached from item only');
select is(jsonb_array_length(item_photo_state(current_setting('test.tenant')::uuid,array[current_setting('test.inherited_item')::uuid])->0->'photos'),0,'explicit empty gallery does not re-inherit photos');
select ok((item_photo_state(current_setting('test.tenant')::uuid,array[current_setting('test.inherited_item')::uuid])->0->>'defaultPhotoId') is null,'empty gallery has no default');
select set_config('test.other',create_tenant('Other photo store','other-photo-store',gen_random_uuid())::text,true);
select throws_like($$select change_item_photo(current_setting('test.other')::uuid,gen_random_uuid(),current_setting('test.item')::uuid,4,'default',current_setting('test.photo')::uuid)$$,'%ITEM_NOT_FOUND%','cross-store item refused');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000000212","role":"authenticated"}';
select throws_like($$select item_photo_state(current_setting('test.tenant')::uuid,array[current_setting('test.item')::uuid])$$,'%FORBIDDEN%','unrelated user cannot list photos');
select is((select count(*) from storage.objects where name=current_setting('test.path')),0::bigint,'unrelated user cannot read bytes');
reset role;
insert into public.tenant_members(tenant_id,user_id,role) values(current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000000212','readonly');
set local role authenticated;
select is((item_photo_state(current_setting('test.tenant')::uuid,array[current_setting('test.item')::uuid])->0->>'revision')::integer,4,'readonly can view');
select throws_like($$select change_item_photo(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.item')::uuid,4,'default',current_setting('test.photo')::uuid)$$,'%FORBIDDEN%','readonly cannot edit');
select ok(not item_photo_access(current_setting('test.path'),true),'readonly cannot upload');
reset role;
insert into auth.mfa_factors(id,user_id,factor_type,status,created_at,updated_at) values(gen_random_uuid(),'f0000000-0000-4000-8000-000000000212','totp','verified',now(),now());
set local role authenticated;
select ok(not item_photo_access(current_setting('test.path'),false),'MFA still enforced');
reset role;
set local role anon;
set local "request.jwt.claims"='{"role":"anon"}';
select ok(not item_photo_access(current_setting('test.path'),false),'anonymous storage hook denies reads');
select ok(not item_photo_access(current_setting('test.path'),true),'anonymous storage hook denies uploads');
select throws_like($$select item_photo_state(current_setting('test.tenant')::uuid,array[current_setting('test.item')::uuid])$$,'%permission denied%','anonymous callers cannot list item photos');
select throws_like($$select change_item_photo(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.item')::uuid,4,'default',current_setting('test.photo')::uuid)$$,'%permission denied%','anonymous callers cannot change item photos');
select * from finish();
rollback;
