begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000008001','submission-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000008002','submission-seller@example.test',now()),
 ('f0000000-0000-4000-8000-000000008003','submission-stranger@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000008001","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Submissions test','submissions-test',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Synthetic seller','submission-seller@example.test','')::text,true);
select set_config('test.id',gen_random_uuid()::text,true);
select set_config('test.path',current_setting('test.tenant')||'/'||current_setting('test.seller')||'/'||gen_random_uuid()::text||'.jpg',true);
select set_config('test.photos',jsonb_build_array(current_setting('test.path'))::text,true);
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000008002","role":"authenticated"}';
insert into storage.objects(bucket_id,name) values('seller-submission-photos',current_setting('test.path'));
select throws_ok($$select seller_ai_configuration(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)$$,'42501',null,'browser cannot read server AI configuration');
reset role;
insert into komisio_private.seller_ai_runtime values(true,encode(extensions.digest(repeat('a',64),'sha256'),'hex')) on conflict(singleton) do update set key_hash=excluded.key_hash;
set local role authenticated;
select set_config('request.headers',jsonb_build_object('x-komisio-seller-ai',repeat('a',64))::text,true);
select lives_ok($$select seller_ai_configuration(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)$$,'verified seller and server get configuration');
select is(begin_seller_photo_assistance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.id')::uuid,current_setting('test.photos')::jsonb,'test-model',null,'en')->>'reserved','true','attempt reserved');
select is(begin_seller_photo_assistance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.id')::uuid,current_setting('test.photos')::jsonb,'test-model',null,'en')->>'reserved','false','retry never generates twice');
select throws_like($$select begin_seller_photo_assistance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.id')::uuid,'[]','test-model',null,'en')$$,'%INVALID_INPUT%','empty photo set rejected');
select throws_like($$select begin_seller_photo_assistance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,gen_random_uuid(),current_setting('test.photos')::jsonb,'test-model',null,'en')$$,'%ASSISTANCE_LIMIT%','cooldown applies');
select throws_like($$select complete_seller_photo_assistance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.id')::uuid,'{"description":"Jacket","price":null,"suitability":"likely","reason":"Fits"}',1,1)$$,'%INVALID_INPUT%','cannot claim fit without criteria');
select throws_like($$select complete_seller_photo_assistance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.id')::uuid,'{"description":"Jacket","price":{"from":"100.00","to":"200.00","evidenceIds":["f0000000-0000-4000-8000-000000000001"]},"suitability":"uncertain","reason":"Review"}',1,1)$$,'%INVALID_INPUT%','fabricated price evidence rejected');
select is(begin_seller_photo_assistance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.id')::uuid,current_setting('test.photos')::jsonb,'test-model',null,'en')->'context'->>'language','en','portal language frozen instead of store default');
select throws_like($$select begin_seller_photo_assistance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.id')::uuid,current_setting('test.photos')::jsonb,'test-model',null,'sv')$$,'%REQUEST_CONFLICT%','retry cannot change the frozen language');
select throws_like($$select complete_seller_photo_assistance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.id')::uuid,'{"description":"Jacket","price":null,"suitability":"uncertain","reason":"Review","approximatePrice":{"from":"200.00","to":"100.00","basis":"ai_estimate"}}',1,1)$$,'%INVALID_INPUT%','inverted approximate range rejected');
select throws_like($$select complete_seller_photo_assistance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.id')::uuid,'{"description":"Jacket","price":null,"suitability":"uncertain","reason":"Review","approximatePrice":{"from":"0.00","to":"100.00","basis":"ai_estimate"}}',1,1)$$,'%INVALID_INPUT%','zero approximate range rejected');
select throws_like($$select complete_seller_photo_assistance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.id')::uuid,'{"description":"Jacket","price":null,"suitability":"uncertain","reason":"Review","approximatePrice":{"from":"50.00","to":"100.00","basis":"verified"}}',1,1)$$,'%INVALID_INPUT%','unverified estimate cannot claim verified provenance');
select set_config('test.output','{"description":"Jacket","price":null,"suitability":"uncertain","reason":"Review needed","approximatePrice":{"from":"50.00","to":"100.00","basis":"ai_estimate"}}',true);
select lives_ok($$select complete_seller_photo_assistance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.id')::uuid,current_setting('test.output')::jsonb,1,1)$$,'stores advisory result');
select lives_ok($$select complete_seller_photo_assistance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.id')::uuid,current_setting('test.output')::jsonb,1,1)$$,'completion replay');
select is(begin_seller_photo_assistance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.id')::uuid,current_setting('test.photos')::jsonb,'test-model',null,'en')->>'status','ready','lost response restores result');
select is(begin_seller_photo_assistance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.id')::uuid,current_setting('test.photos')::jsonb,'test-model',null,'en')->'output'->>'indicativePrice','75.00','database derives indicative midpoint without changing evidence range');
select set_config('test.submission',gen_random_uuid()::text,true);
select lives_ok($$select submit_my_assisted_items(current_setting('test.tenant')::uuid,current_setting('test.submission')::uuid,current_setting('test.seller')::uuid,null,'Edited jacket',current_setting('test.photos')::jsonb,current_setting('test.id')::uuid)$$,'seller may edit description and attach AI provenance');
select set_config('request.headers','{}',true);
select throws_ok($$select complete_seller_photo_assistance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.id')::uuid,null,0,0)$$,'42501',null,'direct completion denied');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000008003","role":"authenticated"}';
select set_config('request.headers',jsonb_build_object('x-komisio-seller-ai',repeat('a',64))::text,true);
select throws_ok($$select seller_ai_configuration(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)$$,'42501',null,'server capability never replaces seller identity');
reset role;
select is((select assistance_id from seller_submissions where id=current_setting('test.submission')::uuid),current_setting('test.id')::uuid,'submission retains analysis identity');
select is((select count(*) from items where tenant_id=current_setting('test.tenant')::uuid),0::bigint,'no inventory accepted');
select throws_ok($$delete from seller_ai_results where id=current_setting('test.id')::uuid$$,'P0001','IMMUTABLE_OPERATION','AI result immutable');
select * from finish();
rollback;
