begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
('c0000000-0000-4000-8000-000000009911','stocktake-owner@example.test',now()),
('c0000000-0000-4000-8000-000000009912','stocktake-reader@example.test',now()),
('c0000000-0000-4000-8000-000000009913','stocktake-outsider@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"c0000000-0000-4000-8000-000000009911","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Stocktake store','stocktake-store',gen_random_uuid())::text,true);
select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),null,(current_store_policy(current_setting('test.tenant')::uuid)->'policy') || '{"vatModeStoreOwned":"store_full"}'::jsonb);
select set_config('test.purchase',gen_random_uuid()::text,true);
select register_purchase(current_setting('test.tenant')::uuid,current_setting('test.purchase')::uuid,'Synthetic lamp',10000,'Test receipt',false);
select set_config('test.item',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.item')::uuid,'purchase',current_setting('test.purchase')::uuid,null,20000);
select set_config('test.session',gen_random_uuid()::text,true);
select is(start_stocktake(current_setting('test.tenant')::uuid,current_setting('test.session')::uuid),current_setting('test.session')::uuid,'start inventory');
select is(start_stocktake(current_setting('test.tenant')::uuid,current_setting('test.session')::uuid),current_setting('test.session')::uuid,'start retry');
select throws_like($$select start_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid())$$,'%STOCKTAKE_OPEN%','only one open session');
select is((stocktake_report(current_setting('test.tenant')::uuid,current_setting('test.session')::uuid,'all',0)->'counts'->>'unchecked')::int,1,'unscanned is unchecked');
select throws_like($$select record_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,'closed','',null,0,null,'')$$,'%STOCKTAKE_PENDING%','cannot close unchecked stock');
select set_config('test.scan',gen_random_uuid()::text,true);
select is(record_stocktake(current_setting('test.tenant')::uuid,current_setting('test.scan')::uuid,current_setting('test.session')::uuid,'scan','I-'||left(current_setting('test.item'),8),null,null,null,''),current_setting('test.scan')::uuid,'scan printed label');
select is(record_stocktake(current_setting('test.tenant')::uuid,current_setting('test.scan')::uuid,current_setting('test.session')::uuid,'scan','I-'||left(current_setting('test.item'),8),null,null,null,''),current_setting('test.scan')::uuid,'scan retry');
select throws_like($$select record_stocktake(current_setting('test.tenant')::uuid,current_setting('test.scan')::uuid,current_setting('test.session')::uuid,'scan',current_setting('test.item'),null,null,null,'')$$,'%REQUEST_CONFLICT%','same ID different input denied');
select throws_like($$select record_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,'finding','',current_setting('test.item')::uuid,0,'damaged','Torn')$$,'%STOCKTAKE_CHANGED%','stale finding denied');
select lives_ok($$select record_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,'finding','',current_setting('test.item')::uuid,1,'damaged','Torn')$$,'record damage');
select record_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,'scan',current_setting('test.item'),null,null,null,'');
select is(stocktake_report(current_setting('test.tenant')::uuid,current_setting('test.session')::uuid,'all',0)->'rows'->0->>'observation','damaged','repeated scan preserves damage');
select is((select count(*) from sale_lines where tenant_id=current_setting('test.tenant')::uuid),0::bigint,'stocktake creates no sales');
select set_config('test.close',gen_random_uuid()::text,true);
select is(record_stocktake(current_setting('test.tenant')::uuid,current_setting('test.close')::uuid,current_setting('test.session')::uuid,'closed','',null,3,null,''),current_setting('test.close')::uuid,'close reviewed inventory');
select is(record_stocktake(current_setting('test.tenant')::uuid,current_setting('test.scan')::uuid,current_setting('test.session')::uuid,'scan','I-'||left(current_setting('test.item'),8),null,null,null,''),current_setting('test.scan')::uuid,'successful retry after close');
select throws_like($$select record_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session')::uuid,'scan',current_setting('test.item'),null,null,null,'')$$,'%STOCKTAKE_CLOSED%','new scans after close denied');
select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','stocktake-sale',now(),'SEK',jsonb_build_array(jsonb_build_object('itemId',current_setting('test.item'),'priceOre',20000)));
select is(stocktake_report(current_setting('test.tenant')::uuid,current_setting('test.session')::uuid,'all',0)->'rows'->0->>'changed','false','closed report frozen after sale');
select set_config('test.session2',gen_random_uuid()::text,true);
select start_stocktake(current_setting('test.tenant')::uuid,current_setting('test.session2')::uuid);
select is((stocktake_report(current_setting('test.tenant')::uuid,current_setting('test.session2')::uuid,'all',0)->'counts'->>'total')::int,0,'sold item excluded from snapshot');
select set_config('test.purchase2',gen_random_uuid()::text,true);
select register_purchase(current_setting('test.tenant')::uuid,current_setting('test.purchase2')::uuid,'Synthetic coat',10000,'Test receipt 2',false);
select set_config('test.item2',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.item2')::uuid,'purchase',current_setting('test.purchase2')::uuid,null,20000);
select record_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session2')::uuid,'scan',current_setting('test.item2'),null,null,null,'');
select is(stocktake_report(current_setting('test.tenant')::uuid,current_setting('test.session2')::uuid,'deviations',0)->'rows'->0->>'expected','false','newly accepted item flagged outside starting list');
select record_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session2')::uuid,'finding','',current_setting('test.item2')::uuid,1,'missing','Moved during count');
select is(stocktake_report(current_setting('test.tenant')::uuid,current_setting('test.session2')::uuid,'all',0)->'rows'->0->>'observation','missing','explicit missing finding');
select record_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session2')::uuid,'scan',current_setting('test.item2'),null,null,null,'');
select is(stocktake_report(current_setting('test.tenant')::uuid,current_setting('test.session2')::uuid,'all',0)->'rows'->0->>'observation','found','later scan corrects missing with new history');
select is((select count(*) from stocktake_events where session_id=current_setting('test.session2')::uuid and observation='missing'),1::bigint,'old missing evidence preserved');
select throws_like($$select record_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session2')::uuid,'closed','',null,2,null,'')$$,'%STOCKTAKE_CHANGED%','stale close requires refresh');
select record_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session2')::uuid,'closed','',null,3,null,'');
select set_config('test.session3',gen_random_uuid()::text,true);
select start_stocktake(current_setting('test.tenant')::uuid,current_setting('test.session3')::uuid);
select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','stocktake-sale2',now(),'SEK',jsonb_build_array(jsonb_build_object('itemId',current_setting('test.item2'),'priceOre',20000)));
select is((stocktake_report(current_setting('test.tenant')::uuid,current_setting('test.session3')::uuid,'all',0)->'counts'->>'unchecked')::int,0,'sale during count is not unverified stock');
select is(stocktake_report(current_setting('test.tenant')::uuid,current_setting('test.session3')::uuid,'all',0)->'rows'->0->>'changed','true','sale during count is visible');
select lives_ok($$select record_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session3')::uuid,'closed','',null,0,null,'')$$,'sold expected item does not block close');
select is(stocktake_report(current_setting('test.tenant')::uuid,current_setting('test.session3')::uuid,'all',0)->'rows'->0->>'changed','true','close freezes stock changes');
select is((select count(*) from sale_lines where tenant_id=current_setting('test.tenant')::uuid),2::bigint,'only the two explicitly recorded sales exist');
select throws_like($$select record_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session3')::uuid,null,'',null,0,null,'')$$,'%INVALID_INPUT%','null kind refused');
select throws_like($$select stocktake_report(current_setting('test.tenant')::uuid,current_setting('test.session')::uuid,'all',-1)$$,'%INVALID_INPUT%','unbounded negative offset refused');
select set_config('test.session4',gen_random_uuid()::text,true);
select start_stocktake(current_setting('test.tenant')::uuid,current_setting('test.session4')::uuid);
select set_config('test.purchase3',gen_random_uuid()::text,true);
select register_purchase(current_setting('test.tenant')::uuid,current_setting('test.purchase3')::uuid,'Ambiguous lamp A',10000,'Test receipt A',false);
select accept_item(current_setting('test.tenant')::uuid,'abcde123-0000-4000-8000-000000000001','purchase',current_setting('test.purchase3')::uuid,null,20000);
select set_config('test.purchase4',gen_random_uuid()::text,true);
select register_purchase(current_setting('test.tenant')::uuid,current_setting('test.purchase4')::uuid,'Ambiguous lamp B',10000,'Test receipt B',false);
select accept_item(current_setting('test.tenant')::uuid,'abcde123-0000-4000-8000-000000000002','purchase',current_setting('test.purchase4')::uuid,null,20000);
select throws_like($$select record_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session4')::uuid,'scan','I-ABCDE123',null,null,null,'')$$,'%STOCKTAKE_AMBIGUOUS%','ambiguous prefix never picks first match');
select lives_ok($$select record_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session4')::uuid,'scan','abcde123-0000-4000-8000-000000000001',null,null,null,'')$$,'full UUID resolves ambiguity');
select throws_like($$select record_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session4')::uuid,'finding','','abcde123-0000-4000-8000-000000000001',1,'missing',' ')$$,'%INVALID_INPUT%','blank correction reason rejected');
select throws_like($$select record_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.session4')::uuid,'scan','c0000000-0000-4000-8000-000000009911',null,null,null,'')$$,'%ITEM_NOT_FOUND%','unknown item cannot enter count');
select is((stocktake_report(current_setting('test.tenant')::uuid,current_setting('test.session4')::uuid,'all',0)->'counts'->>'total')::int,1,'rejected scans leave no observation');
select throws_ok($$delete from stocktake_events$$,'42501',null,'direct write denied');
reset role;
select throws_like($$delete from stocktake_events where tenant_id=current_setting('test.tenant')::uuid$$,'%IMMUTABLE%','events immutable');
select throws_like($$delete from stocktake_expected_items where tenant_id=current_setting('test.tenant')::uuid$$,'%IMMUTABLE%','snapshot immutable');
select throws_like($$delete from stocktake_sessions where tenant_id=current_setting('test.tenant')::uuid$$,'%IMMUTABLE%','session immutable');
insert into tenant_members(tenant_id,user_id,role) values(current_setting('test.tenant')::uuid,'c0000000-0000-4000-8000-000000009912','readonly');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"c0000000-0000-4000-8000-000000009912","role":"authenticated"}';
select lives_ok($$select stocktake_report(current_setting('test.tenant')::uuid,current_setting('test.session')::uuid,'all',0)$$,'readonly reads');
select throws_ok($$select start_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid())$$,'42501',null,'readonly cannot start');
set local "request.jwt.claims"='{"sub":"c0000000-0000-4000-8000-000000009913","role":"authenticated"}';
select throws_ok($$select stocktake_report(current_setting('test.tenant')::uuid,current_setting('test.session')::uuid,'all',0)$$,'42501',null,'outsider denied');
select is((select count(*) from stocktake_sessions),0::bigint,'session RLS');
select is((select count(*) from stocktake_expected_items),0::bigint,'snapshot RLS');
select is((select count(*) from stocktake_events),0::bigint,'event RLS');
reset role;
select ok(not has_function_privilege('anon','public.start_stocktake(uuid,uuid)','execute'),'anonymous denied');
insert into auth.mfa_factors(id,user_id,factor_type,status,created_at,updated_at) values(gen_random_uuid(),'c0000000-0000-4000-8000-000000009911','totp','verified',now(),now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"c0000000-0000-4000-8000-000000009911","role":"authenticated","aal":"aal1"}';
select throws_ok($$select stocktake_report(current_setting('test.tenant')::uuid,current_setting('test.session')::uuid,'all',0)$$,'42501',null,'MFA read');
select throws_like($$select start_stocktake(current_setting('test.tenant')::uuid,gen_random_uuid())$$,'%AUTH_REQUIRED%','MFA write');
reset role;
select * from finish(); rollback;
