begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
('f0000000-0000-4000-8000-000000002891','close-owner@example.test',now()),
('f0000000-0000-4000-8000-000000002892','close-worker@example.test',now()),
('f0000000-0000-4000-8000-000000002893','close-outsider@example.test',now()),
('f0000000-0000-4000-8000-000000002894','close-reader@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000002891","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Automatic close store','automatic-close-store',gen_random_uuid())::text,true);
select set_config('test.other',create_tenant('Other close store','other-close-store',gen_random_uuid())::text,true);
select set_config('test.grant',gen_random_uuid()::text,true);
select lives_ok($$select enable_automation(current_setting('test.tenant')::uuid,current_setting('test.grant')::uuid,'day_close','close-worker@example.test')$$,'owner enables narrow preparation scope');
select throws_like($$select run_automatic_day_closes(current_setting('test.tenant')::uuid,gen_random_uuid())$$,'%FORBIDDEN%','owner cannot impersonate worker');
select set_config('test.yesterday',((now() at time zone 'Europe/Stockholm')::date-1)::text,true);
select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),null,(current_store_policy(current_setting('test.tenant')::uuid)->'policy') || '{"vatModeStoreOwned":"store_full"}'::jsonb);
select set_config('test.purchase',gen_random_uuid()::text,true);
select register_purchase(current_setting('test.tenant')::uuid,current_setting('test.purchase')::uuid,'Synthetic shirt',10000,'Test receipt',false);
select set_config('test.item',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.item')::uuid,'purchase',current_setting('test.purchase')::uuid,null,20000);
select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','automatic-close-sale',(current_setting('test.yesterday')||' 12:00')::timestamp at time zone 'Europe/Stockholm','SEK',jsonb_build_array(jsonb_build_object('itemId',current_setting('test.item'),'priceOre',20000)));
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000002892","role":"authenticated"}';
select throws_like($$select run_automatic_day_closes(current_setting('test.tenant')::uuid,gen_random_uuid())$$,'%FORBIDDEN%','unaccepted grant denied');
select accept_automation_grants();
select is(jsonb_array_length(day_close_automation_tenants()),1,'worker sees only granted store');
select throws_like($$select run_automatic_day_closes(current_setting('test.other')::uuid,gen_random_uuid())$$,'%FORBIDDEN%','other tenant denied');
select throws_like($$select generate_day_close(current_setting('test.tenant')::uuid,gen_random_uuid(),(now() at time zone 'Europe/Stockholm')::date)$$,'%FORBIDDEN%','worker cannot close current day');
select throws_like($$select generate_day_close(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.yesterday')::date)$$,'%FORBIDDEN%','worker cannot backfill before grant');
select is((run_automatic_day_closes(current_setting('test.tenant')::uuid,gen_random_uuid())->>'checked')::int,0,'activation day waits until tomorrow');
reset role;
-- Simulate an already active grant. Production clients cannot change grant dates.
update automation_grants set enabled_at=(current_setting('test.yesterday')||' 00:00')::timestamp at time zone 'Europe/Stockholm' where id=current_setting('test.grant')::uuid;
insert into tenant_members(tenant_id,user_id,role) values(current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000002894','readonly');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000002892","role":"authenticated"}';
select set_config('test.run',gen_random_uuid()::text,true);
select set_config('test.result',run_automatic_day_closes(current_setting('test.tenant')::uuid,current_setting('test.run')::uuid)::text,true);
select is((current_setting('test.result')::jsonb->>'created')::int,1,'creates yesterday with activity');
select is(run_automatic_day_closes(current_setting('test.tenant')::uuid,current_setting('test.run')::uuid),current_setting('test.result')::jsonb,'lost response retries exact recorded run');
select is((run_automatic_day_closes(current_setting('test.tenant')::uuid,gen_random_uuid())->>'unchanged')::int,1,'unchanged day does not create another version');
select is((select count(*) from day_closes where tenant_id=current_setting('test.tenant')::uuid),1::bigint,'one immutable close');
select is((select gross_ore from day_closes where tenant_id=current_setting('test.tenant')::uuid),20000::bigint,'existing totals used');
select is((select count(*) from accounting_exports where tenant_id=current_setting('test.tenant')::uuid),0::bigint,'no accounting exports generated');
select throws_like($$select begin_fortnox_send(current_setting('test.tenant')::uuid,gen_random_uuid(),gen_random_uuid())$$,'%FORBIDDEN%','preparation grants no provider-send rights');
select throws_like($$select publish_store_policy(current_setting('test.tenant')::uuid,gen_random_uuid(),null,'{}')$$,'%FORBIDDEN%','preparation grants no policy rights');
select throws_like($$select run_automatic_day_closes(current_setting('test.tenant')::uuid,null)$$,'%INVALID_INPUT%','null run refused');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000002891","role":"authenticated"}';
select set_config('test.purchase2',gen_random_uuid()::text,true);
select register_purchase(current_setting('test.tenant')::uuid,current_setting('test.purchase2')::uuid,'Late synthetic shirt',10000,'Late test receipt',false);
select set_config('test.item2',gen_random_uuid()::text,true);
select accept_item(current_setting('test.tenant')::uuid,current_setting('test.item2')::uuid,'purchase',current_setting('test.purchase2')::uuid,null,30000);
select record_sale(current_setting('test.tenant')::uuid,gen_random_uuid(),'manual','automatic-close-late-sale',(current_setting('test.yesterday')||' 13:00')::timestamp at time zone 'Europe/Stockholm','SEK',jsonb_build_array(jsonb_build_object('itemId',current_setting('test.item2'),'priceOre',30000)));
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000002892","role":"authenticated"}';
select is((run_automatic_day_closes(current_setting('test.tenant')::uuid,gen_random_uuid())->>'created')::int,1,'late sale creates a new version');
select is((select gross_ore from day_closes where tenant_id=current_setting('test.tenant')::uuid and version=1),20000::bigint,'old close preserved');
select is((select gross_ore from day_closes where tenant_id=current_setting('test.tenant')::uuid and version=2),50000::bigint,'new close includes late sale');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000002894","role":"authenticated"}';
select is(day_close_automatic_status(current_setting('test.tenant')::uuid)->>'through',current_setting('test.yesterday'),'readonly can see progress');
select throws_like($$select run_automatic_day_closes(current_setting('test.tenant')::uuid,gen_random_uuid())$$,'%FORBIDDEN%','readonly cannot run');
select throws_like($$select enable_automation(current_setting('test.other')::uuid,gen_random_uuid(),'day_close','close-worker@example.test')$$,'%FORBIDDEN%','readonly cannot enable');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000002893","role":"authenticated"}';
select throws_like($$select day_close_automatic_status(current_setting('test.tenant')::uuid)$$,'%FORBIDDEN%','outsider cannot read status');
select throws_like($$select run_automatic_day_closes(current_setting('test.tenant')::uuid,gen_random_uuid())$$,'%FORBIDDEN%','outsider cannot run');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000002891","role":"authenticated"}';
select disable_automation(current_setting('test.tenant')::uuid,'day_close');
select is(day_close_automatic_status(current_setting('test.tenant')::uuid),null::jsonb,'disabled scope does not show previous run as active');
select enable_automation(current_setting('test.tenant')::uuid,gen_random_uuid(),'fortnox_send','close-worker@example.test');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000002892","role":"authenticated"}';
select accept_automation_grants();
select throws_like($$select run_automatic_day_closes(current_setting('test.tenant')::uuid,current_setting('test.run')::uuid)$$,'%FORBIDDEN%','revocation blocks even a successful old retry');
select is(jsonb_array_length(day_close_automation_tenants()),0,'other scope cannot discover preparation stores');
select throws_like($$select generate_day_close(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.yesterday')::date)$$,'%FORBIDDEN%','send grant alone cannot prepare closes');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000002891","role":"authenticated"}';
select set_config('test.grant2',gen_random_uuid()::text,true);
select enable_automation(current_setting('test.tenant')::uuid,current_setting('test.grant2')::uuid,'day_close','close-worker@example.test');
select is(day_close_automatic_status(current_setting('test.tenant')::uuid),null::jsonb,'new grant starts with fresh status');
reset role;
update automation_grants set enabled_at=((current_setting('test.yesterday')::date-65)::text||' 00:00')::timestamp at time zone 'Europe/Stockholm' where id=current_setting('test.grant2')::uuid;
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000002892","role":"authenticated"}';
select accept_automation_grants();
select set_config('test.backlog',run_automatic_day_closes(current_setting('test.tenant')::uuid,gen_random_uuid())::text,true);
select is((current_setting('test.backlog')::jsonb->>'checked')::int,31,'backlog bounded to 31 dates');
select is(current_setting('test.backlog')::jsonb->>'outcome','partial','backlog exposes remaining days');
select is((current_setting('test.backlog')::jsonb->>'skipped')::int,31,'empty days do not generate empty closes');
select ok((run_automatic_day_closes(current_setting('test.tenant')::uuid,gen_random_uuid())->>'through')::date>(current_setting('test.backlog')::jsonb->>'through')::date,'later run advances durable progress');
select is(run_automatic_day_closes(current_setting('test.tenant')::uuid,gen_random_uuid())->>'outcome','complete','bounded runs eventually catch up');
select throws_like($$select run_automatic_day_closes(current_setting('test.tenant')::uuid,current_setting('test.run')::uuid)$$,'%REQUEST_CONFLICT%','old run ID cannot be reused under new grant');
reset role;
select ok(not has_function_privilege('anon','public.run_automatic_day_closes(uuid,uuid)','execute'),'anonymous cannot run');
select ok(not has_function_privilege('authenticated','komisio_private.day_close_totals(uuid,date)','execute'),'private totals stay private');
insert into auth.mfa_factors(id,user_id,factor_type,status,created_at,updated_at) values(gen_random_uuid(),'f0000000-0000-4000-8000-000000002892','totp','verified',now(),now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000002892","role":"authenticated","aal":"aal1"}';
select throws_like($$select run_automatic_day_closes(current_setting('test.tenant')::uuid,gen_random_uuid())$$,'%AUTH_REQUIRED%','worker MFA enforced');
reset role;
select * from finish();
rollback;
