begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('f0000000-0000-4000-8000-000000002921','import-owner@example.test',now()),
 ('f0000000-0000-4000-8000-000000002922','import-staff@example.test',now()),
 ('f0000000-0000-4000-8000-000000002923','import-outsider@example.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000002921","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Import check','import-check',gen_random_uuid())::text,true);
select set_config('test.other',create_tenant('Other import','other-import-check',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Current seller','current@example.test','')::text,true);
select set_config('test.foreign',register_seller(current_setting('test.other')::uuid,gen_random_uuid(),'Foreign seller','foreign@example.test','')::text,true);
select register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Duplicate A','shared@example.test','');
select register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Duplicate B','shared@example.test','');
select is(inventory_import_sellers(current_setting('test.tenant')::uuid,'[{"sellerId":"","email":"CURRENT@EXAMPLE.TEST"}]')->0->>'status','matched','email is exact and case insensitive');
select is(inventory_import_sellers(current_setting('test.tenant')::uuid,jsonb_build_array(jsonb_build_object('sellerId',current_setting('test.seller'),'email','')))->0->>'id',current_setting('test.seller'),'exact seller ID is supported');
select is(inventory_import_sellers(current_setting('test.tenant')::uuid,'[{"sellerId":"","email":"shared@example.test"}]')->0->>'status','ambiguous','duplicate email is not guessed');
select is(inventory_import_sellers(current_setting('test.tenant')::uuid,'[{"sellerId":"","email":"current"}]')->0->>'status','missing','no fuzzy seller matching');
select is(inventory_import_sellers(current_setting('test.tenant')::uuid,jsonb_build_array(jsonb_build_object('sellerId',current_setting('test.seller'),'email','wrong@example.test')))->0->>'status','conflict','two references must agree');
select is(inventory_import_sellers(current_setting('test.tenant')::uuid,jsonb_build_array(jsonb_build_object('sellerId',current_setting('test.foreign'),'email','foreign@example.test')))->0->>'status','missing','foreign seller is never disclosed');
select is(inventory_import_sellers(current_setting('test.tenant')::uuid,'[{"sellerId":"","email":"foreign@example.test"}]')->0,jsonb_build_object('status','missing'),'missing result exposes no candidate');
select is(inventory_import_sellers(current_setting('test.tenant')::uuid,'[{"sellerId":"","email":"shared@example.test"}]')->0,jsonb_build_object('status','ambiguous'),'ambiguous result exposes no candidates');
select is(jsonb_array_length(inventory_import_sellers(current_setting('test.tenant')::uuid,'[]')),0,'empty lookup is harmless');
select throws_ok($$select inventory_import_sellers(current_setting('test.tenant')::uuid,null)$$,'P0001','INVALID_INPUT','null rejected');
select throws_ok($$select inventory_import_sellers(current_setting('test.tenant')::uuid,'{}')$$,'P0001','INVALID_INPUT','non array rejected');
select throws_ok($$select inventory_import_sellers(current_setting('test.tenant')::uuid,'[{"sellerId":"invalid","email":""}]')$$,'P0001','INVALID_INPUT','invalid ID rejected');
select throws_ok($$select inventory_import_sellers(current_setting('test.tenant')::uuid,'[{"sellerId":"","email":"","extra":true}]')$$,'P0001','INVALID_INPUT','unknown keys rejected');
select throws_ok($$select inventory_import_sellers(current_setting('test.tenant')::uuid,(select jsonb_agg('{"sellerId":"","email":""}'::jsonb) from generate_series(1,201)))$$,'P0001','INVALID_INPUT','lookup bounded without truncation');
select is((select count(*)::integer from items where tenant_id=current_setting('test.tenant')::uuid),0,'preview creates no inventory');
reset role;
insert into tenant_members(tenant_id,user_id,role) values(current_setting('test.tenant')::uuid,'f0000000-0000-4000-8000-000000002922','staff');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000002922","role":"authenticated"}';
select throws_ok($$select inventory_import_sellers(current_setting('test.tenant')::uuid,'[]')$$,'42501','FORBIDDEN','staff denied');
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000002923","role":"authenticated"}';
select throws_ok($$select inventory_import_sellers(current_setting('test.tenant')::uuid,'[]')$$,'42501','FORBIDDEN','outsider denied');
set local role anon;
select throws_ok($$select inventory_import_sellers(current_setting('test.tenant')::uuid,'[]')$$,'42501','permission denied for function inventory_import_sellers','anonymous denied');
reset role;
update tenant_members set role='admin' where tenant_id=current_setting('test.tenant')::uuid and user_id='f0000000-0000-4000-8000-000000002922';
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000002922","role":"authenticated"}';
select lives_ok($$select inventory_import_sellers(current_setting('test.tenant')::uuid,'[]')$$,'admin allowed');
reset role;
insert into auth.mfa_factors(id,user_id,factor_type,status,created_at,updated_at) values(gen_random_uuid(),'f0000000-0000-4000-8000-000000002921','totp','verified',now(),now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"f0000000-0000-4000-8000-000000002921","role":"authenticated","aal":"aal1"}';
select throws_like($$select inventory_import_sellers(current_setting('test.tenant')::uuid,'[]')$$,'%AUTH_REQUIRED%','MFA is required');
reset role;
select * from finish();
rollback;
