begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('29800000-0000-4000-8000-000000000001','owner@export-photo.test',now()),
 ('29800000-0000-4000-8000-000000000002','seller@export-photo.test',now()),
 ('29800000-0000-4000-8000-000000000003','other@export-photo.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"29800000-0000-4000-8000-000000000001","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Photo export TEST','photo-export-test',gen_random_uuid())::text,true);
select set_config('test.foreign',create_tenant('Other export TEST','photo-export-other',gen_random_uuid())::text,true);
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Exported seller','seller@export-photo.test','')::text,true);
select set_config('test.other',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Other seller','other@export-photo.test','')::text,true);
select set_config('test.foreign_seller',register_seller(current_setting('test.foreign')::uuid,gen_random_uuid(),'Foreign seller','seller@export-photo.test','')::text,true);
select set_config('test.agreement',publish_seller_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),null,'Accepted TEST terms','Original fictional terms','sv',false)::text,true);
select record_agreement_evidence(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,current_setting('test.agreement')::uuid,'Synthetic paper');
select publish_seller_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.agreement')::uuid,'Unaccepted TEST terms','Unaccepted fictional terms','sv',false);
select set_config('test.first',gen_random_uuid()::text,true);
select set_config('test.second',gen_random_uuid()::text,true);
select set_config('test.ai',gen_random_uuid()::text,true);
select set_config('test.path',current_setting('test.tenant')||'/'||current_setting('test.seller')||'/'||gen_random_uuid()::text||'.jpg',true);
reset role;
insert into komisio_private.seller_ai_runtime values(true,encode(extensions.digest(repeat('a',64),'sha256'),'hex')) on conflict(singleton) do update set key_hash=excluded.key_hash;
set local role authenticated;
set local "request.jwt.claims"='{"sub":"29800000-0000-4000-8000-000000000002","role":"authenticated"}';
insert into storage.objects(bucket_id,name) values('seller-submission-photos',current_setting('test.path'));
select set_config('request.headers',jsonb_build_object('x-komisio-seller-ai',repeat('a',64))::text,true);
select begin_seller_photo_assistance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.ai')::uuid,jsonb_build_array(current_setting('test.path')),'test-model');
select complete_seller_photo_assistance(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.ai')::uuid,'{"description":"Synthetic AI coat","price":null,"suitability":"uncertain","reason":"Review needed"}',1,1);
select submit_my_assisted_items(current_setting('test.tenant')::uuid,current_setting('test.first')::uuid,current_setting('test.seller')::uuid,null,'Synthetic coat',jsonb_build_array(current_setting('test.path')),current_setting('test.ai')::uuid,null,'store','SEK');
set local "request.jwt.claims"='{"sub":"29800000-0000-4000-8000-000000000001","role":"authenticated"}';
select review_seller_submission(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.first')::uuid,'more_information','Show label');
set local "request.jwt.claims"='{"sub":"29800000-0000-4000-8000-000000000002","role":"authenticated"}';
select submit_my_assisted_items(current_setting('test.tenant')::uuid,current_setting('test.second')::uuid,current_setting('test.seller')::uuid,current_setting('test.first')::uuid,'Synthetic coat with label',jsonb_build_array(current_setting('test.path')),null,null,'store','SEK');
select set_config('test.foreign_path',current_setting('test.foreign')||'/'||current_setting('test.foreign_seller')||'/'||gen_random_uuid()::text||'.jpg',true);
insert into storage.objects(bucket_id,name) values('seller-submission-photos',current_setting('test.foreign_path'));
select submit_my_items(current_setting('test.foreign')::uuid,gen_random_uuid(),current_setting('test.foreign_seller')::uuid,null,'FOREIGN PRIVATE PROPOSAL',jsonb_build_array(current_setting('test.foreign_path')));
set local "request.jwt.claims"='{"sub":"29800000-0000-4000-8000-000000000003","role":"authenticated"}';
select set_config('test.other_path',current_setting('test.tenant')||'/'||current_setting('test.other')||'/'||gen_random_uuid()::text||'.jpg',true);
insert into storage.objects(bucket_id,name) values('seller-submission-photos',current_setting('test.other_path'));
select submit_my_items(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.other')::uuid,null,'OTHER PRIVATE PROPOSAL',jsonb_build_array(current_setting('test.other_path')));
set local "request.jwt.claims"='{"sub":"29800000-0000-4000-8000-000000000001","role":"authenticated"}';
select review_seller_submission(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.second')::uuid,'invite','Bring it in');
select set_config('test.session',prepare_submission_reception(current_setting('test.tenant')::uuid,current_setting('test.second')::uuid)::text,true);
select set_config('test.export',seller_data_export(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)::text,true);
select is(jsonb_array_length(current_setting('test.export')::jsonb->'photoSubmissions'),2,'original and correction exported');
select is((select x->>'previous_id' from jsonb_array_elements(current_setting('test.export')::jsonb->'photoSubmissions') x where x->>'id'=current_setting('test.second')),current_setting('test.first'),'correction provenance retained');
select is((select x->'assistance_output'->'suggestion'->>'description' from jsonb_array_elements(current_setting('test.export')::jsonb->'photoSubmissions') x where x->>'id'=current_setting('test.first')),'Synthetic AI coat','saved suggestion included without regenerating');
select is((select x->'photos'->>0 from jsonb_array_elements(current_setting('test.export')::jsonb->'photoSubmissions') x where x->>'id'=current_setting('test.first')),current_setting('test.path'),'photo references retained');
select is(jsonb_array_length(current_setting('test.export')::jsonb->'photoSubmissionReviews'),2,'both review decisions retained');
select is(current_setting('test.export')::jsonb->'submissionReceptions'->0->>'session_id',current_setting('test.session'),'reception trace retained');
select is(jsonb_array_length(current_setting('test.export')::jsonb->'acceptedAgreements'),1,'only evidenced terms included');
select is(current_setting('test.export')::jsonb->'acceptedAgreements'->0->>'body','Original fictional terms','accepted historical text exact');
select ok(not current_setting('test.export') like '%PRIVATE PROPOSAL%','other seller and foreign tenant excluded');
select ok(not (current_setting('test.export')::jsonb->'photoSubmissions'->0 ? 'tenant_id'),'tenant column stripped from proposal');
select ok(not (current_setting('test.export')::jsonb->'photoSubmissions'->0 ? 'assistance_id'),'internal attempt linkage excluded');
select ok(not (current_setting('test.export')::jsonb ? 'assistanceAttempts'),'internal model attempts excluded');
select is((select count(*) from access_events where tenant_id=current_setting('test.tenant')::uuid and action='seller.exported'),1::bigint,'exactly one export audit event');
select is(jsonb_array_length(current_setting('test.export')::jsonb->'receptions'),1,'legacy export fields preserved');
select throws_like($$select seller_data_export(current_setting('test.foreign')::uuid,current_setting('test.seller')::uuid)$$,'%SELLER_NOT_FOUND%','seller cannot be exported under another tenant');
reset role;
insert into tenant_members(tenant_id,user_id,role) values(current_setting('test.tenant')::uuid,'29800000-0000-4000-8000-000000000003','staff');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"29800000-0000-4000-8000-000000000003","role":"authenticated"}';
select throws_ok($$select seller_data_export(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)$$,'42501',null,'staff export denied');
reset role;
insert into auth.mfa_factors(id,user_id,factor_type,status,created_at,updated_at) values(gen_random_uuid(),'29800000-0000-4000-8000-000000000001','totp','verified',now(),now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"29800000-0000-4000-8000-000000000001","role":"authenticated","aal":"aal1"}';
select throws_ok($$select seller_data_export(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)$$,'42501',null,'MFA challenge denied');
reset role;
select ok(not has_function_privilege('anon','public.seller_data_export(uuid,uuid)','execute'),'anonymous export denied');
select * from finish();
rollback;
