begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('30100000-0000-4000-8000-000000000001','owner@agreement-workspace.test',now()),
 ('30100000-0000-4000-8000-000000000002','outsider@agreement-workspace.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"30100000-0000-4000-8000-000000000001","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Workspace TEST','agreement-workspace-test',gen_random_uuid())::text,true);
select set_config('test.agreement',publish_seller_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),null,'TEST terms','Synthetic terms','sv',false)::text,true);
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Accepted TEST','','0101')::text,true);
select register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Missing TEST','','0102');
select record_agreement_evidence(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,current_setting('test.agreement')::uuid,'Paper TEST');
select record_agreement_evidence(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,current_setting('test.agreement')::uuid,'Second paper TEST');
select is((agreement_sellers(current_setting('test.tenant')::uuid,current_setting('test.agreement')::uuid,'','all',0)->>'total')::int,2,'one row per seller despite multiple evidence rows');
select is((agreement_sellers(current_setting('test.tenant')::uuid,current_setting('test.agreement')::uuid,'','accepted',0)->>'total')::int,1,'accepted filter counts sellers');
select is(agreement_sellers(current_setting('test.tenant')::uuid,current_setting('test.agreement')::uuid,'','missing',0)->'sellers'->0->>'name','Missing TEST','missing filter does not mix accepted sellers');
select is((agreement_sellers(current_setting('test.tenant')::uuid,current_setting('test.agreement')::uuid,'Accepted','all',25)->>'total')::int,1,'count retained beyond last page');
select is(jsonb_array_length(agreement_sellers(current_setting('test.tenant')::uuid,current_setting('test.agreement')::uuid,'Accepted','all',25)->'sellers'),0,'offset applied after search');
select set_config('test.next',publish_seller_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.agreement')::uuid,'TEST new terms','New synthetic terms','en',false)::text,true);
select is((agreement_sellers(current_setting('test.tenant')::uuid,current_setting('test.next')::uuid,'','accepted',0)->>'total')::int,0,'old evidence does not count for new version');
select throws_like($$select agreement_sellers(current_setting('test.tenant')::uuid,gen_random_uuid(),'','all',0)$$,'%AGREEMENT_NOT_FOUND%','unknown version refused');
select throws_like($$select agreement_sellers(current_setting('test.tenant')::uuid,current_setting('test.next')::uuid,'','all',-1)$$,'%INVALID_INPUT%','negative offset refused');
select set_config('test.profile','{"name":"Registered TEST","email":"","phone":"0103","nationalId":"","addressLine1":"","addressLine2":"","postalCode":"","city":"","country":"","language":"","notes":""}',true);
select set_config('test.new',gen_random_uuid()::text,true);
select throws_like($$select save_seller_with_agreement(current_setting('test.tenant')::uuid,current_setting('test.new')::uuid,null,null,current_setting('test.profile')::jsonb,current_setting('test.agreement')::uuid,'Paper TEST')$$,'%AGREEMENT_CHANGED%','stale registration cannot attest new terms');
select is((select count(*) from sellers where id=current_setting('test.new')::uuid),0::bigint,'stale agreement rolls back seller registration');
select lives_ok($$select save_seller_with_agreement(current_setting('test.tenant')::uuid,current_setting('test.new')::uuid,null,null,current_setting('test.profile')::jsonb,current_setting('test.next')::uuid,'Paper TEST')$$,'registration and evidence saved together');
select is((select agreement_id::text from seller_agreement_evidence where id=current_setting('test.new')::uuid),current_setting('test.next'),'registration pins displayed active version');
select lives_ok($$select save_seller_with_agreement(current_setting('test.tenant')::uuid,current_setting('test.new')::uuid,null,null,current_setting('test.profile')::jsonb,current_setting('test.next')::uuid,'Paper TEST')$$,'registration replay is safe');
select throws_like($$select save_seller_with_agreement(current_setting('test.tenant')::uuid,current_setting('test.new')::uuid,null,null,current_setting('test.profile')::jsonb,current_setting('test.next')::uuid,'Different paper')$$,'%REQUEST_CONFLICT%','retry cannot change evidence reference');
select set_config('test.edit',gen_random_uuid()::text,true);
select throws_like($$select save_seller_with_agreement(current_setting('test.tenant')::uuid,current_setting('test.edit')::uuid,current_setting('test.new')::uuid,1,jsonb_set(current_setting('test.profile')::jsonb,'{name}','"Changed TEST"'),current_setting('test.agreement')::uuid,'Paper TEST')$$,'%AGREEMENT_CHANGED%','stale agreement refuses profile change');
select is((select name from sellers where id=current_setting('test.new')::uuid),'Registered TEST','failed evidence rolls back profile update');
select lives_ok($$select save_seller_with_agreement(current_setting('test.tenant')::uuid,current_setting('test.edit')::uuid,current_setting('test.new')::uuid,1,jsonb_set(current_setting('test.profile')::jsonb,'{name}','"Changed TEST"'),current_setting('test.next')::uuid,'Paper TEST')$$,'profile and evidence saved atomically');
select set_config('test.latest',publish_seller_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.next')::uuid,'Later TEST terms','Later synthetic terms','sv',false)::text,true);
select lives_ok($$select save_seller_with_agreement(current_setting('test.tenant')::uuid,current_setting('test.edit')::uuid,current_setting('test.new')::uuid,1,jsonb_set(current_setting('test.profile')::jsonb,'{name}','"Changed TEST"'),current_setting('test.next')::uuid,'Paper TEST')$$,'confirmed edit replays after a new publication');
set local "request.jwt.claims"='{"sub":"30100000-0000-4000-8000-000000000002","role":"authenticated"}';
select throws_ok($$select agreement_sellers(current_setting('test.tenant')::uuid,current_setting('test.next')::uuid,'','all',0)$$,'42501',null,'another account cannot read seller acceptances');
select throws_ok($$select save_seller_with_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),null,null,current_setting('test.profile')::jsonb,current_setting('test.latest')::uuid,'Paper TEST')$$,'42501',null,'another account cannot register evidence');
reset role;
insert into public.tenant_members(tenant_id,user_id,role) values(current_setting('test.tenant')::uuid,'30100000-0000-4000-8000-000000000002','readonly');
set local role authenticated;
select lives_ok($$select agreement_sellers(current_setting('test.tenant')::uuid,current_setting('test.latest')::uuid,'','all',0)$$,'readonly staff can inspect acceptances');
select throws_ok($$select save_seller_with_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),null,null,current_setting('test.profile')::jsonb,current_setting('test.latest')::uuid,'Paper TEST')$$,'42501',null,'readonly staff cannot record acceptance');
reset role;
insert into auth.mfa_factors(id,user_id,factor_type,status,created_at,updated_at) values(gen_random_uuid(),'30100000-0000-4000-8000-000000000001','totp','verified',now(),now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"30100000-0000-4000-8000-000000000001","role":"authenticated","aal":"aal1"}';
select throws_ok($$select agreement_sellers(current_setting('test.tenant')::uuid,current_setting('test.latest')::uuid,'','all',0)$$,'42501',null,'MFA remains required for acceptance register');
select throws_ok($$select save_seller_with_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),null,null,current_setting('test.profile')::jsonb,current_setting('test.latest')::uuid,'Paper TEST')$$,'42501',null,'MFA remains required for acceptance recording');
reset role;
select ok(not has_function_privilege('anon','public.agreement_sellers(uuid,uuid,text,text,integer)','execute'),'anonymous access denied');
select ok(not has_function_privilege('anon','public.save_seller_with_agreement(uuid,uuid,uuid,integer,jsonb,uuid,text)','execute'),'anonymous combined write denied');
select * from finish();
rollback;
