begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
 ('30200000-0000-4000-8000-000000000001','owner@agreement-languages.test',now()),
 ('30200000-0000-4000-8000-000000000002','seller@agreement-languages.test',now()),
 ('30200000-0000-4000-8000-000000000003','outsider@agreement-languages.test',now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"30200000-0000-4000-8000-000000000001","role":"authenticated"}';
select set_config('test.tenant',create_tenant('Languages TEST','agreement-languages-test',gen_random_uuid())::text,true);
select set_config('test.agreement',publish_seller_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),null,'TEST svenska','Synthetic Swedish terms','sv',true)::text,true);
select set_config('test.translation',gen_random_uuid()::text,true);
select lives_ok($$select publish_agreement_translation(current_setting('test.tenant')::uuid,current_setting('test.translation')::uuid,current_setting('test.agreement')::uuid,'TEST English','Synthetic English terms','en')$$,'owner adds a language to current version');
select lives_ok($$select publish_agreement_translation(current_setting('test.tenant')::uuid,current_setting('test.translation')::uuid,current_setting('test.agreement')::uuid,'TEST English','Synthetic English terms','en')$$,'publication retry preserves exact text');
select throws_like($$select publish_agreement_translation(current_setting('test.tenant')::uuid,current_setting('test.translation')::uuid,current_setting('test.agreement')::uuid,'Changed','Synthetic English terms','en')$$,'%REQUEST_CONFLICT%','retry cannot rewrite translation');
select throws_like($$select publish_agreement_translation(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.agreement')::uuid,'Duplicate','Duplicate','en')$$,'%INVALID_INPUT%','one immutable text per language/version');
select throws_like($$select publish_agreement_translation(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.agreement')::uuid,'Duplicate','Duplicate','sv')$$,'%INVALID_INPUT%','base language cannot be replaced');
select is((select count(*) from seller_agreement_versions where tenant_id=current_setting('test.tenant')::uuid),1::bigint,'translation does not create new terms version');
select set_config('test.seller',register_seller(current_setting('test.tenant')::uuid,gen_random_uuid(),'Seller TEST','seller@agreement-languages.test','')::text,true);
select set_config('test.evidence',gen_random_uuid()::text,true);
select lives_ok($$select record_agreement_evidence_text(current_setting('test.tenant')::uuid,current_setting('test.evidence')::uuid,current_setting('test.seller')::uuid,current_setting('test.agreement')::uuid,'English paper TEST',current_setting('test.translation')::uuid)$$,'staff records exact translated text');
select is((select translation_id::text from seller_agreement_evidence where id=current_setting('test.evidence')::uuid),current_setting('test.translation'),'evidence retains exact translation');
select lives_ok($$select receive_bag_with_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,'TEST',current_setting('test.agreement')::uuid)$$,'translated acceptance satisfies existing receipt gate');
select is((agreement_sellers(current_setting('test.tenant')::uuid,current_setting('test.agreement')::uuid,'','accepted',0)->>'total')::int,1,'register counts acceptance across languages');
select throws_like($$select record_agreement_evidence(current_setting('test.tenant')::uuid,current_setting('test.evidence')::uuid,current_setting('test.seller')::uuid,current_setting('test.agreement')::uuid,'English paper TEST')$$,'%REQUEST_CONFLICT%','legacy retry cannot change accepted language');
select is(jsonb_array_length(seller_data_export(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid)->'acceptedAgreementTranslations'),1,'export retains accepted translation text');
set local "request.jwt.claims"='{"sub":"30200000-0000-4000-8000-000000000002","role":"authenticated"}';
select is(my_seller_agreement_text(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,null,0,null)->'agreement'->>'body','Synthetic English terms','portal defaults to exact accepted text');
select is(jsonb_array_length(my_seller_agreement_text(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,null,0,null)->'languages'),2,'seller sees available languages');
select set_config('test.portal',gen_random_uuid()::text,true);
select lives_ok($$select accept_my_seller_agreement_text(current_setting('test.tenant')::uuid,current_setting('test.portal')::uuid,current_setting('test.seller')::uuid,current_setting('test.agreement')::uuid,current_setting('test.translation')::uuid)$$,'seller can accept translated terms');
select throws_like($$select accept_my_seller_agreement(current_setting('test.tenant')::uuid,current_setting('test.portal')::uuid,current_setting('test.seller')::uuid,current_setting('test.agreement')::uuid)$$,'%REQUEST_CONFLICT%','portal retry pins language');
set local "request.jwt.claims"='{"sub":"30200000-0000-4000-8000-000000000003","role":"authenticated"}';
select is((select count(*) from seller_agreement_translations),0::bigint,'outsider cannot read raw translations');
select throws_ok($$select my_seller_agreement_text(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,null,0,null)$$,'42501',null,'outsider cannot read portal translations');
select throws_ok($$select publish_agreement_translation(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.agreement')::uuid,'TEST','TEST','de')$$,'42501',null,'outsider cannot publish');
set local "request.jwt.claims"='{"sub":"30200000-0000-4000-8000-000000000001","role":"authenticated"}';
select set_config('test.registration',gen_random_uuid()::text,true);
select set_config('test.profile','{"name":"Translated registration TEST","email":"","phone":"0103","nationalId":"","addressLine1":"","addressLine2":"","postalCode":"","city":"","country":"","language":"","notes":""}',true);
select lives_ok($$select save_seller_with_agreement_text(current_setting('test.tenant')::uuid,current_setting('test.registration')::uuid,null,null,current_setting('test.profile')::jsonb,current_setting('test.agreement')::uuid,'Translated paper',current_setting('test.translation')::uuid)$$,'combined registration records translated evidence');
select is((select translation_id::text from seller_agreement_evidence where id=current_setting('test.registration')::uuid),current_setting('test.translation'),'combined registration retains language');
select throws_like($$select save_seller_with_agreement(current_setting('test.tenant')::uuid,current_setting('test.registration')::uuid,null,null,current_setting('test.profile')::jsonb,current_setting('test.agreement')::uuid,'Translated paper')$$,'%REQUEST_CONFLICT%','combined retry cannot switch to base text');
select set_config('test.invalid_registration',gen_random_uuid()::text,true);
select throws_like($$select save_seller_with_agreement_text(current_setting('test.tenant')::uuid,current_setting('test.invalid_registration')::uuid,null,null,current_setting('test.profile')::jsonb,current_setting('test.agreement')::uuid,'Translated paper',gen_random_uuid())$$,'%INVALID_INPUT%','invalid text refuses combined registration');
select is((select count(*) from sellers where id=current_setting('test.invalid_registration')::uuid),0::bigint,'invalid text rolls back seller');
select set_config('test.next',publish_seller_agreement(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.agreement')::uuid,'New TEST','New terms','sv',true)::text,true);
select throws_like($$select record_agreement_evidence_text(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,current_setting('test.next')::uuid,'TEST',current_setting('test.translation')::uuid)$$,'%INVALID_INPUT%','translation from old version cannot evidence new version');
select throws_like($$select publish_agreement_translation(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.agreement')::uuid,'TEST','TEST','de')$$,'%AGREEMENT_CHANGED%','old version cannot gain new translations');
select lives_ok($$select publish_agreement_translation(current_setting('test.tenant')::uuid,current_setting('test.translation')::uuid,current_setting('test.agreement')::uuid,'TEST English','Synthetic English terms','en')$$,'publication retry survives newer agreement');
select lives_ok($$select record_agreement_evidence_text(current_setting('test.tenant')::uuid,current_setting('test.evidence')::uuid,current_setting('test.seller')::uuid,current_setting('test.agreement')::uuid,'English paper TEST',current_setting('test.translation')::uuid)$$,'evidence retry survives newer agreement');
set local "request.jwt.claims"='{"sub":"30200000-0000-4000-8000-000000000002","role":"authenticated"}';
select is(my_seller_agreement_text(current_setting('test.tenant')::uuid,current_setting('test.seller')::uuid,current_setting('test.agreement')::uuid,0,null)->'agreement'->>'body','Synthetic English terms','archive retains exact translated text');
select throws_like($$select accept_my_seller_agreement_text(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,current_setting('test.agreement')::uuid,current_setting('test.translation')::uuid)$$,'%AGREEMENT_CHANGED%','obsolete translation cannot receive new acceptance');
reset role;
select throws_like($$update seller_agreement_translations set body='Changed' where id=current_setting('test.translation')::uuid$$,'%IMMUTABLE_AGREEMENT_RECORD%','translation immutable');
select ok(not has_table_privilege('authenticated','seller_agreement_translations','insert'),'no direct translation writes');
select ok(not has_function_privilege('anon','public.publish_agreement_translation(uuid,uuid,uuid,text,text,text)','execute'),'anonymous publication denied');
insert into public.tenant_members(tenant_id,user_id,role) values(current_setting('test.tenant')::uuid,'30200000-0000-4000-8000-000000000003','readonly');
set local role authenticated;
set local "request.jwt.claims"='{"sub":"30200000-0000-4000-8000-000000000003","role":"authenticated"}';
select is((select count(*) from seller_agreement_translations),1::bigint,'readonly staff can read translations');
select throws_ok($$select publish_agreement_translation(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.next')::uuid,'TEST','TEST','en')$$,'42501',null,'readonly cannot publish');
select throws_ok($$select record_agreement_evidence_text(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.seller')::uuid,current_setting('test.next')::uuid,'TEST',null)$$,'42501',null,'readonly cannot attest');
reset role;
insert into auth.mfa_factors(id,user_id,factor_type,status,created_at,updated_at) values(gen_random_uuid(),'30200000-0000-4000-8000-000000000001','totp','verified',now(),now());
set local role authenticated;
set local "request.jwt.claims"='{"sub":"30200000-0000-4000-8000-000000000001","role":"authenticated","aal":"aal1"}';
select is((select count(*) from seller_agreement_translations),0::bigint,'MFA protects translation reads');
select throws_ok($$select publish_agreement_translation(current_setting('test.tenant')::uuid,gen_random_uuid(),current_setting('test.next')::uuid,'TEST','TEST','en')$$,'42501',null,'MFA protects publication');
select throws_ok($$select save_seller_with_agreement_text(current_setting('test.tenant')::uuid,gen_random_uuid(),null,null,current_setting('test.profile')::jsonb,current_setting('test.next')::uuid,'TEST',null)$$,'42501',null,'MFA protects combined registration');
select * from finish();
rollback;
