import type { Locale } from './i18n'

// Stable answer codes live in the engine; only presentation is translated here.
const keys = [
  'title',
  'intro',
  'intake',
  'goods',
  'pricing',
  'checkout',
  'period',
  'pos',
  'channels',
  'multi',
  'single',
  'next',
  'back',
  'summary',
  'save',
  'saving',
  'saved',
  'edit',
  'home',
  'step',
  'of',
  'readonly',
  'notice',
  'unsupported',
  'failed',
  'conflict',
  'tenantChanged',
  'auth',
  'singleItem',
  'bags',
  'owned',
  'new',
  'pickup',
  'space',
  'other',
  'clothes',
  'kids',
  'furniture',
  'homeGoods',
  'hobby',
  'mixed',
  'store',
  'together',
  'seller',
  'suggestion',
  'both',
  'later',
  'collect',
  'donate',
  'extend',
  'individual',
  'shop',
  'web',
  'social',
  'market',
  'start',
] as const
export type GuideCopy = Record<(typeof keys)[number], string>
const rows: Record<Locale, string[]> = {
  sv: [
    'Er butik. Ert sätt.',
    'Berätta hur ni vill arbeta. Ni kan ändra svaren senare.',
    'Hur får ni in varor till butiken?',
    'Vad fyller ni butiken med?',
    'Vem bestämmer priset',
    'Vem tar hand om kassan?',
    'Och om varan inte blir såld?',
    'Vilket kassasystem vill ni köra?',
    'Var möter ni era köpare?',
    'Välj alla alternativ som passar.',
    'Välj ett alternativ.',
    'Nästa',
    'Tillbaka',
    'Det här är er butik',
    'Spara butikens svar',
    'Sparar…',
    'Svaren är sparade för',
    'Ändra svar',
    'Till startsidan',
    'Fråga',
    'av',
    'Du kan läsa butikens svar. Ägare och administratörer kan ändra dem.',
    'Svaren beskriver ert arbetssätt. Avtal, priser och ekonomiska regler ställs in separat.',
    'Vissa val beskriver önskemål som ännu inte stöds fullt ut: platsuthyrning, hämtning, nya varor och marknadsplatser.',
    'Kunde inte spara. Försök igen.',
    'Svaren har ändrats i en annan flik. Ladda om sidan innan du sparar.',
    'Aktiv butik har ändrats. Ladda om sidan för rätt butik.',
    'Logga in igen för att spara.',
    'Säljare lämnar enskilda varor',
    'Säljare lämnar flera varor vid samma tillfälle',
    'Vi köper in secondhandvaror',
    'Vi köper in nya varor',
    'Vi hämtar varor hemma hos säljaren',
    'Säljare hyr en plats och tar med sina varor',
    'På annat sätt',
    'Kläder & accessoarer',
    'Barnkläder & leksaker',
    'Möbler',
    'Hem & inredning',
    'Sport, fritid & hobby',
    'Lite av allt',
    'Vi i butiken',
    'Vi och säljaren',
    'Säljaren',
    'Vi vill ha prisförslag',
    'Båda sätten',
    'Inte bestämt än',
    'Säljaren hämtar tillbaka',
    'Vi vill kunna skänka vidare',
    'Vi erbjuder mer försäljningstid',
    'Vi kommer överens från fall till fall',
    'I den fysiska butiken',
    'I vår webbshop',
    'Via sociala medier',
    'På marknadsplatser',
    'Butiksguiden',
  ],
  en: [
    'Your store. Your way.',
    'Tell us how you want to work. You can change your answers later.',
    'How do items arrive at your store?',
    'What do you sell?',
    'Who sets the price?',
    'Who handles checkout?',
    'What if an item does not sell?',
    'Which POS system would you like to use?',
    'Where do you meet your buyers?',
    'Choose all that apply.',
    'Choose one option.',
    'Next',
    'Back',
    'This is your store',
    'Save store answers',
    'Saving…',
    'Answers saved for',
    'Edit answers',
    'Go to home',
    'Question',
    'of',
    'You can read the store’s answers. Owners and admins can edit them.',
    'These answers describe how you work. Agreements, prices and financial rules are configured separately.',
    'Some choices describe workflows not yet fully supported: space rental, collection, new goods and marketplaces.',
    'Could not save. Please try again.',
    'Answers changed in another tab. Reload before saving.',
    'The active store changed. Reload to use the correct store.',
    'Sign in again to save.',
    'Sellers bring individual items',
    'Sellers bring bags or boxes',
    'We buy second-hand goods',
    'We buy new goods',
    'We collect items from sellers’ homes',
    'Sellers rent a space and bring their goods',
    'Another way',
    'Clothes & accessories',
    'Children’s clothes & toys',
    'Furniture',
    'Home & interiors',
    'Sport, leisure & hobbies',
    'A bit of everything',
    'Our store',
    'Our store and the seller',
    'The seller',
    'We would like price suggestions',
    'Both ways',
    'Not decided yet',
    'The seller collects it',
    'We would like to donate it',
    'We offer more time to sell',
    'We agree case by case',
    'In the physical store',
    'In our online store',
    'Through social media',
    'On marketplaces',
    'Store guide',
  ],
  no: [
    'Deres butikk. Deres måte.',
    'Fortell hvordan dere vil jobbe. Svarene kan endres senere.',
    'Hvordan får dere varer inn i butikken?',
    'Hva fyller dere butikken med?',
    'Hvem bestemmer prisen?',
    'Hvem tar hånd om kassen?',
    'Hva om varen ikke blir solgt?',
    'Hvilket kassasystem vil dere bruke?',
    'Hvor møter dere kjøperne?',
    'Velg alle alternativene som passer.',
    'Velg ett alternativ.',
    'Neste',
    'Tilbake',
    'Dette er deres butikk',
    'Lagre butikkens svar',
    'Lagrer…',
    'Svarene er lagret for',
    'Endre svar',
    'Til startsiden',
    'Spørsmål',
    'av',
    'Du kan lese butikkens svar. Eiere og administratorer kan endre dem.',
    'Svarene beskriver arbeidsmåten deres. Avtaler, priser og økonomiske regler settes opp separat.',
    'Noen valg gjelder funksjoner som ennå ikke støttes fullt ut: plassutleie, henting, nye varer og markedsplasser.',
    'Kunne ikke lagre. Prøv igjen.',
    'Svarene er endret i en annen fane. Last siden på nytt før du lagrer.',
    'Aktiv butikk er endret. Last siden på nytt for riktig butikk.',
    'Logg inn igjen for å lagre.',
    'Selgere leverer enkeltvarer',
    'Selgere leverer poser eller esker',
    'Vi kjøper inn brukte varer',
    'Vi kjøper inn nye varer',
    'Vi henter varer hjemme hos selgeren',
    'Selgere leier en plass og tar med varene sine',
    'På en annen måte',
    'Klær og tilbehør',
    'Barneklær og leker',
    'Møbler',
    'Hjem og interiør',
    'Sport, fritid og hobby',
    'Litt av alt',
    'Vi i butikken',
    'Vi og selgeren',
    'Selgeren',
    'Vi ønsker prisforslag',
    'Begge deler',
    'Ikke bestemt ennå',
    'Selgeren henter varen',
    'Vi ønsker å kunne donere varen',
    'Vi tilbyr lengre salgstid',
    'Vi avtaler fra tilfelle til tilfelle',
    'I den fysiske butikken',
    'I nettbutikken vår',
    'Via sosiale medier',
    'På markedsplasser',
    'Butikkguiden',
  ],
  dk: [
    'Jeres butik. Jeres måde.',
    'Fortæl, hvordan I vil arbejde. I kan ændre svarene senere.',
    'Hvordan får I varer ind i butikken?',
    'Hvad fylder I butikken med?',
    'Hvem bestemmer prisen?',
    'Hvem står for kassen?',
    'Hvad hvis varen ikke bliver solgt?',
    'Hvilket kassesystem vil I bruge?',
    'Hvor møder I jeres købere?',
    'Vælg alle de muligheder, der passer.',
    'Vælg én mulighed.',
    'Næste',
    'Tilbage',
    'Dette er jeres butik',
    'Gem butikkens svar',
    'Gemmer…',
    'Svarene er gemt for',
    'Rediger svar',
    'Til forsiden',
    'Spørgsmål',
    'af',
    'Du kan læse butikkens svar. Ejere og administratorer kan ændre dem.',
    'Svarene beskriver jeres arbejdsgang. Aftaler, priser og økonomiske regler indstilles separat.',
    'Nogle valg gælder funktioner, der endnu ikke understøttes fuldt ud: pladsudlejning, afhentning, nye varer og markedspladser.',
    'Kunne ikke gemme. Prøv igen.',
    'Svarene er ændret i en anden fane. Genindlæs siden, før du gemmer.',
    'Den aktive butik er ændret. Genindlæs siden for den rigtige butik.',
    'Log ind igen for at gemme.',
    'Sælgere afleverer enkelte varer',
    'Sælgere afleverer poser eller kasser',
    'Vi køber brugte varer ind',
    'Vi køber nye varer ind',
    'Vi henter varer hjemme hos sælgeren',
    'Sælgere lejer en plads og tager deres varer med',
    'På en anden måde',
    'Tøj og tilbehør',
    'Børnetøj og legetøj',
    'Møbler',
    'Bolig og indretning',
    'Sport, fritid og hobby',
    'Lidt af hvert',
    'Vi i butikken',
    'Vi og sælgeren',
    'Sælgeren',
    'Vi ønsker prisforslag',
    'Begge dele',
    'Ikke besluttet endnu',
    'Sælgeren henter varen',
    'Vi vil gerne kunne donere varen',
    'Vi tilbyder længere salgstid',
    'Vi aftaler det fra sag til sag',
    'I den fysiske butik',
    'I vores webshop',
    'Via sociale medier',
    'På markedspladser',
    'Butiksguiden',
  ],
  fi: [
    'Teidän myymälänne. Teidän tapanne.',
    'Kertokaa, miten haluatte toimia. Vastauksia voi muuttaa myöhemmin.',
    'Miten tavarat tulevat myymäläänne?',
    'Mitä myymälässänne myydään?',
    'Kuka päättää hinnan?',
    'Kuka hoitaa kassan?',
    'Entä jos tavara ei mene kaupaksi?',
    'Mitä kassajärjestelmää haluatte käyttää?',
    'Missä kohtaatte ostajanne?',
    'Valitse kaikki sopivat vaihtoehdot.',
    'Valitse yksi vaihtoehto.',
    'Seuraava',
    'Takaisin',
    'Tällainen on myymälänne',
    'Tallenna myymälän vastaukset',
    'Tallennetaan…',
    'Vastaukset tallennettu myymälälle',
    'Muokkaa vastauksia',
    'Etusivulle',
    'Kysymys',
    '/',
    'Voit lukea myymälän vastaukset. Omistajat ja ylläpitäjät voivat muokata niitä.',
    'Vastaukset kuvaavat toimintatapaanne. Sopimukset, hinnat ja taloussäännöt määritetään erikseen.',
    'Kaikkia toimintatapoja ei vielä tueta täysin: paikanvuokraus, noudot, uudet tavarat ja markkinapaikat.',
    'Tallennus epäonnistui. Yritä uudelleen.',
    'Vastauksia muutettiin toisessa välilehdessä. Lataa sivu uudelleen ennen tallennusta.',
    'Aktiivinen myymälä vaihtui. Lataa sivu uudelleen.',
    'Kirjaudu uudelleen sisään tallentaaksesi.',
    'Myyjät tuovat yksittäisiä tavaroita',
    'Myyjät tuovat kasseja tai laatikoita',
    'Ostamme käytettyjä tavaroita',
    'Ostamme uusia tavaroita',
    'Noudamme tavarat myyjän kotoa',
    'Myyjät vuokraavat paikan ja tuovat tavaransa',
    'Muulla tavalla',
    'Vaatteet ja asusteet',
    'Lastenvaatteet ja lelut',
    'Huonekalut',
    'Koti ja sisustus',
    'Urheilu, vapaa-aika ja harrastukset',
    'Vähän kaikkea',
    'Me myymälässä',
    'Me ja myyjä yhdessä',
    'Myyjä',
    'Haluamme hintaehdotuksia',
    'Molemmilla tavoilla',
    'Ei vielä päätetty',
    'Myyjä noutaa tavaran',
    'Haluamme lahjoittaa tavaran',
    'Tarjoamme lisää myyntiaikaa',
    'Sovimme tapauskohtaisesti',
    'Fyysisessä myymälässä',
    'Verkkokaupassamme',
    'Sosiaalisen median kautta',
    'Markkinapaikoilla',
    'Myymäläopas',
  ],
  de: [
    'Ihr Laden. Ihr Weg.',
    'Wie möchten Sie arbeiten? Sie können die Antworten später ändern.',
    'Wie kommen die Waren in Ihren Laden?',
    'Was verkaufen Sie?',
    'Wer bestimmt den Preis?',
    'Wer übernimmt die Kasse?',
    'Was passiert, wenn ein Artikel nicht verkauft wird?',
    'Welches Kassensystem möchten Sie nutzen?',
    'Wo erreichen Sie Ihre Käufer?',
    'Wählen Sie alles Zutreffende aus.',
    'Wählen Sie eine Option.',
    'Weiter',
    'Zurück',
    'Das ist Ihr Laden',
    'Antworten speichern',
    'Wird gespeichert…',
    'Antworten gespeichert für',
    'Antworten bearbeiten',
    'Zur Startseite',
    'Frage',
    'von',
    'Sie können die Antworten lesen. Inhaber und Administratoren können sie ändern.',
    'Die Antworten beschreiben Ihre Arbeitsweise. Verträge, Preise und Finanzregeln werden separat eingerichtet.',
    'Einige Abläufe werden noch nicht vollständig unterstützt: Flächenvermietung, Abholung, Neuware und Marktplätze.',
    'Speichern fehlgeschlagen. Bitte erneut versuchen.',
    'Die Antworten wurden in einem anderen Tab geändert. Laden Sie die Seite vor dem Speichern neu.',
    'Der aktive Laden wurde gewechselt. Laden Sie die Seite neu.',
    'Melden Sie sich zum Speichern erneut an.',
    'Verkäufer bringen einzelne Artikel',
    'Verkäufer bringen Taschen oder Kartons',
    'Wir kaufen gebrauchte Waren ein',
    'Wir kaufen neue Waren ein',
    'Wir holen Waren bei Verkäufern zu Hause ab',
    'Verkäufer mieten eine Fläche und bringen ihre Waren',
    'Auf andere Weise',
    'Kleidung und Accessoires',
    'Kinderkleidung und Spielzeug',
    'Möbel',
    'Wohnen und Einrichtung',
    'Sport, Freizeit und Hobby',
    'Von allem etwas',
    'Wir im Laden',
    'Wir und der Verkäufer',
    'Der Verkäufer',
    'Wir möchten Preisvorschläge',
    'Beides',
    'Noch nicht entschieden',
    'Der Verkäufer holt den Artikel ab',
    'Wir möchten den Artikel spenden',
    'Wir bieten mehr Verkaufszeit an',
    'Wir entscheiden von Fall zu Fall',
    'Im Laden',
    'In unserem Onlineshop',
    'Über soziale Medien',
    'Auf Marktplätzen',
    'Laden-Assistent',
  ],
  es: [
    'Tu tienda. A tu manera.',
    'Cuéntanos cómo quieres trabajar. Puedes cambiar las respuestas después.',
    '¿Cómo llegan los artículos a tu tienda?',
    '¿Qué vendes en tu tienda?',
    '¿Quién decide el precio?',
    '¿Quién se encarga de la caja?',
    '¿Y si el artículo no se vende?',
    '¿Qué sistema de punto de venta quieres usar?',
    '¿Dónde encuentras a tus compradores?',
    'Elige todas las opciones que correspondan.',
    'Elige una opción.',
    'Siguiente',
    'Atrás',
    'Así es tu tienda',
    'Guardar respuestas',
    'Guardando…',
    'Respuestas guardadas para',
    'Editar respuestas',
    'Ir al inicio',
    'Pregunta',
    'de',
    'Puedes leer las respuestas. Los propietarios y administradores pueden cambiarlas.',
    'Las respuestas describen tu forma de trabajar. Los acuerdos, precios y reglas financieras se configuran por separado.',
    'Algunas opciones aún no tienen soporte completo: alquiler de espacios, recogida, productos nuevos y plataformas de venta.',
    'No se pudo guardar. Inténtalo de nuevo.',
    'Las respuestas cambiaron en otra pestaña. Recarga antes de guardar.',
    'La tienda activa ha cambiado. Recarga la página.',
    'Vuelve a iniciar sesión para guardar.',
    'Los vendedores traen artículos sueltos',
    'Los vendedores traen bolsas o cajas',
    'Compramos artículos de segunda mano',
    'Compramos productos nuevos',
    'Recogemos artículos en casa del vendedor',
    'Los vendedores alquilan un espacio y traen sus artículos',
    'De otra manera',
    'Ropa y accesorios',
    'Ropa infantil y juguetes',
    'Muebles',
    'Hogar y decoración',
    'Deporte, ocio y aficiones',
    'Un poco de todo',
    'Nosotros en la tienda',
    'Nosotros y el vendedor',
    'El vendedor',
    'Queremos sugerencias de precios',
    'De ambas maneras',
    'Aún no lo hemos decidido',
    'El vendedor lo recoge',
    'Queremos poder donarlo',
    'Ofrecemos más tiempo de venta',
    'Lo acordamos caso por caso',
    'En la tienda física',
    'En nuestra tienda online',
    'Por redes sociales',
    'En plataformas de venta',
    'Guía de la tienda',
  ],
  it: [
    'Il tuo negozio. A modo tuo.',
    'Raccontaci come vuoi lavorare. Puoi modificare le risposte in seguito.',
    'Come arrivano gli articoli nel tuo negozio?',
    'Che cosa vendi nel negozio?',
    'Chi decide il prezzo?',
    'Chi gestisce la cassa?',
    'E se un articolo non viene venduto?',
    'Quale sistema di cassa vuoi usare?',
    'Dove incontri i tuoi acquirenti?',
    'Scegli tutte le opzioni pertinenti.',
    'Scegli un’opzione.',
    'Avanti',
    'Indietro',
    'Ecco il tuo negozio',
    'Salva le risposte',
    'Salvataggio…',
    'Risposte salvate per',
    'Modifica le risposte',
    'Vai alla pagina iniziale',
    'Domanda',
    'di',
    'Puoi leggere le risposte. Proprietari e amministratori possono modificarle.',
    'Le risposte descrivono il tuo modo di lavorare. Accordi, prezzi e regole finanziarie si impostano separatamente.',
    'Alcune opzioni non sono ancora pienamente supportate: affitto di spazi, ritiro, prodotti nuovi e marketplace.',
    'Salvataggio non riuscito. Riprova.',
    'Le risposte sono cambiate in un’altra scheda. Ricarica prima di salvare.',
    'Il negozio attivo è cambiato. Ricarica la pagina.',
    'Accedi nuovamente per salvare.',
    'I venditori portano singoli articoli',
    'I venditori portano borse o scatole',
    'Acquistiamo articoli di seconda mano',
    'Acquistiamo prodotti nuovi',
    'Ritiriamo gli articoli a casa del venditore',
    'I venditori affittano uno spazio e portano i loro articoli',
    'In un altro modo',
    'Abbigliamento e accessori',
    'Abbigliamento per bambini e giocattoli',
    'Mobili',
    'Casa e arredamento',
    'Sport, tempo libero e hobby',
    'Un po’ di tutto',
    'Noi del negozio',
    'Noi e il venditore',
    'Il venditore',
    'Vorremmo suggerimenti sui prezzi',
    'Entrambi i modi',
    'Non ancora deciso',
    'Il venditore ritira l’articolo',
    'Vorremmo poterlo donare',
    'Offriamo più tempo per la vendita',
    'Concordiamo caso per caso',
    'Nel negozio fisico',
    'Nel nostro negozio online',
    'Tramite i social media',
    'Sui marketplace',
    'Guida del negozio',
  ],
}
export function guideCopy(locale: Locale): GuideCopy {
  const values = rows[locale]
  if (values.length !== keys.length)
    throw new Error(`Incomplete guide translation: ${locale}`)
  return Object.fromEntries(
    keys.map((key, index) => [key, values[index]]),
  ) as GuideCopy
}
